### ISSUE TITLE
Submit a new version with an IAP

### ISSUE THREAD

**Issue by dankokp** [fastlane/fastlane#10041]
Hi,
I have a problem with in-app purchases. I'm able to successfully create a new IAP using spaceship "in_app_purchases.create". But after this I have to submit a new version to ITC with this IAP. I don't see a way to do it using fastlane deliver or spaceship. Is there a way to do it at all?
Thank you!

**Comment by taquitos** [comment]
I know you mentioned using spaceship, but maybe you could use _gym_ + `increment_build_number`+ _deliver_ to accomplish that? I'm just thinking out loud here because apple mentions:

> Your first In-App Purchase must be submitted with a new app version.

So after creating a new IAP, you'll need to create a new release + rebuild the app with a new build version to meet apple's criteria. 
Maybe you can use _fastlane_ to automate that part?

**Comment by dankokp** [comment]
Hi taquitos,
Thank you for advice, but unfortunately it doesn't work

**Comment by FranciscoMSM** [comment]
Is there any option in the API to just sent the IAP to revision? We don't need to upload a new version of the app if we already have IAP's available on current version.

I checked the code and I don't think so. Anyone with a less tedious way to send multiple IAP's to revision? :)
