### ISSUE TITLE
[Match] : Auto-Generate / Auto-Repair Certificate and Provisioning Profile in case of Expired / Revoked / Deleted scenarios

### ISSUE THREAD

**Issue by ramnac** [fastlane/fastlane#10395]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Developer Account is in a clean state
Match been used to create a Distribution Certificate and a Provisioning Profile. 
When the Certificate gets expired / revoked
Match throws an error "Certificate 'XXXXXX' (stored in your git repo) is not available on the Developer Portal"

The problem here is Match validation fails because the certificate gets disappeared from the developer portal when Certificate gets expired / revoked.

What I am suggesting is, Match should Auto-Repair, i.e.,
In the above scenario, Match should remove the p12 and cer file from the git repo
And then create a new certificate ( Sync it in the git repo )
After fixing the certificate, the provisioning profile should also be Fixed ( because when the certificate gets expired, Provisioning profile status changes to expired )

By following the above suggestion, Match will not throw "Certificate 'XXXXXX' (stored in your git repo) is not available on the Developer Portal"

The same problem exists for Provisioning profile as well
When the provisioning profile gets deleted from the developer portal
Match throws an error "Provisioing profile XXXX is not available on the Developer Portal"

Match should rather create a new one.

I can submit a PR for this. 

I feel many are facing this issue.

**Comment by ram0287** [comment]
@KrauseFx - Any comments on this ? I am nearly done with the pull request

**Comment by ram0287** [comment]
@KrauseFx - you might be busy, but would be happy if you can reply to this. Waiting to hear your thoughts.

**Comment by KrauseFx** [comment]
That's weird, _match_ should auto-repair the certificate and with it the associated provisioning profiles. What has to change in the fastlane code base to fix this issue?

**Comment by ram0287** [comment]
In the above scenario, fastlane will fail in the method **_certificate_exists_** in **_spaceship_ensure.rb_**

It is because of UI.user_error!("To reset the certificates of your Apple account, you can use the `match nuke` feature, more information on https://github.com/fastlane/fastlane/tree/master/match")

rather we should return nil from that method, and in the **_runner.rb_** 
inspite of these lines,
_# Certificate
cert_id = fetch_certificate(params: params)
spaceship.certificate_exists(username: params[:username], certificate_id: cert_id) if spaceship_

we need to change it to 
_# Certificate
cert_id = fetch_certificate(params: params)
if spaceship && !spaceship.certificate_exists(username: params[:username], certificate_id: cert_id)
    if self.files.count > 0
        delete_certs_and_profiles!
    end
    self.changes_to_commit = true
    # To create a new certificate
    cert_id = fetch_certificate(params: params)
end_

For provisioning profile, in **_spaceship_ensure.rb_**
Inspite of these lines,
_if found.valid?
        return found_

we need to change it to
_# Though Profile is in Active Status, When the Certificate is not valid, the status changes to Expired.
# So it's better to check both valid and certificate_valid
if found.valid? && found.certificate_valid?
        return found_

and few more. I can submit a PR.

**Comment by ram0287** [comment]
@KrauseFx - Any comments ?

**Comment by KrauseFx** [comment]
Hey @ram0287, sorry for the late reply, yeah that sounds great, please go ahead and submit a PR, and let's continue the discussion over there

**Comment by ram0287** [comment]
@KrauseFx - Thank you 👍 

I am working on this. Just have to change few bits because of few new changes ( files_to_commit )
