### ISSUE TITLE
Not possible to use "hockey" with dSYM-only

### ISSUE THREAD

**Issue by awBSH** [fastlane/fastlane#10499]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I want to download dSYM from ITC and upload it to HockeyApp, without uploading the IPA to HockeyApp. I use the following lane:

    download_dsyms(
      app_identifier: "my.bundle.identifier",
      team_id: "123456789",
      build_number: "4711"
    )
    hockey(
      api_token: "MY_API_TOKEN",
      upload_dsym_only: true
    )

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 3    | download_dsyms      | 21          |
| 💥   | hockey              | 0           |
+------+---------------------+-------------+

[15:59:11]: fastlane finished with errors

[!] You have to provide a build file

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

Do I really need to provide a build (ipa?) even if I just want to upload the dSYM to HockeyApp?

**Comment by szweier** [comment]
@awBSH I just came across the same issue. When I did some digging into it I noticed that the check for having to provide a build file is actually within the else checking for a dsym file.

```
if options[:dsym]
          dsym_filename = options[:dsym]
        else

          if build_file.nil?
            UI.user_error!("You have to provide a build file")
          end
```

So it appears as though what you (and I) are trying to do is actually not providing the dSYM file to the hockey action. I'm not sure how to provide the dSYM file when using download_dsyms action as there is the potential for multiple dSYMs to be downloaded and need uploading. That being said, maybe this information helps you figure out a solution. If you do, please let me know what steps you took to solve the problem.

**Comment by janpio** [comment]
Yes, @szweier, what you write makes sense:

The `hockey` action expects either a `dsym` parameter or a default `SharedValues::DSYM_OUTPUT_PATH` which can be set by other actions (unchanged behaviour since 2 years ago): https://github.com/fastlane/fastlane/blob/fe7c424404466886a7fbfa107914283a37db3428/fastlane/lib/fastlane/actions/hockey.rb#L224

`download_dsym` doesn't set _that_ value, but sets `SharedValues::DSYM_PATHS` instead, which is an array: 
https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/download_dsyms.rb#L70-L71 (lines are unchanged since 2 years)

(Background why there are both `DSYM_OUTPUT_PATH` and DSYM_PATHS`: There are actions that create 1 dsym (e.g. `gym`), and actions that create multiple ones (e.g. `download_dsyms`). Both make sense in their own right.)

So what you could probably do, is to iterate over this array in your `Fastfile` and call `hockey` for each of them (which even works if it is just one). Would probably look something like this:

```
download_dsyms(
  app_identifier: "my.bundle.identifier",
  team_id: "123456789",
  build_number: "4711"
)
Actions.lane_context[SharedValues::DSYM_PATHS].each do |dsym_path|
  hockey(
    api_token: "MY_API_TOKEN",
    upload_dsym_only: true,
    dsym: dsym_path
  )
end
```
(100% untested - please tell me if it actually works, then I can add this to the code examples of `download_dsyms`)

**Comment by bguidolim** [comment]
Hello all!

`upload_dsym_only` didn't work correctly because it's not calling the correct URI to do that.

The [plugin](https://github.com/justin/fastlane-plugin-upload_symbols_to_hockey) actually use the correct URI, but not the correct parameter.

I've opened a pull request fixing that: https://github.com/justin/fastlane-plugin-upload_symbols_to_hockey/pull/1

But probably is better open a new PR to `hockey.rb`.

**Comment by janpio** [comment]
Good catch @bguidolim. Would be awesome if you could open a PR for that.

**Comment by bguidolim** [comment]
@janpio working on that now.
