### ISSUE TITLE
Manage release process of Fastlane plugins with `fastlane` itself

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#10552]
I asked in Slack if it was possible and would make sense to manage the release process of a Fastlane plugin with Fastlane. @KrauseFx replied that Fastlane itself is published with Fastlane:
https://github.com/fastlane/fastlane/blob/master/fastlane/Fastfile

Using parts of this of course one could also manage the release process of a Fastlane plugin.

Then @KrauseFx also suggested that this could be part of the default plugin template:
https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/plugins/template/fastlane/Fastfile.erb

TODO would be to extract the really important parts of the `Fastfile` and get rid of all the rest, test it, then put it into the plugin template.

**Comment by jdee** [comment]
Beyond advertising the versatility of Fastlane, I wonder how valuable this would be. `rake release` is a standard command known to gem developers. The existing plugin Rakefile doesn't seem to have anything specific to Fastlane, which is nice. The `:release` lane in the Fastfile here is huge, but as you suggest, only part of that would be added to a plugin. If there is something that you get here that isn't available with `rake release`, maybe a built-in action could be added to Fastlane like `release_plugin`. Then the plugin template could include a simple lane that includes that action, rather than a big, obtrusive lane. One of the main purposes of the Fastfile in a plugin is to provide examples, and the more that is introduced there for purposes of plugin maintenance, the more it dilutes that main purpose, so keeping it small (relegated to a built-in action) seems like a good idea.

**Comment by janpio** [comment]
In Slack I joked that one best extracted these actions to a plugin to release plugins...
(But yes, I have no idea what really is needed to release a plugin as I forked my first one a few days ago and am now trying to find out what to do why - I only suggested this as @KrauseFx didn't disagree to the idea)

**Comment by jdee** [comment]
Another approach might be to add something like `Fastfile.internal` to the plugin template and then `import` that into the main Fastfile.

One thing that might be nice: From time to time, things change in the general Ruby environment. For example, RuboCop updates and starts generating new warnings and failures. The .rubocop.yml in the main repo is reused in the plugin template. If the .rubocop.yml in the repo has been updated in the repo since you created the plugin, Fastlane could automatically update RuboCop and the .rubocop.yml in plugins as well. This might also apply to things like CI configuration. An automatic plugin update action could be useful.
