### ISSUE TITLE
exportOptionsPlist error for key 'method': expected one of {}, but found app-store

### ISSUE THREAD

**Issue by carloscuesta** [fastlane/fastlane#10559]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm building my application through gym, everything seems ok, the build succeeds the archieve succeeds but then I've got the following error:

Everything was working fine some weeks ago, could be the Xcode update?

```
[16:01:43]: Generated plist file with the following values:
[16:01:43]: ▸ -----------------------------------------
[16:01:43]: ▸ {
[16:01:43]: ▸   "provisioningProfiles": {
[16:01:43]: ▸     "com.app.mobile": "match AppStore com.app.mobile"
[16:01:43]: ▸   },
[16:01:43]: ▸   "method": "app-store"
[16:01:43]: ▸ }
[16:01:43]: ▸ -----------------------------------------

xcodebuild -exportArchive -exportOptionsPlist /var/folders/rc/3h6sm0jx5qlcyty903dtjpmh0000gn/T/gym_config20171010-7247-1py7ni1.plist -archivePath '/Users/carloscuesta/Library/Developer/Xcode/Archives/2017-10-10/app 2017-10-10 15.56.11.xcarchive' -exportPath /var/folders/rc/3h6sm0jx5qlcyty903dtjpmh0000gn/T/gym_output20171010-7247-tgw0cy
2017-10-10 16:01:44.739 xcodebuild[16662:2582386] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/rc/3h6sm0jx5qlcyty903dtjpmh0000gn/T/app_2017-10-10_16-01-44.739.xcdistributionlogs'.
error: exportArchive: exportOptionsPlist error for key 'method': expected one of {}, but found app-store

Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key 'method': expected one of {}, but found app-store" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key 'method': expected one of {}, but found app-store}

** EXPORT FAILED **
[16:01:44]: Exit status: 70

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.61.0                  |
| export_method | app-store               |
| sdk           | iPhoneOS11.0.sdk        |
+---------------+-------------------------+
```

### Environment

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.61.0  | ✅ Up-To-Date  |

```
| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |
```

**Comment by JeffBNimble** [comment]
@carloscuesta I just had the exact same problem. However, the problem for me was caused by me trying to run xcodebuild -exportArchive on an archive that was a generic archive instead of an app archive.

The way that you can easily test to see if your xcarchive is a valid App Store archive is to open the archive in Xcode. Xcode will tell you if your xcarchive is a generic archive or an App Store archive. If your exportOptions.plist has method=app-store, then your archive MUST be an App Store archive.

For me, the problem was that I had inadvertently changed some build settings for some private frameworks. The Skip Install build setting for those frameworks was inadvertently changed from NO to YES causing this problem.

For more info, you might check out this: https://developer.apple.com/library/content/technotes/tn2215/_index.html

I hope this helps.

**Comment by carloscuesta** [comment]
@JeffBNimble 

Definitely has to be this, for some reason the app is building as `Generic Xcode Archive` instead of an `App Store archieve`. I've checked all the libraries but everything seems to be OK on the `Skip install > Build settings` 🤔 

Thanks for your help,

**Comment by interstateone** [comment]
@carloscuesta I'm not sure that this is a fastlane/gym issue but I'm wondering if you can provide some more information for the sake of completeness for others that run into it. I ran into the same symptoms that you've described:

After trying to make a new release of our app that includes a new 3rd party library (distributed as a built framework through CocoaPods) xcodebuild (via gym) would make a generic archive instead of an app archive. During this time I believe we also switched from Xcode 9.0.x to 9.1, but I'm not sure if that's related.

The generic archive _only_ had the app in /Products/Applications, which is different from the other issues I've seen with generic archives that are due to multiple products or headers being "installed" in the archive.

I was able to get an app archive created by updating from CocoaPods 1.3.1 (current latest release) to the latest beta 1.4..beta.2 and reinstalling our pods. Looking at the diffs of the xcconfig and project files, it's not clear why this would have solved the issue and there's no mention of this in particular in the release notes.

> Seems like the last linked library was corrupting our archive even though the build was been successful

This is a good breadcrumb, but can you share what you did to solve the issue or any more information about the root of it?

Thanks!

**Comment by carloscuesta** [comment]
Hey @interstateone 

At the time of facing this issue, I was integrating the UrbanAirship's react-native SDK. Since we do not use CocoPods I had to link manually the SDK on both platforms iOS & Android.

At first glance I thought the Xcode update was the problem, but then I made a build from the `master` branch and everything finished successfully. 

The difference between the master branch and the one I was working on at that time was the link of the SDK. In order to solve the problem, I manually linked again the SDK starting from a new branch.
