### ISSUE TITLE
fastlane init

### ISSUE THREAD

**Issue by ts-cyl** [fastlane/fastlane#10699]
### New Issue Checklist

- [✅ ] Updated fastlane to the latest version
- [ ✅] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [✅ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [✅ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
```
cpe-172-100-107-58:near_merchant_ios chenyulong$ fastlane init
fastlane could not check for updates error: execution expired
[13:29:01]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[13:29:03]: Detected iOS/Mac project in current directory...
[13:29:03]: This setup will help you get up and running in no time.
[13:29:03]: fastlane will check what tools you're already using and set up
[13:29:03]: the tool automatically for you. Have fun! 
[13:29:03]: $ xcodebuild -list -workspace ./NearMerchant.xcworkspace
[13:29:05]: $ xcodebuild -showBuildSettings -workspace ./NearMerchant.xcworkspace -scheme NearMerchant
[13:29:08]: Your Apple ID (e.g. fastlane@krausefx.com): ts_cyl@163.com
[13:29:17]: Verifying that app is available on the Apple Developer Portal and iTunes Connect...
[13:29:17]: Starting login with user 'ts_cyl@163.com'
/Users/chenyulong/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:379:in `block in inflate_adapter': stack level too deep (SystemStackError)
	from /Users/chenyulong/.fastlane/bin/bundle/lib/ruby/2.2.0/net/protocol.rb:411:in `call_block'
	from /Users/chenyulong/.fastlane/bin/bundle/lib/ruby/2.2.0/net/protocol.rb:402:in `<<'
	from /Users/chenyulong/.fastlane/bin/bundle/lib/ruby/2.2.0/net/protocol.rb:102:in `read'
	from /Users/chenyulong/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:401:in `read'
	from /Users/chenyulong/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:290:in `block in read_body_0'
	from /Users/chenyulong/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:261:in `inflater'
	from /Users/chenyulong/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:280:in `read_body_0'
	from /Users/chenyulong/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http/response.rb:201:in `read_body'
	 ... 8723 levels...
	from /Users/chenyulong/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/chenyulong/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.62.1/bin/fastlane:20:in `<top (required)>'
	from /Users/chenyulong/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/chenyulong/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
cpe-172-100-107-58:near_merchant_ios chenyulong$
```
### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>

*generated on:* **2017-10-26**
</details>

**Comment by ts-cyl** [comment]
help me! thanks

**Comment by bomalley** [comment]
I'm seeing the exact same error. Anxious for guidance.

Thanks in advance!

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13                                       |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13 (17A405)                     |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>


*generated on:* **2017-10-26**
</details>

**Comment by ohayon** [comment]
Hey @bomalley - is this happening for you also when running `fastlane init`? 

We will definitely look into this issue, in the meantime, you can work around this by manually creating a Fastfile, let us know if you need any help making that happen! 🚀

**Comment by bomalley** [comment]
Yes @ohayon, it is during a `fastlane init`.

Thanks for the tip. I wasn't sure exactly what the `fastlane init` command did. If I can just create the fastlane file myself and get past the error, that's great to know.

**Comment by milch** [comment]
Can any of you try running `fastlane spaceship` to see if you run into the same error?

**Comment by SebastianThiebaud** [comment]
@milch Same error for me when running `fastlane init`.

Once running `fastlane spaceship`, I get 
```
[15:27:03]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Could not find gem 'pry'

If you installed spaceship using `sudo gem install spaceship` run
  sudo gem install pry
to install the missing gem

If you use a Gemfile add this to your Gemfile:
  gem 'pry'
and run `bundle install`
```
Not sure what I'm supposed to do here.

**Comment by milch** [comment]
@SebastianThiebaud Sorry, I forgot that you need `pry` for that. Can you install the `pry` gem and try running that again?

**Comment by SebastianThiebaud** [comment]
@milch I'm not really familiar with fastlane and ruby in general

```
$ sudo gem install pry
Password:
Sorry, try again.
Password:
Successfully installed pry-0.11.2
Parsing documentation for pry-0.11.2
Done installing documentation for pry after 2 seconds
1 gem installed
$ fastlane spaceship
[13:41:40]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Could not find gem 'pry'

If you installed spaceship using `sudo gem install spaceship` run
  sudo gem install pry
to install the missing gem

If you use a Gemfile add this to your Gemfile:
  gem 'pry'
and run `bundle install`
```

**Comment by HelloHolyLi** [comment]
I can not init too, I get stuck at :
Loading session from '/Users/xxx/.fastlane/spaceship/xxxx@gmail.com/cookie'

and after a long while, I get this error:

/Users/xxxx/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http/response.rb:382:in `block in inflate_adapter': stack level too deep (SystemStackError)  

from /Users/xxxx/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:429:in `call_block'
	from /Users/xxxx/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:420:in `<<'
	from /Users/xxxx/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:122:in `read'
	from /Users/xxxx/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http/response.rb:404:in `read'
	from /Users/xxxx/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http/response.rb:293:in `block in read_body_0'
	from /Users/xxxx/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http/response.rb:264:in `inflater'
	from /Users/xxxx/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http/response.rb:283:in `read_body_0'
	from /Users/xxxx/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http/response.rb:204:in `read_body'
	 ... 10908 levels...
	from /Users/xxxx/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `load'
	from /Users/xxxx/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `<main>'
	from /Users/xxxx/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/xxxx/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

here is my env:

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0.1                                       |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.62.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.4       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| openssl                   | 2.0.3        |
</details>


*generated on:* **2017-10-31**
</details>

Does any one have any idea about this?

**Comment by milch** [comment]
It's hard to see what the issue is since the stack trace gets truncated so early. Can one of you try putting this into a file (e.g. `test.rb`): 

```ruby
require 'fastlane'

begin
  Fastlane::CLIToolsDistributor.take_off
rescue => e
  puts e.backtrace
  raise
end
```

and then run it just like you would fastlane? i.e. if your fastlane command is `bundle exec fastlane init` run `bundle exec ruby test.rb init`. Seems like the stack trace will be 10k lines long, so don't post the whole thing, but maybe the last 20-30 lines

**Comment by mccarron** [comment]
I was having the same issue with a new Fastlane install, but after installing gems for pry and spaceship it crashes out a lot faster (no need to wait) with the following error: `uninitialized constant Spaceship::Client::InsufficientPermissions (NameError)`

I thought maybe it was due to that account not being an Admin, but I promoted it and still getting the problem.

Spaceship also works on it's own now with the same account. 
```
Logging into to iTunes Connect (@)...
Successfully logged in to iTunes Connect

Logging into the Developer Portal (@)...
Successfully logged in to the Developer Portal
```

Full error stack: 
```
/Users/xyz/.rvm/gems/ruby-2.4.1@cocoapods/gems/fastlane-2.64.0/fastlane/lib/fastlane/setup/setup_ios.rb:45:in `rescue in run': [!] uninitialized constant Spaceship::Client::InsufficientPermissions (NameError)
	from /Users/xyz/.rvm/gems/ruby-2.4.1@cocoapods/gems/fastlane-2.64.0/fastlane/lib/fastlane/setup/setup_ios.rb:30:in `run'
	from /Users/xyz/.rvm/gems/ruby-2.4.1@cocoapods/gems/fastlane-2.64.0/fastlane/lib/fastlane/setup/setup.rb:29:in `run'
	from /Users/xyz/.rvm/gems/ruby-2.4.1@cocoapods/gems/fastlane-2.64.0/fastlane/lib/fastlane/commands_generator.rb:122:in `block (2 levels) in run'
	from /Users/xyz/.rvm/gems/ruby-2.4.1@cocoapods/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/xyz/.rvm/gems/ruby-2.4.1@cocoapods/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/xyz/.rvm/gems/ruby-2.4.1@cocoapods/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/xyz/.rvm/gems/ruby-2.4.1@cocoapods/gems/fastlane-2.64.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/xyz/.rvm/gems/ruby-2.4.1@cocoapods/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/xyz/.rvm/gems/ruby-2.4.1@cocoapods/gems/fastlane-2.64.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/xyz/.rvm/gems/ruby-2.4.1@cocoapods/gems/fastlane-2.64.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/xyz/.rvm/gems/ruby-2.4.1@cocoapods/gems/fastlane-2.64.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/xyz/.rvm/gems/ruby-2.4.1@cocoapods/gems/fastlane-2.64.0/bin/fastlane:20:in `<top (required)>'
	from /Users/xyz/.rvm/gems/ruby-2.4.1@cocoapods/bin/fastlane:23:in `load'
	from /Users/xyz/.rvm/gems/ruby-2.4.1@cocoapods/bin/fastlane:23:in `<main>'
	from /Users/xyz/.rvm/gems/ruby-2.4.1@cocoapods/bin/ruby_executable_hooks:15:in `eval'
	from /Users/xyz/.rvm/gems/ruby-2.4.1@cocoapods/bin/ruby_executable_hooks:15:in `<main>'
```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                         |
| --------------------------- | --------------------------------------------- |
| OS                          | 10.13.1                                       |
| Ruby                        | 2.4.1                                         |
| Bundler?                    | true                                          |
| Git                         | git version 2.13.6 (Apple Git-96)             |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1@cocoapods/bin/fastlane |
| Host                        | Mac OS X 10.13.1 (17B48)                      |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                  |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                   |
| Is contained                | false                                         |
| Is homebrew                 | false                                         |
| Is installed via Fabric.app | false                                         |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/   |
| Xcode Version               | 9.1                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| fastlane            | 2.64.0  | ✅ Up-To-Date  |
| credentials_manager | 1.0.0   | ✅ Up-To-Date  |
| spaceship           | 1.0.0   | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.4       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.6        |
| minitest                  | 5.10.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.9        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| cocoapods                 | 1.3.1        |
| coderay                   | 1.1.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| commander-fastlane        | 4.4.5        |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.1        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.1        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| credentials_manager       | 1.0.0        |
| method_source             | 0.9.0        |
| pry                       | 0.11.2       |
</details>


*generated on:* **2017-11-10**
</details>

**Comment by BuXY** [comment]
Please take a look at [my solution](https://github.com/fastlane/fastlane/issues/8530#issuecomment-355533052).

**Comment by minuscorp** [comment]
Can we get this closed? I think that, as @BuXY pointed out, the issue was more a gem conflict (system Ruby vs other Ruby versions used). Feel free to open another issue linked to this one if the problem raises again.
