### ISSUE TITLE
Not option for take screenshots without launch android app

### ISSUE THREAD

**Issue by rahulmodu** [fastlane/fastlane#10830]
I have not found any option to take screenshots without launch app by using screengrab.If it is possible to take screenshots without launch app then please provide me command for that.

**Comment by joshdholtz** [comment]
@rahulmodu It is not possible. If you could please search through issues for similar questions before creating an issue that would be super appreciated 🙃 This has been asked in #1080, and #10831 by @rahul19393 and in #10817 (which was an issue you already created)

https://docs.fastlane.tools also has a lot of these answers for you that should get you an answer quicker instead of waiting for someone to reply via issues 😇 

Happy fastlaning 🚀
