### ISSUE TITLE
Spaceship not reading `itc_team_id` from `Appfile`

### ISSUE THREAD

**Issue by pablog** [fastlane/fastlane#10944]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm using `Spaceship` in a custom action, which returns the latest version uploaded to TestFlight:

(Why isn't there a default action for this as we have `latest_testflight_build_number`?)

```ruby
module Fastlane
  module Actions
    class LatestTestflightVersionAction < Action

      # Retrieves the latest version uploaded to ItunesConnect

      def self.run(params)
        Spaceship::Tunes.login

        # I'd like this to happen automatically.
        Spaceship::Tunes.client.team_id = CredentialsManager::AppfileConfig.try_fetch_value(:itc_team_id)

        app = Spaceship::Tunes::Application.find(params[:bundle_id])
        if app.nil?
          UI.abort_with_message! "The application is not yet created in iTunes Connect."
        end
        app.all_build_train_numbers.max
      end

      # Fastlane Action class required functions.

      def self.is_supported?(platform)
        true
      end

      def self.available_options
        [
          FastlaneCore::ConfigItem.new(key: :bundle_id, optional: false),
        ]
      end

    end
  end
end
```

The point is that I have to manually do:

```ruby
Spaceship::Tunes.client.team_id = CredentialsManager::AppfileConfig.try_fetch_value(:itc_team_id)
```

To provide the iTunes Connect team I want to be using.

### Environment

This is my `Appfile`:

```
# Your Apple email address. (ex: "some-email@wolox.com.ar")
apple_id "some-email@wolox.com.ar"

# Developer Portal Team ID. (ex: "RDFGA2FGMD")
team_id "XXXXXXXXXX"

# iTunes Connect Team ID. (ex: "18742801")
itc_team_id "YYYYYYY"
```

**I have no `.env.default`.**

My question is why I have to manually do that, and how can I provide the `itc_team_id` in `Appfile` for `Spaceship` to be able to read it.

If I don't do that, `Spaceship` would pick always the first team my user belongs to.

Thanks in advance.

**Comment by hjanuschka** [comment]
hey @pablog ✋ 

i think, it is because `spaceship` itself is not bound to the Appfile/Deliverfile/Whateverfile.
there is only 2 places in the code where `try_fetch_value` is used, `playground` and `spaceauth` - both some special edge-cases. (hope i am not wrong @KrauseFx )


so as in your PR https://github.com/Wolox/fastlane-mobile/pull/1 i think its correct to add the team selection code at that place.

> (Why isn't there a default action for this as we have latest_testflight_build_number?)
seems like you are one of the first ones you needs that feature?


according to the action guide https://docs.fastlane.tools/plugins/create-plugin/#submitting-the-action-to-the-fastlane-main-repo  - i'd suggest that you package up your custom action into a plugin and maybe if the plugin is used alot it will be integrated into core.
