### ISSUE TITLE
Localization DSL

### ISSUE THREAD

**Issue by michaelhenry** [fastlane/fastlane#11020]
Hi guys, I have question, I created an action for my opensource project , https://github.com/michaelhenry/Localizr a DSL the manages localization. Is it possible to still submit a new action here? or if not, is there any way to install where we can pull  an action from different sources  asside from making it as a git-submodule. 
Thank you!

Cheers,
Michael

**Comment by janpio** [comment]
That sounds like a pretty good candidate for a fastlane plugin!

That way the actual logic could be implemented and tested without any commitment needed from the core contributors, and if it turns out to be super popular and used very often it can still be integrated to the core pem action.

You can read more about creating a plugin here: https://docs.fastlane.tools/plugins/create-plugin/

**Comment by michaelhenry** [comment]
@janpio Oh thanks for the advice 👍
