### ISSUE TITLE
Different framit output for iPhone X only

### ISSUE THREAD

**Issue by IchHabRecht** [fastlane/fastlane#11160]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Running frameit on previously created screenshots gives me different output for iPhone X only. In portrait the whole iPhone is integrated into the frame, not cropped as all other screens (iPhone and iPad). I attached two framed screenshots to show the differences. Both were created with the same call of frameit.
![iphone x-01 list pink finite 01 portrait_framed](https://user-images.githubusercontent.com/1453345/33794783-fdb02ebc-dcd2-11e7-82f7-0056d37a62c6.png)
![iphone se-01 list pink finite 01 portrait_framed](https://user-images.githubusercontent.com/1453345/33794788-07f9d71a-dcd3-11e7-8816-b8632ac6dc3a.png)

**Comment by mouhcine** [comment]
I'm having the same issue

**Comment by Katorias** [comment]
Also experiencing the same issue, any workarounds?

**Comment by janpio** [comment]
Interesting. @funnel20 knows quite a bit about that code, maybe they can help.

**Comment by Katorias** [comment]
That would be awesome, looking to use this on our CI server, but the funny looking iPhone X screenshots are preventing us from doing so.

**Comment by funnel20** [comment]
My first guess: this is related to parameter `show_complete_frame`.
The difference between the 2 screenshots in the original issue is that 
the iPhone SE screenshot is created with parameter `show_complete_frame` enabled. And iPhone X not.
But I assume the value in your Framefile.json is equal for all devices and set to `true`.

If this is the case, the issue is that iPhone X doesn't respect the value for `show_complete_frame`.

**Comment by IchHabRecht** [comment]
Hi @funnel20,

Thank you for your input. Just for clarification, both screenshots were framed in the same run with the same options.

**Comment by funnel20** [comment]
Thanks @IchHabRecht , that confirms my thought. So ich habe Recht too :-)

**Comment by Katorias** [comment]
@funnel20 Your assumptions we're correct, the values in Framefile.json we're equal for all devices and show_complete_frame was set to false and all devices we're framed in the same call to frameit. The same issue was also mentioned here #10805

**Comment by funnel20** [comment]
**Background before iPhone X**
Consider the iPhone SE in this example with:

- `show_complete_frame` = `true`
- `padding` = 0

![iphone se-01_remotetab_framed](https://user-images.githubusercontent.com/2139844/38078791-af965dde-333d-11e8-8fc9-8b1f0aae00e5.png)

The device screenshot (green area) has a specific aspect ratio. For iPhone SE this is 1136/640 = 1.78.
The device frame (red dotted box) has a **different** aspect ratio, because the bezels on top and bottom are wider than on the side edges. Measured on this image this is 1072/512 = 2.09.

This means that when positioning the device frame in the image with original aspect ratio (because this is required by App Store), automatically side padding occurs. Although is was specified at 0.

To prevent that the framed screenshot becomes too narrow and optimally use the side edges of the image, the parameter `show_complete_frame` was introduced. This will force to maintain the side padding at the cost of the height of the framed device, by cutting down the bottom frame.
When setting `show_complete_frame` to `false`, the requested padding of 0 is fulfilled at the left and right sides:

![iphone se-01_remotetab_framed](https://user-images.githubusercontent.com/2139844/38079451-35e633d6-333f-11e8-8b6c-651200ece35c.png)

**And then there was iPhone X**
Without top and bottom bezels. Same analysis for aspect ratio:
- screenshot aspect ratio: 2436/1125 = 2.17
- frame aspect ratio: 2255/1119 = 2.02

And here is the 'root cause' of the observed behaviour:
The framed aspect ratio is **smaller** than the original screenshot ratio.

This means the exact opposite of earlier iPhones; when resizing the framed device, no side padding occurs, but top and bottom padding. This is perfectly indicated in this image, where indeed the side padding is 0, but at the bottom padding is introduced:

![iphone x-01_remotetab_framed](https://user-images.githubusercontent.com/2139844/38079530-6c348d3e-333f-11e8-864a-f4192d1714bc.png)

**Conclusions**

- Parameter `show_complete_frame` was introduced to optimally use the full width of the image by respecting the side padding at a cost of cutting down the bottom bezel.
- Because iPhone X has no top and bottom bezels, it will always respect the side padding, without cutting down bezels.
- So there is no frameit issue with `show_complete_frame` for iPhone X. This parameter is just not applicable for it, because the problem that it solves is simply not there.

**Comment by funnel20** [comment]
Yes, by why would users expect or desire that the iPhone X frame will be cut down? If it fits within the image borders, it fits.

**Comment by janpio** [comment]
> Why would users expect or desire that the iPhone X frame will be cut down? If it fits within the image borders, it fits.

Because they are obvisouly using `show_complete_frame = false` as `hide lower part of device so it looks a specific way = true`.

**Comment by funnel20** [comment]
They can also use `show_complete_frame = false` as:
`make the framed device as wide as possible and accept the consequence that the lower part of the device is clipped`.

Based on the implementation this is the intended purpose from the _frameit_ author.

With the introduction of iPhone X this purpose has no meaning anymore as clipping doesn't occur due to the new aspect ratio. Hence values `true` and `false` provide the same result.

The existing documentation suggest that hang over "can occur":

> The `show_complete_frame` value specifies whether _frameit_ should shrink the device and frame so that they show in full in the framed screenshot. If it is false, then they can hang over the bottom of the screenshot.

My suggested docu in PR #11662 improves this by using "clipping might occur":

> Specifies whether _frameit_ should shrink the device frame so that it is completely shown in the framed screenshot. If it is false, clipping of the device frame might occur at the bottom (when `title_below_image` is `false`) or top (when `title_below_image` is `true`) of the framed screenshot.

**The question** 
Is there a user desire to clip the complete iPhone X frame?

If so, how many pixels? 
Only (part of) the bezel, or even part of the framed screenshot?

**Comment by IchHabRecht** [comment]
Hi @funnel20 and @janpio,

Thanks for your information so far. Just for the record (as I'm the issue owner). As an user I would expect to get same screenshots for each device. For me it's the same if I have to use `show_complete_frame` or any other (new) setting. But I really like to be able to produce framed screenshots without the whole device shown. For now IHMO `show_complete_frame=false` is/was the way to get to this result. I would understand to introduce a new option but I really like to be able to get the described screenshots.

**Comment by funnel20** [comment]
`show_complete_frame` does still what it does, also for iPhone X.
Only the effect will be shown when the 'lacking' space of the bezels is filled with text.
Here is an example with padding = 10 and multi-line text.

`show_complete_frame` = false:
![iphone x-01_remotetab_framed](https://user-images.githubusercontent.com/2139844/38136339-094449a0-341e-11e8-9db5-3c385ff9140f.png)

`show_complete_frame` = true:
![iphone x-01_remotetab_framed](https://user-images.githubusercontent.com/2139844/38136348-10b0c088-341e-11e8-9148-dd46349f167e.png)

**Comment by funnel20** [comment]
The implementation of `show_complete_frame` is all based on padding. Either respect vertical top and bottom padding (`true`) or sacrifice top/bottom padding and respect side padding (false).
As we now learned, the latter might not always occur at iPhone X, because it has more free vertical space due to the lack of bezels.

**Solution**
Users demand a clipped iPhone X when `show_complete_frame` = `false`.
There are multiple ways 2 accomplish this.

**Comment by funnel20** [comment]
@janpio can you ask the team how they feel about this?
If this is the desired behaviour for `show_complete_frame` or that we have to create a new parameter?

**Comment by Katorias** [comment]
@funnel20  I'd really love to see that as a parameter if it's possible, though I admit it does seem difficult to integrate with the current functionality of `show_complete_frame`. If it is possible and it's something the team is willing to implement, I like your idea of distributing the orange space between the yellow and pink areas equally, it makes the most sense.

**Comment by janpio** [comment]
> can you ask the team how they feel about this?

There is no "team" to ask on this, we can just create a new issue with a feature proposal and see what responses trickle in from the community (and maybe some people that are on the team list).

To recap:
So obviously some users would like to have a way to consistently get this style of end result (screenshot in device frame, result shown a bit hidden on the lower end). As `show_complete_frame` does exactly what it should do, make sure the complete frame is seen if set to `true`, I think it would only make sense to add a new option - right? 

So the way to go would really be a new issue, that details what it should to, what it could be called etc.

**Comment by funnel20** [comment]
As an addendum to your recap: `show_complete_frame` is NOT doing for iPhone X what users expect when set to `false`.

So I would prefer to not add a new parameter, but just implement my suggestion from above for `show_complete_frame = false` (as confirmed by @Katorias):
For iPhoneX, move the frame down until the bottom bezel is cut off, while evenly distributing the text(s) above.
And something opposite in case `title_below_image` is `true`.

**Comment by matiasvillaverde** [comment]
Still have the same issue, is not possible to set the iPhone X at the same level as the rest of the devices.

**Comment by IchHabRecht** [comment]
This is still not resolved yet.

**Comment by funnel20** [comment]
@IchHabRecht The discussion shows there is no straightforward solution. In my comments I also asked for input, which you didn't provide. In order to work towards a solution that covers your needs, it would be great if you can participate.

**Comment by dermaaarkus** [comment]
I just want to add that I would love to see it too, because our marketing workers requires us developers to make the iPhone X screenshot "cutted" like all other. So we cant use frameit for this requirements right now 😢

**Comment by dermaaarkus** [comment]
@funnel20 actually I dont get the point where you ask for input. In my opinion your suggestion using the `show_complete_frame` flag is the one I prefer too :)

**Comment by funnel20** [comment]
@janpio Is it possible to re-open this issue?

**Comment by funnel20** [comment]
@dermaaarkus Since the issue is closed, I can't link to previous comments anymore.
But these are the questions, below the large screenshot with the orange square at the bottom:

The main question from my previous comment is still pending:
**How much pixels do you want to cut down from the frame?**

The second question is:
**How do you want the vertical orange offset that is clipped below, add to the yellow and/or pink area?**
I think it's preferred to increase yellow and pink equal, so the text is vertically aligned between the image top and frame top.

**Comment by dermaaarkus** [comment]
Ok thanks. I can just answer how I like it:

1. the orange line (the frame itself), so 0 pixels would be good. So the user can see the notch which is like a branding for the iPhone X. The green line would be my second choice.

![frameit](https://user-images.githubusercontent.com/7196958/42503712-b1c54500-8439-11e8-9d93-0f73abbb7783.png)

2. I prefer an equal distribution for yellow and pink, too

**Comment by funnel20** [comment]
As far as I know the notch is the top area with the camera, probably you mean just the Home slider, between your green and orange lines.
But I get your point and I agree that the orange line is preferred, so still the round display corners are visible, which are also typical for iPhone X.

One side-effect of this choice will be that the frameit code will require hard-coded offsets per device to facilitate this. Especially when Apple will release new devices with notch later this year.
Even for one device (like iPhone X) there may be different versions of the device frame over time, which can have a different vertical offset.
From a code perspective this requirement seems to be hard to maintain.
The current implementation is based on math; when the frame doesn't fit below the text, just slide it vertically outside the image area.

So I'm still not in favour of this request.

**Comment by dermaaarkus** [comment]
* Oops yes I meant the home button, thank you.
* I get your point about maintaining and can understand it
* Maybe there are more participants/opinions in this thread?
