### ISSUE TITLE
Rename `fastlane_version` to `min_fastlane_version`

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#11206]
`fastlane_version` ...

> [v]erifies the minimum fastlane version required

https://docs.fastlane.tools/actions/fastlane_version/

If you don't know anything about fastlane, you right now can misunderstand `fastlane_version "1.23.4"` to mean that your fastlane setup will use version 1.23.4, which is not true.

Example: https://github.com/fastlane/fastlane/issues/6006#issuecomment-245193151

Renaming the action would solve this problem.

TODO:
- Copy action to new naming
- Provide old naming as alias for backwards compatibility
- Change `Fastfile` template(s) to use new naming

**Comment by revolter** [comment]
Another problem I found with that is that it looked 100% like a variable, instead of a function/action that does something, so adding a verb would be great! Examples: `require_fastlane_version`, `require_min_fastlane_version`.

**Comment by jdee** [comment]
This could presumably be done using aliases, making the `fastlane_version` action an alias for `min_fastlane_version` the way `gym` is now an alias for `build_app`. Because I'm sure @mpirri needs something to do.

**Comment by milch** [comment]
I agree with @revolter, I think `require_fastlane_version` would make the most sense

**Comment by jdee** [comment]
That sounds reasonable. It's fairly trivial to change the names. I'll leave the PR as is until a consensus is reached.

**Comment by janpio** [comment]
`require_fastlane_version` has the exact same problem as only `fastlane_version` - it can be misunderstood to require that exact version.

If you want the `require` in there it would have to be `require_min_fastlane_version` or `require_fastlane_min_version`.

**Comment by milch** [comment]
Some more bike shedding: `min_fastlane_version_required` then?

**Comment by janpio** [comment]
`required` is probably better than `require` as it matches better to the "passive" nature of the already present installation of fastlane vs. the active act of "requiring" something right now.

(I personally would leave it off in my own code, but if majority agrees I don't object of course)

**Comment by jdee** [comment]
I guess one issue is the general disconnect when mobile app devs use a Ruby tool and aren't familiar with general dependency management using a Gemfile and the Bundler. It would be easy to think that something like this would work:

```Ruby
required_fastlane_version "~> 2.69"
```

I'm not sure there's anything morphological that can be done to avoid the idea that it's a variable assignment. And I doubt that actually matters. I think the reason @revolter got confused is he thought it was a general assignment mechanism and could do things like `x 5` instead of `x = 5`. I understand the thought process, but I wonder if that's a major concern for new users. Maybe others have had the same misunderstanding. There are also other actions that might be misinterpreted that way, such as `team_id`. The most important thing is probably to document the syntax to use and the exact meaning of what each action does, preferably with minimal reference to the docs. Hence a better action name is probably a good idea. But I doubt there's a quick code fix that will address the general issue of using Ruby with Fastlane.

**Comment by revolter** [comment]
Well, we could replace it with `min_fastlane_version("1.101.0")` to avoid confusions for people not accustomed to ruby.

**Comment by janpio** [comment]
That might actually be a great idea. 

Looking at the rest of the `Fastfile` you have either just "keywords" (action names without params), "function calls" (actions with params) or the usual variable asignments with `=`.

**Comment by revolter** [comment]
The "problem" would be that the fastlane's codebase uses function calling without parentheses.

**Comment by janpio** [comment]
But isn't this an action?
https://docs.fastlane.tools/actions/fastlane_version/

**Comment by revolter** [comment]
Yes, it is.

**Comment by janpio** [comment]
Beautifully implemented by @jdee 🥇 💯 
https://github.com/fastlane/fastlane/pull/11209/files
