### ISSUE TITLE
feature request: include Pluginfile for `import_from_git`

### ISSUE THREAD

**Issue by liaogz82** [fastlane/fastlane#11200]
This is a feature request from me.

I am unifying multiple iOS project Fastfile and they are using some common fastlane plugins. Right now `import_from_git` just pull Fastfile and actions folder from external git. Would be good if it includes `Pluginfile` too

### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]

### Environment

[INSERT OUTPUT HERE]

**Comment by basvankuijck** [comment]
Yeah this would be great. 
Some of the actions in 'our' fastlane repository we import using `import_from_git` have other gem requirements (nokogiri for instance).
The only way not to fail during fastlane initialization because of a missing gem, is to add `gem "nokogiri"` to every project's `Gemfile`.

Which is a bit of a hassle if we create a new action which needs another not yet specified gem, then we have to go over all of the projects and add it to their Gemfile. Quite time consuming.
So it would be great if we could just add a `Pluginfile` to the fastlane repository.

Currently I created a build script which is pulled from an external repository that (temporarily) appends missing gems to the Gemfile and reverts it after fastlane ran, but that's a bit of a nasty workaround
