### ISSUE TITLE
Support  APNs Auth Key in pem. (reopen)

### ISSUE THREAD

**Issue by punksta** [fastlane/fastlane#11221]
reopen https://github.com/fastlane/fastlane/issues/7848

Some of third party services like [Firebase](https://firebase.google.com/docs/cloud-messaging/ios/certs) and [https://support.clevertap.com/](https://support.clevertap.com/docs/ios/creating-an-apns-auth-key-for-sending-push-notifications.html)  recommends use auth key, not certificates. 

Maybe it's time to add it to fastlane?

thanks!

**Comment by zarcode** [comment]
+1

**Comment by janpio** [comment]
Thanks for this feature request for `pem`.

You could help us - or any other contributor that wants to work on this - by providing all necessary documentation to understand what exactly it is you want to have implemented. If you also already have an idea _how_ it could be implemented in fastlane (as in how one would use it, the API of the actions, parameters etc), please post this as well. 

Each of these steps make it easier for someone to code it up and thereby increases the probability of implementation. Thanks you.

**Comment by nubek** [comment]
hello @janpio,

I thing @punksta want to have a simple fastlane pem (or sign) function to generate a **APNs Auth Key** as described here (between _"Create a new Auth Key by clicking ..."_ and _"Locate and copy your Team ID - ..."_): https://developer.clevertap.com/docs/how-to-create-an-ios-apns-auth-key

Actually a function like this would be very useful, because the APNs Auth Key is used a lot now in different notification tools, like FCM. Then you would be able to use it automised like other fastlane tools and don't have to do this in the developer portal ;)

**Comment by nubek** [comment]
me too :D 👍

**Comment by nubek** [comment]
hey @janpio, some reply would be nice!

**Comment by joshdholtz** [comment]
TBH, I had no idea what an APNS Auth key was 🙃 But this sounds like a thing that we should have. I will add this to my list of things to look into 💪

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zapjonny** [comment]
BTW I think the point of APNS auth keys is that they do not time out after a year. Which means this is something you do once (per development program!) and then almost never again. There is likely hardly a need to automate it and thus probably no need to support in fastlane. Then again i do not have a lot of experience with the apns keys so I might not be 100% accurate.

**Comment by JimHowell20** [comment]
+1 this would be nice to have for people that make lots of different apps.
