### ISSUE TITLE
Can fast lane support multi-branch feature upload to TestFlight?

### ISSUE THREAD

**Issue by jacobjiangwei** [fastlane/fastlane#11231]
The initial request was:

Big team develop multi feature in different groups, they all want to put their feature in TF to get tested.

But just build number was not enough to tell the differences.

Is there a way to make TF easy to identify different branch's builds?
If yes, how to do that with fast lane?

**Comment by taquitos** [comment]
It seems like all you have to work with is version number in iTunes Connect. In that case, I might use team-assigned build versioning.
Imagine a chat app with 3 teams:
"Messages Team" uses: version 1.0.0 to 1.0.1000
"Contacts Team" uses: version 1.0.1001 to 1.0.2000
"Stickers Team" uses: version 1.0.2001 to 1.0.3000

While not ideal (since it kinda ignores semantic versioning), it still provides multiple build trains and each team can use `increment_version_number`
