### ISSUE TITLE
Use one Apple Developer auth session for entire `fastlane match` session

### ISSUE THREAD

**Issue by ethansinjin** [fastlane/fastlane#11525]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When using `fastlane match` (optionally with --force-for-new-devices) on a project that has multiple targets, one login per target occurs on iTunes Connect. This can easily result in rate limiting by iTunes Connect (see "Complete output" section)
If you get rate-limited in the middle of one iteration (I.e. after regenerating some but not all of the provisioning profiles), future runs of match with the same arguments will fail. The only ways to recover from this scenario are:

- Run `fastlane nuke` and then start from scratch
- Manually edit the signing repository to remove provisioning profiles that weren't regenerated, and then re-run once rate limiting ends (usually 15 minutes later)

It would be ideal if `fastlane match` logged in once and used the active session for each target. As is, regenerating provisioning profiles for both `development` and `adhoc` is a surefire way to get locked out of `developer.apple.com` if your project has multiple targets.

##### Complete output when running fastlane, including the stack trace and command used

```
bundle exec fastlane match development --force-for-new-devices

[14:28:23]: Cloning remote git repo...
[14:28:23]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[14:28:26]: 🔓  Successfully decrypted certificates repo
[14:28:26]: Verifying that the certificate and profile are still valid on the Dev Portal...

(*Here is where it installs the first n profiles, regenerating from Apple when necessary*)

Looking for related GitHub issues on fastlane/fastlane...

➡️  Action to inject a specific properties file to override one in an IPA?
    https://github.com/fastlane/fastlane/issues/503 [closed] 3 💬
    26 Sep 2016

➡️  iTunes account blocked/corrupted by fastlane sigh download
    https://github.com/fastlane/fastlane/issues/10793 [open] 71 💬
    5 days ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
	<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>Shield</center>
</body>
</html>
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.13.2                                          |
| Ruby                        | 2.5.0                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.14.3 (Apple Git-98)                |
| Installation Source         | /usr/local/var/rbenv/versions/2.5.0/bin/fastlane |
| Host                        | Mac OS X 10.13.2 (17C205)                        |
| Ruby Lib Dir                | /usr/local/var/rbenv/versions/2.5.0/lib          |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                       |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Library/Developer/CommandLineTools/             |
| Xcode Version               |                                                  |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.75.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-badge | 1.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.1       |
| CFPropertyList            | 2.3.6        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.1        |
| minitest                  | 5.11.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.4        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| curb                      | 0.9.4        |
| fastimage                 | 2.1.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| dotenv                    | 2.2.1        |
| excon                     | 0.60.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| gh_inspector              | 1.0.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.0       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.7.0        |
| word_wrap                 | 1.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| badge                     | 0.8.7        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| cocoapods                 | 1.3.1        |
| fastlane-plugin-badge     | 1.0.0        |
</details>

*generated on:* **2018-01-10**
</details>

**Comment by RishabhTayal** [comment]
I am seeing the same issue.

**Comment by deepumukundan** [comment]
Same here. This has been a recurring issue in the past as well.

**Comment by craigajohnson** [comment]
The rate limiting is destroying us. It is increasingly difficult to get all the way through a single build process for a single app given the number of Fastlane operations involved.

Does anyone know of official guidance from Apple on their new rate limiting policy?

This is destructive to CI systems and for what?

**Comment by taquitos** [comment]
So, we have aggressive session caching:
https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/client.rb#L369-L403

But for some reason that is failing for you, can you run fastlane with `--verbose`? 
We should be seeing `Loading session from '#{persistent_cookie_path}`

Which comes from:
https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/client.rb#L280-L291

**Comment by deepumukundan** [comment]
The only workaround (that too not foolproof) we do currently is to switch to a VPN after an operation like `match nuke`, and then run the profile re-generation separately (with the new IP address) so we don't run into this issue much. Works some times, not always

**Comment by taquitos** [comment]
@craigajohnson please append the entire output from `--verbose`

**Comment by craigajohnson** [comment]
BuildMAC3:~ buildadminmac$ fastlane sigh download_all --verbose -u****************
[✔] 🚀
[16:39:53]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:39:53]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
INFO [2018-01-18 16:39:53.98]: Starting login with user '*****************'
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Password (for ********************): **********
security: SecKeychainAddInternetPassword <NULL>: User interaction is not allowed.
Could not store password in keychain
Loading session from '/Users/buildadminmac/.fastlane/spaceship/****************/cookie'

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
        <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>Shield</center>
</body>
</html>


URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09%3Chtml%3E%0D%0A%3Chead%3E%3Ctitle%3E503%20Service%20Temporarily%20Unavailable%3C/title%3E%3C/head%3E%0D%0A%3Cbody%20bgcolor=%22white%22%3E%0D%0A%3Ccenter%3E%3Ch1%3E503%20Service%20Temporarily%20Unavailable%3C/h1%3E%3C/center%3E%0D%0A%3Chr%3E%3Ccenter%3EShield%3C/center%3E%0D%0A%3C/body%3E%0D%0A%3C/html%3E%0D%0A%0A+repo:fastlane/fastlane
➡️  Action to inject a specific properties file to override one in an IPA?
    https://github.com/fastlane/fastlane/issues/503 [closed] 3 💬
    26 Sep 2016

➡️  Use one Apple Developer auth session for entire `fastlane match` session
    https://github.com/fastlane/fastlane/issues/11525 [open] 8 💬
    31 minutes ago

➡️  iTunes account blocked/corrupted by fastlane sigh download
    https://github.com/fastlane/fastlane/issues/10793 [open] 74 💬
    2 days ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
ERROR [2018-01-18 16:40:05.13]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/spaceship/lib/spaceship/client.rb:466:in `send_shared_login_request': [!] The request could not be completed because: (Spaceship::Tunes::Error)
        <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>Shield</center>
</body>
</html>


        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/spaceship/lib/spaceship/portal/portal_client.rb:27:in `send_login_request'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/spaceship/lib/spaceship/client.rb:650:in `do_login'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/spaceship/lib/spaceship/client.rb:355:in `login'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/spaceship/lib/spaceship/client.rb:71:in `login'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/spaceship/lib/spaceship/portal/spaceship.rb:95:in `login'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/sigh/lib/sigh/download_all.rb:11:in `download_all'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/sigh/lib/sigh/manager.rb:35:in `download_all'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/sigh/lib/sigh/commands_generator.rb:82:in `block (2 levels) in run'
        from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
        from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
        from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
        from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/sigh/lib/sigh/commands_generator.rb:138:in `run'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/sigh/lib/sigh/commands_generator.rb:16:in `start'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/fastlane/lib/fastlane/cli_tools_distributor.rb:90:in `take_off'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.77.1/bin/fastlane:20:in `<top (required)>'
        from /usr/local/bin/fastlane:22:in `load'
        from /usr/local/bin/fastlane:22:in `<main>'
BuildMAC3:~ buildadminmac$

**Comment by craigajohnson** [comment]
Yes. We do however switch around sometimes depending on which arbitrary build we are running (individual developer accounts per app). Should we force deletion of the cookie if we know we are running for a different account?

**Comment by taquitos** [comment]
Each account should have a cookie in that path: ` /Users/buildadminmac/.fastlane/spaceship/`, so that shouldn't be a problem
I think we'll need more logging to understand they the cookie isn't currently valid.

**Comment by ethansinjin** [comment]
This is still an issue on the latest `fastlane`

**Comment by jeremyspatrick** [comment]
fastlane-bot want's to close this but ignoring it will not make it go away. This should be a higher priority.

**Comment by joshdholtz** [comment]
Heyyy, I will look into! How many provisioning profiles are you attempting to do? Just want to make sure that I am setting up the same kind of environment as you 😊

**Comment by ethansinjin** [comment]
My current environment has 9 provisioning profiles:

- App
- Today widget
- Messages extension
- Push Notification Content extension
- Intents extension (siri)
- Intents UI extension (siri)
- Watch
- Watch extension
- Watch Intents extension (siri)

**Comment by RishabhTayal** [comment]
Any updates on this one? I have been seeing this more than often now.

**Comment by LeeroyDing** [comment]
Bot is really helpful by actively ignoring outstanding issues

**Comment by LeeroyDing** [comment]
Am I the only one thinking this is still an issue?

**Comment by yfedin** [comment]
No - you're not the only one. My build jobs fail continuously due to "Could not login to iTunes Connect" and "503 Service Temporarily Unavailable" issues. 

I am on the latest fastlane version (2.98.0). I am using SPACESHIP_COOKIE_PATH pointing to a folder shared between CI nodes. Even when there is a valid cookie (successfully generated minutes ago) - "bundle exec fastlane spaceauth" starts failing shortly (within minutes). It seems so that it is failing to use existing session and re-authenticates against ITC, causing the account to be locked again and again. I've been using plain account without 2FA by now. I tried enabling 2FA hoping it could help, but it didn't.

When I don't run spaceauth - I get 503 message :(

Not even sure what yet to try...

**Comment by joshdholtz** [comment]
@yfedin This **may** be fixed in `2.99.0` for you? https://github.com/fastlane/fastlane/pull/12783

**Comment by yfedin** [comment]
Yes - just saw it, updated and giving it a try... Thanks @joshdholtz ! Will let know shortly if it worked...

**Comment by yfedin** [comment]
So far so good - couple dozen builds ran smoothly by now. Thanks a lot!!!
