### ISSUE TITLE
Snapshot takes screenshots only in English

### ISSUE THREAD

**Issue by alper** [fastlane/fastlane#11736]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I have this as my setup but still al the screenshots produced are in English:

```
  override func setUp() {
    let app = XCUIApplication()
    setupSnapshot(app)

    app.launchArguments = [LaunchArgument.resetData.string]
    app.launch()
  }
```

### Environment

<details>

<summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.16.1                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><pre>

# A list of devices you want to take the screenshots from
 devices([
   "iPhone 7",
   "iPhone SE",
   "iPhone X"
 ])

languages([
  "en",
  "de",
])

erase_simulator
reinstall_app
# concurrent_simulators

workspace "./Bla.xcworkspace"
scheme "Bla Staging"
configuration "Staging"

xcargs "-only-testing:'UI Tests/ScreenshotTests'"

output_directory "./fastlane/screenshots"

</pre></details>

**Comment by taquitos** [comment]
Could you try `de-DE` instead of just `de`? I think you need that `DE` region designator

**Comment by Srvictorlucas** [comment]
I'm having the same issue, whenever i run `fastlane snapshot` my html file all show all my screenshots for English, even showing all languages that I've set on snapfile `
languages([
  	"en",
       "de-DE",
       "fr-FR",
       "ja",
       "zh-Hans",
       "ko",
       "pt-BR",
       "pt-PT"
])`. Also, when i change device's language it also change all screenshots for that language. It's like I needed to change manually every language whenever I want to run fastlane's snapshot. Maybe I'm missing some configuration.

**Comment by KMGoDaddy** [comment]
Same issue - gonna be spending the weekend manually generating 92 screens. Hoping it's just iPhoneX that has become mandatory since last app submission. :(

**Comment by ReDetection** [comment]
@alper Can you please add `[Regression]` mark in the title? 

Did anyone had a chance to discover if this issue was introduced in some particular fastlane version or maybe SnapshotHelper.swift? 

I also experience this on Sierra 
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.6 (16G1212)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode9.2.app/Contents/Developer/                 |
| Xcode Version               | 9.2                                                            |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.80.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.10.1       |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| addressable               | 2.5.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| libxml-ruby               | 2.6.0        |
| faraday                   | 0.13.1       |
</details>


*generated on:* **2018-02-09**
</details>

**Comment by janpio** [comment]
So this worked before for you?

**Comment by ReDetection** [comment]
Yea, I make about 250 screenshots every month with single command, this tool saves hours. I'm trying to narrow problem, but had no luck yet

**Comment by janpio** [comment]
I added `[Regression]` to the title so this gets more eyeballs.

Sharing your setup (`Fastfile` etc.) sure would help. Maybe even a minimal repro on a new app?

**Comment by ReDetection** [comment]
OK, I was able to find issue in my code: I was overwriting `launchArguments` which snapshot depends on, so my set up code was like this:
```
        setupSnapshot(app)
        app.launchArguments = ["--demo"]
        app.launch()
```
It's enough to change `=` to `+=` or swap first two lines to fix the issue.

I wrote [simple dummy](https://github.com/fastlane/fastlane/files/1715269/localization.zip) project to test localization – you can use it if you lazy to create your own ;)

**Comment by janpio** [comment]
(Removed the "Regression" label then)
