### ISSUE TITLE
Precheck for tvOS

### ISSUE THREAD

**Issue by fassko** [fastlane/fastlane#11756]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

**Precheck** for tvOS. Currently it only supports iOS platform

### Environment

Apple TV tvOS

**Comment by fassko** [comment]
Hi there, if someone from core team would like to help me I could try to implement this.

**Comment by KrauseFx** [comment]
Hey @fassko, thanks for submitting this issue, great idea. Unfortunately we decided to not officially support tvOS for now, due to the number of users for the tvOS platform, so we can't commit to spending time on it. However if you feel like it, feel free to dive into the fastlane code base, check out https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md on how to get started 👍
