### ISSUE TITLE
latest_testflight_build_number issue

### ISSUE THREAD

**Issue by ChristopherDrum** [fastlane/fastlane#1178]
On iTunes Connect I have an app at version 3.0.2
I have two builds uploaded as 
`3.0.2.0`
`3.0.2.1`

When I run latest_testflight_build_number(version: 3.0.2)
the response I get back is
```
Fetching the latest build number for version 3.0.2
[07:58:20]: Latest upload is build number: 3
[07:58:20]: FETCHED BUILD NUMBER: 3
```

I was expecting to receive a `1` back for a build number, or is my understanding of the 4th digit different than the community?

**Comment by nmccann** [comment]
Looking at the [code](https://github.com/fastlane/fastlane/blob/master/lib/fastlane/actions/latest_testflight_build_number.rb), the build number is converted to a string using [to_i](http://apidock.com/ruby/String/to_i) which parses the number to an integer. The expectation seems to be that build numbers will be integers rather than semver style versions. Is there a particular reason why you can't omit the semver portion of your build number and just use an integer sequence like `1, 2, 3, 4...` for your builds?

**Comment by KrauseFx** [comment]
Thanks for jumping in @nmccann. Should I update the action to support any kind of number format? Is there any reason why we shouldn't do it?

**Comment by ChristopherDrum** [comment]
@nmccann I think this came from an early misunderstanding of the build version format necessary for iTunes Connect. It was understood that it must follow the semver + build # format, but it seems that it incorrect. Switching to the single integer build number should be completely fine, to be honest. Thank you.

**Comment by ChristopherDrum** [comment]
@nmccann Here's why we didn't think we could use a single digit for our build number. Apple docs state:

"CFBundleVersion (String - iOS, OS X) specifies the build version number of the bundle, which identifies an iteration (released or unreleased) of the bundle. The build version number should be a string comprised of three non-negative, period-separated integers with the first integer being greater than zero. The string should only contain numeric (0-9) and period (.) characters. Leading zeros are truncated from each integer and will be ignored (that is, 1.02.3 is equivalent to 1.2.3)."

Now, this doesn't talk about 4-digit strings, but the "three non-negative, period-separated integers" is pretty explicit.

**Comment by ChristopherDrum** [comment]
@KrauseFx To your point, Apple's docs say the bundle version should follow a certain format which latest_testflight_build_number does not return. So it would make a lot of sense to me to update the action to align with the docs. Also, I think this type of x.x.x.x build number formatting is pretty common. At least, everyone on my team individually felt it was the correct way to set a build number, from past experience.

**Comment by devashish2203** [comment]
+1 to updating the action to support x.x.x.x format for build number

We have builds uploaded to test flight, latest being
version: 4.12.0
buildNumber: 4.12.0.6
the latest_testflight_build_number(versi

**Comment by tizaks** [comment]
I've just run into this issue as well - right now my TestFlight is like this:
Version 1.0 (Build 3)
Version 1 (Build 2)
Version 0.1 (Build 1)

TestFlight (correctly) considers the 1.0 Version to be the newest, but this is what happens when I run `latest_testflight_build_number`:
`Fetching the latest build number for version 1
Latest upload is build number: 2`

I know the way I did the versions is a bit confusing, but I believe this Action should align with TestFlight's handling of version ordering

**Comment by ohwutup** [comment]
Hi everyone! I am going to close this for now and I marked it as an enhancement. We should definitely do this and will update the issue as soon as we can pull it off! Thanks everyone! :octopus: :ocean:
