### ISSUE TITLE
update_info_plist fails when plist file extension is different

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#12088]
As of now the `update_info_plist` action will fail [here](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/update_info_plist.rb#L87) if the extension of the file passed in `plist_path`  parameter is anything other than '.plist'. I believe we should be able to support other file extensions as well for e.g. `.entitlements` since `.entitlements` is also a plist file.

I would be more than happy to open a PR to make this change.

**Comment by elitalon** [comment]
@RishabhTayal I don't know what the core team thinks about this, but the interface of the action assumes you're  actually editing an "Info.plist" file, rather than some generic `.plist` file. Allowing other extensions in the same action would change the semantics.

Maybe it makes sense to add some generic `update_plist` or an specific `update_entitlements` action. Which in turn could be used internally to refactor [update_app_group_identifiers](https://docs.fastlane.tools/actions/update_app_group_identifiers) and [update_icloud_container_identifiers](https://docs.fastlane.tools/actions/update_icloud_container_identifiers).

**Comment by RishabhTayal** [comment]
Closing in favor of https://github.com/fastlane/fastlane/issues/12188
