### ISSUE TITLE
[frameit] Possibility to make it without frames? just title and background under it?

### ISSUE THREAD

**Issue by Assisto** [fastlane/fastlane#12116]
Hi, thanks for fantastic tool.

Btw, is there any option to annotate scrennshots without iphone/ipad frames? 
Just original image (fullscreen), title and background under title?

thanks

**Comment by janpio** [comment]
I don't think so, as the real goal of `frameit` is to... frame screenshots ;)

But @funnel20 might know if there maybe is a workaround.

**Comment by funnel20** [comment]
With the current Framefile and options it's not possible.
The way frameit is implemented is that it sizes down the original screenshot and adds the device frame around it. As a result an empty space is created below or above the device frame. Because frameit knows the scale factor, it knows the exact position and dimension of the empty space. Hence it can use the correct font size to position the text within that space.

It would be complicated to postion text over a a full size screenshot, as it might conflict with the screenshot content.
And scaling it down without a device frame to make space for the text, would result in a visually unattractive screenshot.

**Comment by Assisto** [comment]
I see. Thanks for reply. ))

**Comment by funnel20** [comment]
@Assisto You're welcome.

I'm however a bit curious about your question.
Since the moment I experienced framed screenshots I never wanted to go back to those raw screenshots. Its gorgeous for both App Store and any publications/marketing.

The only wish for frameit I have for the future (and probably will make after approval of @janpio 😀) is to use frameit without text and a transparent background. So just frame the raw screenshot to make it visually appealing.
The reason: that's perfect for the app documentation or user manual.

**Comment by janpio** [comment]
Looking forward for the issue @funnel20 ;)

**Comment by Assisto** [comment]
Undoubtedly frameit - is fantastic timesaving tool. But in some cases, for example - games' screenshots, raw images are more common (https://itunes.apple.com/US/app/id1261357853?l=en https://itunes.apple.com/US/app/id1319618742?l=en)

**Comment by funnel20** [comment]
I see, that's a good one.
They added a solid background behind the text, so it won't conflict with the screenshot content.

**Comment by janpio** [comment]
"Problem" (again) is that `frameit` already does more than it was initially supposed to do: frame screenshots with devices. "Putting on a background" and "putting text on the background next to the framed screenshot" are not really what was the main task ;)

One could of course think about renaming `frameit` into `do_stuff_with_screenshots` and create these other things as individual methods - but _someone_ would have to code all that and invest all the time necessary for that.

**Comment by Assisto** [comment]
I have checked other possibilities, and, unfortunatelly, there is no alternatives to frameit. :) 
Will think how to implement such option in fork. ))
