### ISSUE TITLE
How I can capture the screenshots for multiple fragments and activities 

### ISSUE THREAD

**Issue by shailesh2208** [fastlane/fastlane#12122]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am confuse with the method(testTakeScreenshot()) define in test class, how we can use it if I want to move on multiple fragments and activities. I have use this method for testing purpose and I have found the blank screenshot that means screenshot was captured before the data load on the view.

Also I want to know the use of Espresso in fastlane.
  
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
         fastlane environment
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by joshdholtz** [comment]
@shailesh2208 You will need to script your tests to wait until your screen loads, take the screenshot, and then put in logic to simulate clicks or app navigations so that you can move to multiple screens. The docs show some examples of these.

Also, the `screen grab` documentation on https://docs.fastlane.tools/actions/screengrab/#screengrab has some info and example projects of Espresso 😊

**Comment by shailesh2208** [comment]
I have an issue, screenshots capture before the page load the UI, can we hadle it to wait the process untill the full UI is visible.
