### ISSUE TITLE
fastlane match creates lots of random private keys in keychain

### ISSUE THREAD

**Issue by elwerene** [fastlane/fastlane#12291]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm using fastlane match in a cd environment and had the issue, that builds decreased in speed over time (a lot, from 10 minutes in the beginning to over 3 hours in the end). I realized, that the process of putting a key into the keychain took a very long time. So I had a look in the keychain and found more than 1800 private keys with strange labels: 16 characters (A-Z0-9).

As "Keychain Access.app" was not able to select all the keys (it was constantly scrolling back down and crashed randomly) I wrote a little tool to delete all those keys: https://github.com/elwerene/keychain-cleaner

Maybe I did something wrong in my cd setup as I set up the build to put the signing key into the keychain for each build, sometimes multiple signing keys as some products needs a different signing key for the build and the release.

I can provide you with my Fastfiles if I've discovered an edge case here :)

**Comment by johnknapprs** [comment]
I've experienced the same thing.  Though it inconsistently happens across machines.  One build machine will get buried in these keys while others running the same job do not.  

I'll clear them out, then after awhile see it happen on another.  It's even happened on development machines.  Not sure what's going on but I think it might come from the match keychain password being passed to unlock.

**Comment by joshdholtz** [comment]
@elwerene This is really strange - I have never seen _match_ make that many private keys before 🤔 If you could share your `Fastfile` that would be great

**Comment by joshdholtz** [comment]
@elwerene Nothing really jumps out as odd here. Are you able to upload a screenshot of what those certs with strange labels? I'm curious as to what these certs look like that are being created

**Comment by joshdholtz** [comment]
@elwerene Ahh, I see! How many different teams are you making builds for? My key list about 20 long but it doesn't grow when I run `match` for a team that I already ran `match` for?

**Comment by elwerene** [comment]
I think it's a total of 5 Teams.

**Comment by joshdholtz** [comment]
@elwerene Something definitely seems fishy. I build stuff for 10ish teams and don't see the same issue at all. Are you nuking the `match` repo before every run? Nuking is the only way I could see where it would keep adding more keys

**Comment by elwerene** [comment]
Nope, no nuking.--------- Original Message ---------
From: Josh Holtz 
To: fastlane/fastlane 
Date: Fri Apr 20 15:08:34 GMT+02:00 2018
Subject: Re: [fastlane/fastlane] fastlane match creates lots of random private keys in keychain (#12291)

@elwerene Something definitely seems fishy. I build stuff for 10ish teams and don't see the same issue at all. Are you nuking the match repo before every run? Nuking is the only way I could see where it would keep adding more keys

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fastlane/fastlane","title":"fastlane/fastlane","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fastlane/fastlane"}},"updates":{"snippets":[{"icon":"PERSON","message":"@joshdholtz in #12291: @elwerene Something definitely seems fishy. I build stuff for 10ish teams and don't see the same issue at all. Are you nuking the `match` repo before every run? Nuking is the only way I could see where it would keep adding more keys"}],"action":{"name":"View Issue","url":"https://github.com/fastlane/fastlane/issues/12291#issuecomment-383090216"}}}

**Comment by joshdholtz** [comment]
@elwerene Huh.... I am not sure then what would be causing all of these keys to get created. I'm sure you've looked into this but is there anything else on this machine that could be causing this? Something not fastlane? I can't seem to replicate this or see how this could happen 😔

**Comment by caguilar187** [comment]
What happens if you run fastlane with `--verbose` on? In particular on the match calls? I was seeing this line `security: SecKeychainItemImport: User interaction is not allowed.` But it was just silently happening but the builds still worked so I never noticed it. I recently was trying to run the command that match uses under the hood `security set-key-partition-list -S apple-tool:,apple: -k '' /Users/boulderci/Library/Keychains/login.keychain-db` which was taking forever which is when I noticed I had 14,000 entries for private keys.

I cleaned them out last week and now I'm unlocking the keychain using the fastlane action and passing the keychain password in match, which got rid of that message. Currently I'm at 100 private keys created so not sure if it worked fully but I'm keeping an eye on it. We do have like 20 active iOS projects all of which use different teams.

**Comment by elwerene** [comment]
@joshdholtz I'm not entirely sure, because we use the same machine for Android Fastlane builds as well. But as far as I know, Android builds don't use the keychain. I'll update our continuous deployment task to include --verbose and will post an update once I find something suspicious!

**Comment by elwerene** [comment]
It took some time, I finally managed to get a verbose log: https://gist.github.com/elwerene/bf9211a06919db337cc8c37178fb617c

**Comment by caguilar187** [comment]
Your output looks the same as mine, sadly after checking in again on my machines after 2 weeks of running I have about 700 of those keys. It's the only thing that should be using the keychain on said machine at least on a continuous basis. There might be other things but those should be one offs. I'm going to be taking another stab at tracking down the source on my end.

**Comment by simonbuchan** [comment]
It's not due to being locked vs. unlocked. The output is a bit spammy to output here, but it's easy to reproduce (on my machine™️):

```
#!/bin/sh
set -ex
export MATCH_APP_IDENTIFIER=...
export MATCH_GIT_URL=...
export MATCH_KEYCHAIN_NAME=match.keychain
export MATCH_KEYCHAIN_PASSWORD=match

echo "====== RUNNING LOCKED ======"

security create-keychain -p "$MATCH_KEYCHAIN_PASSWORD" "$MATCH_KEYCHAIN_NAME"

bundle exec fastlane match --verbose --readonly
# Note second run prints two keys
bundle exec fastlane match --verbose --readonly

security delete-keychain "$MATCH_KEYCHAIN_NAME"

echo "====== RUNNING UNLOCKED ======"

security create-keychain -p "$MATCH_KEYCHAIN_PASSWORD" "$MATCH_KEYCHAIN_NAME"

security unlock-keychain -p "$MATCH_KEYCHAIN_PASSWORD" "$MATCH_KEYCHAIN_NAME"

bundle exec fastlane match --verbose --readonly
# Note second run *still* prints two keys
bundle exec fastlane match --verbose --readonly

security delete-keychain "$MATCH_KEYCHAIN_NAME"
```

At least using a throwaway keychain means the damage can be contained.

Interestingly the first imported key's label is "Imported Private Key", the second is a hash. Seems like the `security import` is missing some key id so it knows to override?

**Comment by simonbuchan** [comment]
You'll probably also need something like `security list-keychains -s match.keychain login.keychain`, still working out the details myself.

**Comment by simonbuchan** [comment]
Not sure if it's related, but [this line](https://github.com/fastlane/fastlane/blob/9d4248873590ad363c12f50bc6180d580675b289/fastlane_core/lib/fastlane_core/cert_checker.rb#L26) looks like it has bug where the certificate identities are not checked on the requested `--keychain_name`?

**Comment by simonbuchan** [comment]
Seems `security list-keychains -s match.keychain` and `security unlock-keychain -p match-password match.keychain` is enough for match to work with under CI with a custom keychain (which also means you don't have to have the build agent or project settings know the account login keychain password).

The other thing I ran into is that I have the CI running under a LaunchDaemon, not a LaunchAgent, and match will fail unless that had `SessionCreate` set to true in the daemon plist - as a wild guess that might be due to the hard-coded keychain for the WWDR certificate?
