### ISSUE TITLE
Version URL for hockeyapp build

### ISSUE THREAD

**Issue by adityakhatkhate** [fastlane/fastlane#12388]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

This is an enhancement request to the hockeyapp upload process. Currently, it allows to share the `public_url` for hockeyapp as the link once the build is uploaded. This url takes the user to the specific app but not to the specific version that was built. Can we provide an option for accessing the `config_url` that comes back in the response from hockeyapp after the upload of the build which points to the specific version. This can be added with something like - 

version_url = response.body['config_url']
Actions.lane_context[SharedValues::HOCKEY_VERSION_DOWNLOAD_LINK] = version_url

below the section here - https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/hockey.rb#L169

**Comment by adityakhatkhate-aofl** [comment]
As an alternate I was able to get the required value by using - 

`lane_context[SharedValues::HOCKEY_BUILD_INFORMATION])['config_url']`

However, I do think the `config_url` might be a more relevant value during a notification than the `public_url` since that ties a message uniquely to a particular version of the build.
