### ISSUE TITLE
Google Api Error: apkNoUpgradePaths: You cannot rollout this release because it does not allow any existing users to upgrade to the newly added APKs.

### ISSUE THREAD

**Issue by kelvincooll** [fastlane/fastlane#12473]
supply(
    skip_upload_apk: 'true'
       )
Hi,
I am trying to update screenshot without updating apk in playstore but getting this error. Above I have mentioned the fastlane code .For upgrading screenshot I dont know why it is showing apk error . Can you help me to solve this issue.

**Comment by joshdholtz** [comment]
@kelvincooll This is most likely due to using a lower version number than what is already released (so that users will never see this version that you just uploaded).

And if you would be able to use the issue templated provided from now on that would be a huge help ❤️  It helps by making sure all the proper steps were done so that we don't have duplicate issues and have all the information we need to help debug more 😊

**Comment by kelvincooll** [comment]
Am using the higher version number than released one but still facing this issue.  Thanks for your reply.

**Comment by Villar74** [comment]
got that error. In docker it doesn't working.

**Comment by Villar74** [comment]
problem was in versionCode. docker automatically created apk with wrong vC
