### ISSUE TITLE
[feature_request] ensure_git_status_clean to ensure branch is up-to-date

### ISSUE THREAD

**Issue by wugeorgeq** [fastlane/fastlane#12746]
### Feature Request
I want to add an action (or add a parameter to ensure_git_status_clean.rb, but seems less clean) so that I can check if local branch is up to date with remote.

#### Motivation Behind Feature
Prevents the case of distributing a build and realizing immediately that another PR was merged in that short time window.

#### Feature Description
Pretty simple, if the team thinks this is a good idea, I can make the PR :)

#### Alternatives or Workarounds
Right now I've created my own private function that does this, I think it would be helpful for the community

**Comment by wugeorgeq** [comment]
obviously the PR would look different but this is my code snippet for desired behavior
```private_lane :verifyCleanAndUpToDate do
    repo_status = Actions.sh("git status")
    repo_clean = repo_status.include?("up-to-date") && repo_status.include?("clean")
    if repo_clean
      UI.success('Git status is clean, all good! 💪')
    else
      UI.user_error!("Please commit changes and/or pull")
    end
  end```

**Comment by joshdholtz** [comment]
@wugeorgeq Thanks for using the feature request template 😊 ❤️ 

- I don't think they should be its own action within fastlane (we are trying to limit the amount of actions we merge in as it increases the amount of time for support/maintenance)
- I also don't think it necessary fits within the naming of `ensure_git_status_clean` since the proper way to check if its up to date with a remote is by running `git fetch --dry-run` (https://stackoverflow.com/a/7939193)
  - Checking based on strings `up-to-date` or `clean` feels like there could be some failures if a branch name contains those strings
  - Buuuuttttt... it may work within that action 🤔 

I'm kinda on the fence about including this. I _think_ this may fit better as a third party plugin right now unless this has a lot of requests / high demand.

Lemme know your thoughts or if you have any questions about my thoughts 🙃

**Comment by wugeorgeq** [comment]
Thanks for the correction! I'm out of the office today but will definitely look into the 3rd party route to see how it works and if the functionality exists (new to fast lane)

**Comment by joshdholtz** [comment]
@wugeorgeq Sounds good and welcome to fastlane! 😊 🚀 Docs are creating a plugin can be found here - https://docs.fastlane.tools/plugins/create-plugin/ 💪
