### ISSUE TITLE
Add options to generated readme 

### ISSUE THREAD

**Issue by adamvandenhovenfm** [fastlane/fastlane#12801]
#### Motivation Behind Feature

If you read [Advanced Fastlane](https://docs.fastlane.tools/advanced/#passing-parameters), you discover that you can pass parameters into Lanes. This is a great feature for more complex build/deploy situations when you're trying to fit into an existing build sequence, or you have a large number of effectively identical builds and want to reuse lanes. 

However, in the generated readme, [only the name of the lane is output](https://github.com/fastlane/fastlane/blob/e61fbe3cd5ee395cd792201bc7a7b835c6eac9cd/fastlane/lib/fastlane/documentation/docs_generator.rb#L83). It would be good if that example reflected the allowed options 

#### Feature Description

There are two approaches I can think of. 

One is to add `option` such that `option option_name, is_required, default` would then be used when generating the example. At some point it would also be possible to use this to add behaviour to the lane itself (by failing if required options are missing, setting defaults). 

The other approach is to add `ex` which is handled identically to `desc` (join multiple by new lines) except that it would be used in the example portion and the existing code would only be used if no `ex` existed.  

I'm not sure which one is best. The first seems to have more long term utility. 

#### Alternatives or Workarounds

The workaround is to simply extend the description (say with a heredoc or just many `desc` lines) to document these options.

**Comment by adamvandenhovenfm** [comment]
I'm not sure any of this is relevant to the ticket but...

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.5                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.2 (Apple Git-101.1)        |
| Installation Source         | ~/.rbenv/versions/2.4.2/bin/fastlane        |
| Host                        | Mac OS X 10.13.5 (17F77)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.2/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.98.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| tty-screen                | 0.6.4        |
| openssl                   | 2.0.5        |
| highline                  | 1.7.10       |
| io-console                | 0.4.6        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.2        |
| plist                     | 3.4.0        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.8        |
| faraday                   | 0.15.1       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.3        |
| json                      | 2.1.0        |
| unicode-display_width     | 1.3.2        |
</details>


*generated on:* **2018-06-27**
</details>

**Comment by johnknapprs** [comment]
If I'm not mistaken, the `desc` feature accepts markdown so you can definitely get creative with how data is loaded into it when generated. 

Personally, I migrated away from complex lane logic.  To me, a lane should be simple and straight forward.  Passing data between them only increases complexity. (That's why there's `lane_context`)

The way that I solved the documentation problem is two fold: 

1. Migrated all complex functionality to plugins (up to 82 Actions and 15 Helpers as of today)
2. Copied the Fastlane documentation generator into it's own utility that supports my plugin heavy architecture

Plugins have far more documentation and customization functionality than Lanes.  I can insert 2 descriptions, categories, platform restrictions, example code, default values, and most awesomely... I can execute them from the command line without a Fastfile.  

Hacking up the Fastlane doc generator to fit my projects, I was also able to generate markdown files for each custom plugin and have it save to my repository.  When someone pulls one of my codebases, they'll see the sparse Lane readme, but appended to the end is a markdown link to where all the plugin docs are stored.   

From my experience Fastlane has 2 main selling points.  1. API/Signing management with Apple.  2. A robust plugin framework.   Leverage #2 and you'll find that the plugin functionality will cover 90% of your needs.  (I'm also very interested to see how Apple's official api impacts Fastlane and its community seeing that it will make the functionality language agnostic).

Just my 2 cents.   I spent a long time trying to wrestle Lanes into how I wanted them to operate.  Once I took some time to re-architect my pipelines into a plugin first system, everything suddenly made sense.

**Comment by joshdholtz** [comment]
@adamvandenhovenfm Heyyyyy 👋 I totally understand this feature request because I created a similar issue about a few months back for this - #11824 

Do you want to move this discussion over there? I don't think this is a highly requested or highly used feature (which is why I haven't put this in yet) but it could provide some nice API / self-documentation level to users running your _fastlane_ setup

This isn't a super complicated feature to add but I doneed to balance if its worth the number of users that will be using this feature 🙃 (which is why I haven't pulled the trigger to do this yet)

## My lane description
In the meantime, I've been using lane descriptions like this...
```
desc "Bumps the version and build number on the project"
desc "The lane to run by developers"
desc "#### Example:"
desc "```\nfastlane ios bump version:2.0.1 build_number:23\n```"
desc "#### Options"
desc " * **`version`**: The version to set in the Info.plist (`CFBundleShortVersionString`)"
desc " * **`build_number`**: The build number to set in the Info.plist (`CFBundleVersion`)"
desc ""
lane :bump do
    # See previous slide for logic
end
```
