### ISSUE TITLE
certificate problem ( ARCHIVE FAILED )

### ISSUE THREAD

**Issue by baturorkun** [fastlane/fastlane#12975]
when i use crontab, i have a certificate problem because shell script cannot access keychain.
i don't want to use the keychain. 

fastlane cert    ---> download cer  file but i have an error and only one cer file (U7THXUPJPP.cer)
There is no P12 file.

[18:47:31]: Successfully logged in
[18:47:32]: Certificate BZA8E861GC (iOS Distribution) can't be found on your local computer
[18:47:33]: **Found the certificate U7THXUPJPP (iOS Distribution) which is installed on the local** machine. Using this one.
[18:47:34]: Verifying the certificate is properly installed locally...
[18:47:34]: Successfully installed certificate U7THXUPJPP

my fastfile code:

lane :beta do
    #cert
    sigh(force: true)
    build_ios_app(
      workspace: me.xcworkspace",
        scheme: "me"
    )
end

Result : ARCHIVE  FAILED
 === BUILD TARGET Connected2.me OF PROJECT Connected2.me WITH CONFIGURATION Release ===
[10:37:15]: ▸ Check dependencies
[10:37:15]: ▸ Code Signing Error: Provisioning profile "com.C2M.Connected2 AppStore" doesn't include signing certificate "iPhone Developer: Batur Orkun (3RRLYHLK78H)".
[10:37:15]: ▸ Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.4'

How to use local cer file or download cer file from itunes and use it?

**Comment by joshdholtz** [comment]
@baturorkun There isn't a way to not use a keychain in _cert_ currently. What you _could_ try to do use the `create_keychain` action with the `path` option (set as an absolute path) to create a keychain in the directory that your cron can access 🤔

**Comment by baturorkun** [comment]
himmm.. i tried it actually.  i created a new keychain. but i could not use them maybe because it did not work

**Comment by joshdholtz** [comment]
@baturorkun Creating a keychain wouldn't work in your job? Or setting the new keychain into `cert` didn't work?

**Comment by joshdholtz** [comment]
@baturorkun Huh, I would have thought that would have worked. TBH, I am not familiar with crontab so I don't know how much help I can be with this. Having access to the keychain is definitely needed to see if an existing cert is made (so that you don't blow through the maximum amount of distribution certs that are available on the dev portal).

But there _could_ be an argument made for adding an option to bypass all keychain related calls since keychain here is also stopping _cert_ from working on Windows but that complexity behind that to do that right is kinda high so there isn't a quick solution (from my end) that can help you out with this right now 😔

**Comment by baturorkun** [comment]
thanks :)
