### ISSUE TITLE
fastlane all action is not work! please help me!

### ISSUE THREAD

**Issue by FunnyFzl** [fastlane/fastlane#12991]
<img width="701" alt="2018-07-31 6 16 27" src="https://user-images.githubusercontent.com/15104149/43453925-01e7073e-94ee-11e8-98be-bbe26c5c124a.png">
<img width="583" alt="2018-07-31 9 42 32" src="https://user-images.githubusercontent.com/15104149/43463251-b3eefbe6-950a-11e8-9195-84773f390418.png">

**Comment by heartofagoof** [comment]
Looks like a file permission issue - is the user running the fastlane command and /Users/funny the same? What are the permissions on that folder?

**Comment by FunnyFzl** [comment]
@fastlane-bot  after "fastlane  env"——>
<img width="593" alt="2018-08-01 11 43 38" src="https://user-images.githubusercontent.com/15104149/43499870-3c168df2-9580-11e8-81de-35f3a5db5e38.png">

**Comment by joshdholtz** [comment]
@FunnyFzl This totally does look like a configuration issue with how Ruby/fastlane was installed? Do you know if you installed this Ruby or fastlane with sudo? That would probably cause this permission issue. 

The part that its failing on is actually trying to write a small file since we have some opt-in anonymized analytics that we recorded. To get around **this** failure could set the an environment variable to bypass this (`FASTLANE_OPT_OUT_USAGE=1`) but I would think that you would still run into other issues down the road.

I think the proper solution would to be reinstall Ruby/fastlane without sudo if that is what happened 🤔
