### ISSUE TITLE
How do you properly configure gym for Apple Watch targets? 

### ISSUE THREAD

**Issue by jefflopes** [fastlane/fastlane#13015]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

gym

Sort of. I'm not sure how to configure gym for an Apple Watch target. The docs don't mention it, so I'm not sure if it's supposed to just work or if it's not supported. I'm also using Xcode10 because I need watchOS 5, to complicate things further. 

No

#### Question Description

I'm running the following: 
fastlane gym --scheme "tenpercenthappier" --export_method app-store --clean

And getting this error: 
error: unable to resolve product type 'com.apple.product-type.application.watchapp2' for platform 'iphoneos'(in target 'Watch')

Full build log here:
[fastlane_out.txt](https://github.com/fastlane/fastlane/files/2249787/fastlane_out.txt)

Fastlane env here: 
[fastlane_env.txt](https://github.com/fastlane/fastlane/files/2249788/fastlane_env.txt)

**Comment by joshdholtz** [comment]
@jefflopes Heyy 👋 Thanks again for making this issue so that we can have the conversation here!

That ` error: unable to resolve product type` error is actually not one I have seen myself before 😔 And Googling that error actually doesn't come up with anything either.

I'm not sure when this app was developed but did things build properly in Xcode 9? (if you built it with that ever) Otherwise I may need to get a Xcode 10 app with watchkit spun up myself to see if I can duplicate this error 🙃

**Comment by jefflopes** [comment]
Unfortunately, the Watch app is new to our project in Xcode 10, since it depends on some new capabilities. How does gym know which Watch SDK to use? "sdk" appears to specify the iOS SDK, but I don't see an equivalent for Watch.

**Comment by joshdholtz** [comment]
@jefflopes _gym_ should know how to build the watch app based upon Xcode build settings in that watch target. I'm out at a lake right now with really bad internet so I can't download latest Xcode beta but I will pull that down next week and try to get my own project setup to see if I can duplicate this 🤔 

I'd really like to figure out what the error means since I have never seen it before myself 🙃

**Comment by jefflopes** [comment]
@joshdholtz In the meantime, I'll see if I can get a standalone project setup to reproduce the issue so I can share it with you. Thanks again for the help.

**Comment by joshdholtz** [comment]
@jefflopes Not a problem! I hope we can figure this out 😊

**Comment by 10percentdev** [comment]
@joshdholtz Any updates on this?

**Comment by taher-mosbah** [comment]
@jefflopes having the same issue, did you find a workaround ?

**Comment by GabePires** [comment]
Hopefully this will help someone. I believe the error is unrelated to fastlane. I was trying to run an old watch app I hadn't opened since Sept 2015 and run into an error on build similar to the above.

My solution had two steps:
1. Go into build settings for both the WatchKit Extension and WatchKit App and change the baseSDK and supported platforms from iOS to watchOS
2. Open up the project.pbxproj file in a text editor like sublime text and find these two bits:
`com.apple.product-type.application.watchapp`
and `com.apple.product-type.watchkit-extension`
Change these them to:
`com.apple.product-type.application.watchapp2`
and `com.apple.product-type.watchkit2-extension`
