### ISSUE TITLE
Match could delete provisioning profiles but not certificates

### ISSUE THREAD

**Issue by Khronoss** [fastlane/fastlane#13022]
### Feature Request
When using `fastlane match nuke` or another option, match could be able to delete ONLY provisioning profiles and keep certificates

#### Motivation Behind Feature
I find it a bit annoying, when I want to simply reset all of my provisioning profiles to also have to delete my certificates

#### Feature Description
If working with match's `nuke` feature, it could ask to wether delete certificates with the profiles or not to, or juste add a feature like `match dynamite` that will be expected to delete ONLY provisioning profiles

It would work exactly the same way as `fastlane match nuke`, but ONLY for provisioning profiles

#### Alternatives or Workarounds
The only workaround I find is deleting by hand the profiles in the github repo and then ask match to recreate them

**Comment by joshdholtz** [comment]
@Khronoss Thanks for the feedback and feature request! This is definitely something that I have experienced myself as well. Offering an option to delete a cert does get a little risky since sometimes that can take a whole app down (if its enterprise) so it is something we have limited in the past but _could_ be brought up again for discussion 🙃   I will think about this one over the weekend on how to best approach this issue 🤔

**Comment by Khronoss** [comment]
Thank you for your answer ! :)

I don't get why it can be so risky to delete provisioning profiles regarding deleting profiles AND certificates, for me it's actually safer or simpler, non ? Otherwise you're talking about a use case I'm not aware of :s

**Comment by joshdholtz** [comment]
@Khronoss Deleting distribution certificates for Adhoc (in App Store accounts) or In House (in Enterprise accounts) will actually prevent apps that are installed on users from opening. This distribution apps that are distributed and signed with that cert. A developer will then be forced to create/use a new cert and redistribute to the app to all the users. This may not be that big of a deal for Adhoc as there isn't a huge user base (most likely) but this can be a big deal for enterprise accounts that have an app distributed to thousands of users.

This **is not** an issue for apps released to the App Store because Apple actually resigns the IPA once upload to App Store Connect with their own certificate so that you are safe to revoke your cert and not ruin any of your users' experiences that downloaded the app through the App Store.

So for the sake of the adhoc and enterprise situations (and because that cert process may be confusing to some developers), we originally wanted to mitigate thje risk the accidental deletion of certificates, the possible consequences, and the invalidation of provisioning profiles 🙃

**Comment by Khronoss** [comment]
Ohhhhhh @joshdholtz I think we're victims of some misunderstanding, I absolutely don't want to wipe out a single certificate, but rather being able to delete ONLY the provisioning profiles of the registered certificate(s)

Nowadays, when using `fastlane match nuke`, it erases the provisioning profiles AND the certificates, but I would like to tell it to delete only provisioning profiles and NOT to delete the corresponding certificates
