### ISSUE TITLE
Reviews takes very long time. 

### ISSUE THREAD

**Issue by scorpion35** [fastlane/fastlane#13030]
I am trying to retrieve reviews for several apps. It seems each app is taking a very long time (about 2 hours or over).  Is anyone else having the same issues? Can you suggest a faster method, please? 

Here's my code

```ruby
itc_app = Spaceship::Tunes::Application.find("bundleid")
all_reviews = itc_app.ratings.reviews()
```

I have also tried to limit the reviews per storefront (e.g.: `itc_app.ratings.reviews("US")` OR `itc_app.ratings.reviews("GB")`, etc.), but that doesn't seem faster either.

Also tried limiting the reviews by version. 
```ruby
tunes_client.get_reviews(itc_app.apple_id, itc_app.platform, "US", version.version_id.to_s)
```

Here's an example, 
```
2018-08-03 11:14:33 PM -04 EDT - INFO - [apple_reviews] | Finding all available reviews for "bundleid1" ...
2018-08-04 02:18:39 AM -04 EDT - INFO - [apple_reviews] | Found 90,000 reviews.
```
[_Notice the time difference between two log lines above._]

Any help is greatly appreciated :)

**Comment by scorpion35** [comment]
@taquitos ^^ :)

**Comment by joshdholtz** [comment]
@scorpion35 Heyyy 👋 So, this is totes because you are 90,000 reviews  😊 The `reviews` method you are calling will actually pull down every single review (100 per page) until there are no more reviews - https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/tunes_client.rb#L361-L381

This is done to make thing easier on whoever is calling this function but this looks like it may actually be hurting you due to the number of reviews your app has. We can could find a way to change up this API call so you can page manually if that is what you are looking to do? How are you using these reviews? Are you expecting to get all of them or just a subset?

**Comment by scorpion35** [comment]
@joshdholtz Thank you very much for the reply. I am trying to run sentiment analysis on our reviews (for all apps within my account). My script runs daily and tries to fetch reviews from yesterday, and run sentiment analysis. 

I have figured a way to limit the reviews, by adding an optional parameter `upto_date`. Please take a look at my pull request here - https://github.com/fastlane/fastlane/pull/13040. It brings down the time to seconds from several hours!

Kindly let me know if you need any more information! :)

**Comment by scorpion35** [comment]
https://github.com/fastlane/fastlane/commit/413fb07f25a8e6355a4f0b76eaab6933269800cd
