### ISSUE TITLE
3-step authentication with Fastlane?

### ISSUE THREAD

**Issue by pronebird** [fastlane/fastlane#13037]
Hi,

I've been playing with Fastlane recently and now it has 3 step authentication. I am not sure WTH because Xcode uploads everything fine after 2 step authentication, but Fastlane also requests "application specific password". Is this a bug or am I doing something wrong?

Cheers,
Andrej

**Comment by joshdholtz** [comment]
@pronebird Heyy 👋 If you could please use an issue template for you next issue and include some more information like `fastlane env` and an example of your `Fastfile` that would be a huge help when trying to answer issues 😊 

But... it seems like the "application specific password" you are mentioning is what _fastlane_ uses when uploading an app to App Store Connect using iTunes Transporter (which is the application that Apple provides with Xcode to upload apps). So it seems like is that iTunes Transporter is not receiving a password (or receiving the wrong password) from you so that it can't verify you and upload your app to App Store Connect. I could be totally wrong here because I don't have any idea what playing around with _fastlane_ you are doing but this seems like what you are experiencing 🙃 

A standard approach to using _fastlane_ is giving _fastlane_ its own Apple account (instead of using a personal one). This way you don't need to enable 2 step or 2 factor authentication and then revoke this account whenever you want without any personal side effect.
