### ISSUE TITLE
Timeout waiting for fulfillment of promise for 'remote query'.

### ISSUE THREAD

**Issue by ViktorBylbas** [fastlane/fastlane#13048]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

I get "Caught error... 65"

#### Question Description
I get this error when I want get screens. I add string XCUIApplication().webViews.links[" STORE"].tap() in UI tests on iOS. Before the "STORE" line, a square with "?" inside.

UI Tests:
`class YogaUITests: XCTestCase {
        
    override func setUp() {
        super.setUp()
        
        let app = XCUIApplication()
        setupSnapshot(app)
        app.launch()
    }
    
    override func tearDown() {
        // Put teardown code here. This method is called after the invocation of each test method in the class.
        super.tearDown()
    }
    
    func testExample() {
        snapshot("start")
        XCUIDevice.shared.orientation = .faceUp
        snapshot("first")
        
        let webViewsQuery = XCUIApplication().webViews
        webViewsQuery.children(matching: .other).element.tap()
    
        snapshot("second")
        webViewsQuery.links[" STORE"].tap()     // here get error
    }    
}`

fastfile:

`platform :ios do
	lane :snapshots do
		snapshot(
			project: "platforms/ios/" + @appName + ".xcodeproj",
            skip_open_summary: true
		)
	end
end`

Please, help me

**Comment by janpio** [comment]
Please don't just delete the issue template but fill it out. 
Your issue currently doesn't have nearly enough information to answer you question.

**Comment by joshdholtz** [comment]
@ViktorBylbas This seems like it is more of an Xcode / UI Tests error instead of something directly _fastlane_ related 🤔 Error code 65 means there was an error when compiling your app. So if _fastlane_ sees error 65 that usually also means that your app is having issues compiling in Xcode as well (there are some cases where this is not the case). But this seems like you may have an invalid character or some sort on that line that is causing your app and/or tests to not compile properly. There isn't much we can do on our end to look into this so this is something that I think you will need to attempt to debug yourself 🙃 If you do find this is 100% an issue with fastlane, please let us know by giving us more information with your `fastlane env`, your `Fastfile`, steps that we can take to reproduce, and any workarounds that you may have.

I **actually** did end up copying and pasting your line of code that errors into my sample _snapshot_ project and it compiled properly for me so it seems like you may have another type of invalid character (maybe invisible) on the line that is in your Xcode project that is causing your project to fail 🤔
