### ISSUE TITLE
lane :beta match() fails with code 70

### ISSUE THREAD

**Issue by lmenus** [fastlane/fastlane#13150]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Fastlane Match

#### Question Description

Hi,

I am setting up Fastlane for a new project and going through the deployment to Testflight test case. So far I nuked all certificates and created new ones. Here's my current `Fastline` file.

```rb
default_platform(:ios)
xcversion(version: "9.4.1")

platform :ios do
  lane :beta do
    match(type: "appstore", force_for_new_devices: true)
    build_app(scheme: "app_scheme")
  end
end
```

And indeed, running

```sh
$ fastlane beta
```

Generates an app build! 🎉

The trouble appears if I replace the match `type` to `development`. The action exits with error 70.

```sh
There seems to be a mismatch between your provided `export_method` in gym and the selected provisioning profiles.
```

I have not modified this file (yet 😬) so the values there would be defaults I guess. My question is, should I not use `type=development` for the `beta` lane? (I am not sure I understand correctly what this setting does.)

If that's of any help, I have an app target with 3 different bundle identifiers depending on build configuration (dev, stage, release)

Thanks!

**Comment by marksiu** [comment]
Hi,
I am not fully understand your questions, please let me know if i cannot answer your questions. It would be great if you can provide the full error log.

`Match` is a services which helps to manager certificates and provisioning profile.
Normally, we have the following setting in iOS.
* build app to iDevice via Xcode: `development` provisioning profile with `develop` certificate
* build the app and then download from platform (e.g. Crashlytics): `adhoc` provisioning profile with `production` certificate
* build the app and submit to TestFlight/App store: `app store` provisioning profile with `production` certificate

the `match` parameter `type` is referring to the provisioning profile type. It has 4 values for you to choose, `development` (default value), `adhoc`, `appstore`, `enterprise`
(you can type `fastlane action match` to check the attachment screen)
<img width="1040" alt="screen shot 2018-08-18 at 12 28 01 am" src="https://user-images.githubusercontent.com/22641551/44277767-41e66f80-a27e-11e8-9fe5-f221d1ed7ddf.png">

If you would like to upload your build to TestFlight by `fastlane beta`, it should use `appstore` in `type` because Apple won't accept `development` type provisioning profile.]

The error message `There seems to be a mismatch between your provided `export_method` in gym and the selected provisioning profiles.` may refer to one of the following reason
1. build scheme Archive session is not using correct configuration
2. no valid `appstore` type provisioning profile found in your Apple developer account

Hope it can help.

**Comment by lmenus** [comment]
Hi @marksiu, thank you for your help! I am now a few hours into Fastlane so getting more comfortable with it. The issue was when I was trying to upload to Testflight with the following command.

```rb
match(type: "development")
```

So I guess you should use only `appstore` as you wrote above.
