### ISSUE TITLE
produce has endless loop when invalid app name is used

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/fastlane#13192]
<img width="843" alt="screenshot 2018-08-22 06 01 52" src="https://user-images.githubusercontent.com/869950/44493308-83d43480-a635-11e8-946f-b6b08d3406e2.png">

This asks me if I want to try again, but then it still auto-fills that username to the invalid one. It should ask for my input again.

**Comment by KrauseFx** [comment]
@joshdholtz is that something you can take a look at? This was done as part of `fastlane init`

**Comment by joshdholtz** [comment]
@KrauseFx I think I'm confused by this 🤔 The error here is it can't create the app in App Store Connect because the app name is greater than 30 characters so it fails because of that and then tries again but will fail again because that name is too long? 

Should a different behavior happen if this error occurs?

**Comment by joshdholtz** [comment]
@KrauseFx I don't fully remember this but is the value for `app_name` taken from the Info.plist?
