### ISSUE TITLE
Revoking developer access using match

### ISSUE THREAD

**Issue by kernow** [fastlane/fastlane#13298]
### Question Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Revoking developer access using match

#### Question Description
I apologise if this has been covered before, I couldn't find anything relating to this in the docs or GH issues.

As I understand it when using match to manage certificates you create a single apple account and certificates relating to this. The account credentials are then shared among all of the developers in the team. What happens when one of the developers leaves the company? How can access be revoked for a single developer without having to change the apple account password and update all team members with the new password. How can you tell who has pushed a particular build if everyone is using the same account?

I can see there are some benefits to using match but there appears to be some serious downsides to it unless I'm misunderstanding how it works in some way.

Thanks

**Comment by getaaron** [comment]
Typically you would use a machine account and you should rotate the password regularly. There are many solutions to shared credentials like 1Password for teams, vault, SafeSend, etc. You can keep the machine user’s password wherever you keep other shared credentials like API secrets, SSH private keys, etc.

If you don’t have a process set up for dealing with shared credentials, I would recommend setting one up. If you can’t for some reason, then maybe use cert and sigh instead of match.
