### ISSUE TITLE
Warn or do not promote a buggy version

### ISSUE THREAD

**Issue by zedtux** [fastlane/fastlane#13326]
#### Motivation Behind Feature
After having complained in the issue #13284, @janpio suggested me to open this issue proposing the following idea :

After a new release has been published, fastlane promote it to its users at the end of a run, which is great ... until you upgrade to the latest version, a Friday afternoon, and just before the week-end you have to push a new release to TestFlight and fastlane fails at sending your ipa 😭.

The existing feature showing Github issues relating to the occurred error is a very good thing, but is too late. Your week-end is about to start and you have this big red error on your screen with your boss in your back waiting for the new version ... you start to see your week-end shortening 😅.

#### Feature Description

The idea is to flag a version as buggy, therefore shows a warning on that version to the fastlane users, or even better, yank the version so that it will not be installed.

#### Alternatives or Workarounds
For people having already upgraded to that stale version, suggesting them to downgrade could help them so save their precious time.

**Comment by janpio** [comment]
The solutions to your boss problem:
1. Don't upgrade on production but try on your staging system first.
2. Just downgrade again and it will work as before.

Regarding your feature request:
- Where should this "flagging" happen?
- How should "yanking" a version work?
- Who decides if something should be "flagged" or "yanked"? 
- Do you do this for each small regression? What about all the bug fixes that were in the version and improving the life of many other users?

**Comment by joshdholtz** [comment]
@zedtux My apologies on `2.103.x` 😔 This was a big release for us as we reworked some internals to bring more support to Windows and updated _spaceship_ to use appstoreconnect.apple.com instead of itunesconnect.apple.com. Our unit tests are pretty robust and we run our test suites many times but we cannot catch everything.

To address your feature request:
We try to push out hotfixes as soon as we see them come in so that any users who update to the latest will get the fixed versions. I don't think that adding the ability to flag a version as "buggy" is the proper approach to solving this problem. The first thing is for us to make sure what we are producing is 💯 but we all know that is not always the case with software. The second thing we do is to try access the situation of any problems that arise. If its not a fix that we can address within a morning or afternoon's times, we will revert the fix or pull the version. If its something we can fix, we will push out a patched version.

I don't know exactly what version you are referring to as being buggy but we had a few hours between `2.103.0` and `2.103.1` and then released another version a few hours ago to fix a few more things that are now in `2.104.0`. 

`2.103.1` did not seem buggy enough to pull

If it wasn't working for someone exactly as they needed it, they are always welcome to set _fastlane_ in their `Gemfile` to whatever version they would like 🙃 Rubygems makes it very easy to upgrade, downgrade, or stay locked at a version of a gem. Our users aren't forced to use the newest gem but we do show the changelog because things can move so fast. 

---

## Actions to take
- We will not be implementing a flag for "buggy"
  - We do not intend to ship buggy software and don't want to make it seem like we do
  - If a new version does seem to cause a lot of issues, we will find the problem and decide if we can do a hotfix in time or pull the build
- We will aim to ship smaller changesets in our versions to allow for more confident releases that are easier to verify 💯 % that things are working

I appreciate your the time you spent to write your feature request ❤️ Happy fastlaning 🚀

**Comment by zedtux** [comment]
## Answer to @janpio :

In my case, the boss problem was a joke, but I can imagine this could happen.

> Don't upgrade on production but try on your staging system first.

In our case, we are in development phase, we don't have a product yet for that app. So our "production" is our staging, but we have people testing it.
Again, as it was a joke, there were no pain.

> Just downgrade again and it will work as before.

And that's what I did, but it's out of the scope of this feature request as its goal is to avoid this situation.

> Where should this "flagging" happen?

> Who decides if something should be "flagged" or "yanked"?

Well you better know your project than me. I'm not writing you a technical spec but a use case.

> How should "yanking" a version work?

[`gem yank` documentation](https://guides.rubygems.org/command-reference/#gem-yank) is your friend.

> Do you do this for each small regression?

That will be up to you guys to decide when a version has too much regression.

> What about all the bug fixes that were in the version and improving the life of many other users?

Why would this be lost ? Especially if as said @joshdholtz :

> [...] we had a few hours between 2.103.0 and 2.103.1 and then released another version a few hours ago to fix a few more things that are now in 2.104.0

So the *bug fixes that were in the version and improving the life of many other users* will be available few hours later, that's all.

## Answer to @joshdholtz 

There's no problem, as I said, we had no pain, and it could happen even with a lot of tests ... even you would have a 100% code coverage it would happen.

> The first thing is for us to make sure what we are producing is 💯 but we all know that is not always the case with software.

Exactly and that's why managing the case where things are broken is nice, and I guess that's why you have this feature to show the related Github issues, which I repeat is nice.
And you did it to address this case where something went wrong and the task failed.
In my eyes, this request is not a revolution, it's just a second measure added to the existing one, showing the Github issues.

## Anyways to summarise this request

This request is just about improving this awesome tool that is fastlane. This request is not a magic solution to the problem of the world as @janpio tried to said in his comment, so it's not something that will be used a lot ... well hopefully for you guys 😅.

The real goal is to avoid people upgrading, and being stuck within an important deployment. Of course downgrading is a workaround, but then please let me reuse your sentence @janpio :

> What about all the bug fixes that were in the version and improving the life of many other users?

It's just that it could be avoided that people upgrade, are stuck, downgrade, then fears upgrading again next time and finally stick with an old version which is working.

## Last words

As this request is not critical, and we spent already enough time (actually on my part, I let you decide for yourself guys), if you aren't convince, feel free to close it but bare in mind what I explained to you.
In the other hand, if you think it's fair and want to continue discussing how to do it, and not if you'll do it, then I'm available.

Cheers.

**Comment by zedtux** [comment]
... I see. Let's the bot close this issue. 😶

**Comment by zedtux** [comment]
What a shame ...
