### ISSUE TITLE
setup_jenkins on slave agent 

### ISSUE THREAD

**Issue by quver** [fastlane/fastlane#1340]
```
[09:42:59]: ---------------------------
[09:42:59]: --- Step: setup_jenkins ---
[09:42:59]: ---------------------------
[09:42:59]: Not executed by Continuous Integration system.
```

**Infrastructure:**
- Jenkins on Linux VM
- Slave agent via SSH on Mac OS 10.11

In this scenario setup_jenkins returns `Not executed by Continuous Integration system`

Temporary workaround 

```
setup_jenkins(
    force: true
)
```

**Comment by jerome-mare** [comment]
This error is due to the fact that the is_ci? helper function is looking for an environment variable named JENKINS_URL, if the environment variable is set, setup_jenkins is executed. This variable is set only on Jenkins Master. Jenkins Slave do not provide this variable.

A quick workaround is to define the variable JENKINS_URL to the Jenkins Slave Node.

To fix the issue, is_ci? helper function has to look for JENKINS_URL or JENKINS_HOME environment variable to detect if we are executing fastlane on jenkins ci or not.

I will create a pull request to fix this issue

**Comment by quver** [comment]
Thank you

2016-06-07 22:40 GMT+02:00 jerome-mare <notifications@github.com>:

> This error is due to the fact that the is_ci? helper function is looking
> for an environment variable named JENKINS_URL, if the environment variable
> is set, setup_jenkins is executed. This variable is set only on Jenkins
> Master. Jenkins Slave do not provide this variable.
>
> A quick workaround is to define the variable JENKINS_URL to the Jenkins
> Slave Node.
>
> To fix the issue, is_ci? helper function has to look for JENKINS_URL or
> JENKINS_HOME environment variable to detect if we are executing fastlane on
> jenkins ci or not.
>
> I will create a pull request to fix this issue
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fastlane/fastlane/issues/1340#issuecomment-224407152>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AATX-mks5yakVLENj43wBl5pFnusNfcwks5qJddAgaJpZM4Hc3ac>
> .
>



-- 
Pozdrawiam,
Paweł Bednorz

**Comment by TKBurner** [comment]
@jerome-mare Thanks for stepping in on this! We'll review your PR 👍
