### ISSUE TITLE
Extending fastlane support for macOS: any interest?

### ISSUE THREAD

**Issue by mjm** [fastlane/fastlane#13573]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm aware that supporting the Mac platform is not a priority for fastlane. Unfortunately, for developers of Mac apps, there isn't a great alternative for automating codesigning and other workflows in CI. You can get fastlane to do it, but it's a lot harder than it is for iOS apps.

I would like to work on contributions to allow match, cert, and sigh to work for Mac apps as well. Is there any interest in accepting such contributions?

**Comment by fishcharlie** [comment]
I think this would be awesome. Although we don't know how the project from Apple to bring UIKit to macOS will work. The only risk is that things will really change and break when that gets released. But I think fastlane should support that since I wouldn't be surprised if there is a major influx of macOS applications after that gets released. So preparing for that and ensuring that fastlane is well prepared for that massive change I think would be great.

**Comment by janpio** [comment]
Hey @mjm and @fishcharlie, this would definitely be an interesting thing! As you already saw in #13607 @mjm, we are very open to merge pull requests regarding this topic.

One first step, would probably be to go and search through all the issues of fastlane to find out what current users of fastlane for macOS have as issues and problems and see if those can be fixed. Maybe a "Collection of problem with fastlane when using it for macOS app" issue might also be useful, where someone collects all disadvantages that currently exist - and then opens issue for each individual one and tracks if a PR was submitted or merged to fix the problem.

If you need any help, feel free to ping me!
