### ISSUE TITLE
Calling actions directly from ruby

### ISSUE THREAD

**Issue by MartinGonzalez** [fastlane/fastlane#13734]
Hi there! 
I've been using fastlane for our CI pipelines and it's awesome. But now I have a REST api and I would like to call for example SlackAction directly from Ruby. This project is not a fastlane plugin.

Is that possible or I'm misunderstanding fastlane
Thanks

**Comment by janpio** [comment]
So you have a random ruby project and want to use some of the functionality that fastlane offers via one of its actions?

That is certainly possible - somehow. I personally don't know enough about ruby to do that.

The code of the `slack` action lives here: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/slack.rb So if you have the `fastlane` gem installed, you also have this code.

What **I** would do though, would be to shell out and execute `fastlane run slack` with the correct params. This is probably really terrible, but it should work with no further work.

**Comment by MartinGonzalez** [comment]
That's right, I have a random project without being a fastlane plugin and the fastlane gem is in my Gemfile.
 I would like to call something similar to Fastlane::Action::SlackAction.run but that doesnot work. I did that hack to call a shell but I dont' like it :/

**Comment by joshdholtz** [comment]
@MartinGonzalez The _easiest_ way to call this would probably be to shell it out from Ruby (which feels bad) but it would be something like..
```rb
`fastlane run slack message:"Your message" slack_url:"your-url"`
```

This feels a bit bad because you have to shell out of Ruby to call other Ruby but this is the most straightforward way without doing through all the importing you would need to do yourself to call all the any actions you would possibly need to call.

If you are not integrating with any of the main fastlane tools in your API like _deliver_, _match_, _produce_, etc I would probably suggest to integrate slack into your API yourself with the slack gem as it will be more performant and probably easier to maintain 😊

**Comment by ast3150** [comment]
You can theoretically integrate any part of fastlane by addressing the module directly, for example using ```Spaceship::Tunes.login```

I'm actually trying to do something by integrating Fastlane into a Ruby app too at the moment. For simply using Slack from Ruby however, I would advise against using the Fastlane Action, and using the Gem called `slack-notifier`. It's quite simple to use, you can find the documentation [here.](https://github.com/stevenosloan/slack-notifier)

**Comment by MartinGonzalez** [comment]
Thanks a lot guys!

**Comment by hjanuschka** [comment]
i am not 100% sure if this still works, atleast it is a starting point: https://github.com/fastlane/fastlane/issues/6920#issuecomment-259351261

**Comment by geraldeersteling** [comment]
I'm also having troubles with this and would love a nice solution.

Wrote a 'helper' class in Ruby, but all fastlane actions (such as `match`) are unavailable, unless you call them directly I suppose.  
I'm now also 'shelling out' to call the necessary actions, but while this works it also bloats my code a little for every action I want to call from my helper...
