### ISSUE TITLE
Where we can write lanes code using spaceship fastlane

### ISSUE THREAD

**Issue by contactme-amol** [fastlane/fastlane#13985]
Hi Guys, 

I have question regarding spaceship: 
I gone through following link to understand spaceship, but unable to get where and which file I can write lanes or other code of spaceship. 
https://github.com/fastlane/fastlane/tree/master/spaceship

I need to implement spaceship for upload app IPA and need to submit IPA for beta review. 

I gone through describe steps for spaceship, but unable to find any create file step and add given code which described in example. 

- Which file I need to create to implement functionality of "Submit IPA for beta review on apple store"?
- How I can call specific function to build IPA and submit for beta review?
- Would you please describe more, so I can follow same steps to achieve results?

Your inputs will be helpful for me and can save my R & D efforts, I searched lot but can't find expected solution.

**Comment by janpio** [comment]
You probably don't need to use spaceship directly, just use what fastlane offers you: https://docs.fastlane.tools/

**Comment by joshdholtz** [comment]
@contactme-amol You are correct that `pilot` does not allow you to pass in demo account information. It does however look like that `deliver` does. You can probably but a combination of `deliver` to submit your IPA (with all the information you need) and then use `pilot` to submit the beta for review for now... but I will work on adding in the sending up of test account into to `pilot` since it should totally have that 🙃

**Comment by contactme-amol** [comment]
@joshdholtz - I tried above suggestion but it doesn't worked. 

I think, Test contact information should be go with pilot itself and it should submit app to external beta review. 

Following information should be filled like metadata.

![screen shot 2019-02-05 at 7 21 46 pm](https://user-images.githubusercontent.com/38633231/52278058-1b2b0b00-297c-11e9-9f76-d18c86f5b337.png)
