### ISSUE TITLE
Specify Android devices similar to iOS devices?

### ISSUE THREAD

**Issue by scottymeyers** [fastlane/fastlane#14172]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Screenshots

No

No

#### Question Description

I'm successfully obtaining screenshots on iOS on the multiple devices I've specified. My question is how am I to do the same on Android? I'll have multiple Emulators open, which `adb devices -l` recognize, but I'm only finding one devices images for each test.

**Comment by janpio** [comment]
As far as I know `screengrab`, the tool generating the screenshots for Android, wasn't written that way because Play Store accepts pretty much anything as a screenshot.

But not long ago someone implemented a `specific_device` parameter https://docs.fastlane.tools/actions/screengrab/#parameters that might help you achieve your goal.
