### ISSUE TITLE
modify_services from "on/off" to true/false

### ISSUE THREAD

**Issue by MartinGonzalez** [fastlane/fastlane#14202]
#### Motivation Behind Feature
Code homogeneity

#### Feature Description
Changing string to boolean in modify_service to keep code homogeneity

Right now modify_service receives a hash with `service_name: "on/off"`
Would it be better to change it to `service_name: true/false`

Before
```
modify_services(
  username: "test.account@gmail.com",
  app_identifier: "com.someorg.app",
  services: {
    push_notification: "on",
    associated_domains: "off"
  }
)
```

After
```
modify_services(
  username: "test.account@gmail.com",
  app_identifier: "com.someorg.app",
  services: {
    push_notification: true,
    associated_domains: false
  }
)
```

I can do a pull request if everybody agrees.

**Comment by johnknapprs** [comment]
I once thought the same thing.  Two issues come to mind: 

1. This would break a number of existing implementations (including my own).  However, perhaps the change could include both parameter types. 

2. Not all of the options are booleans.  
- - `data_protection` accepts `(complete|unlessopen|untilfirstauth)`
- - `icloud` accepts `(legacy|cloudkit)` 

If homogeneity is the goal, having users provide string answers would make more sense since some options requires strings.  Having users switch between booleans and strings feels like it would go against that goal. 

That's just my 2 cents though.   Folks around these parts always seem happy to hash out ideas on the issue board or on a pull request.  

Happy hunting!

**Comment by MartinGonzalez** [comment]
> I once thought the same thing. Two issues come to mind:
> 
> 1. This would break a number of existing implementations (including my own).  However, perhaps the change could include both parameter types.
> 2. Not all of the options are booleans.
> 
> * * `data_protection` accepts `(complete|unlessopen|untilfirstauth)`
> * * `icloud` accepts `(legacy|cloudkit)`
> 
> If homogeneity is the goal, having users provide string answers would make more sense since some options requires strings. Having users switch between booleans and strings feels like it would go against that goal.
> 
> That's just my 2 cents though. Folks around these parts always seem happy to hash out ideas on the issue board or on a pull request.
> 
> Happy hunting!

Thanks for your answer! And is there any reason why they are string and not symbols? Like

:legacy
:cloudkit
:on
:off

**Comment by janpio** [comment]
Breaking existing functionality obviously is a big no-no. But a PR that adds true/false as additional valid values for the entries that are current on/off, I see no reason why this should not get merged and allow a more obvious and simple usage of the action.

**Comment by MartinGonzalez** [comment]
Cool, I will do it on weekend! :D
