### ISSUE TITLE
Apple February 12 Update merging developer teams and roles on Apple Developer and App Store connect

### ISSUE THREAD

**Issue by metekabak** [fastlane/fastlane#14200]
Hi,
Currently we are using Spaceship::Portal and Spaceship::Tunes for to verify the permissions and the given informations.

Will there be any changes on implementing this?

Thanks.

https://appstoreconnect.apple.com/role-updates/
![image](https://user-images.githubusercontent.com/3997926/52362054-c4433580-2a50-11e9-8afb-c1f7444cf166.png)

**Comment by janpio** [comment]
Very probably.

Unfortunately there is no public information about how exactly things will change yet, so fastlane can't really be prepared.

**Comment by petekanev** [comment]
If I may hijack the topic to ask a related question to the upcoming changes - How much do you think the fastlane `produce` and `deliver` APIs will change, considering those make use of not only the teamId but also the ItunesConnect team ids?

Thanks!

**Comment by janpio** [comment]
Pretty much the same response: No idea, depends on how they implement it. If the APIs just start taking one value instead of the other, we just have to update our code in a few places (and clean up a few awkward namings). If it is more, we will have to do whatever it takes to update - and try to keep our external API working so your lanes can just work as before.

**Comment by jonassvalin** [comment]
Hi Fastlane team,
Unsurprisingly this change seems to have affected our deployment pipeline. Our first attempt at building and deploying to TestFlight since this change occurred failed with the following error:

`{"responseId"=>"X", "resultCode"=>9999, "resultString"=>"You are not permitted to create distribution provisioning profiles for team.  Please contact one of your team admins, who can create a profile on your behalf.", "userString"=>"You are not permitted to create distribution provisioning profiles for team.  Please contact one of your team admins, who can create a profile on your behalf.", "creationTimestamp"=>"2019-02-13T00:27:05Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/profile/createProvisioningProfile.action", "httpCode"=>200}`

We have not made any changes to our provisioning profiles or the user that is used to perform this deployment. Has anyone else seen a similar issue yet?

**Comment by janpio** [comment]
(Best open a new issue @jonassvalin and include all the information asked for in the issue template. Thanks.)

**Comment by abotkin-cpi** [comment]
Given the update emails following up on this today where Apple is going to require two-factor authentication starting February 27th, will there be some sort of transition document/pinned issue on what options folks have with Fastlane?  A lot of the docs today steer people away from using two-factor on the CI, so I imagine many will need to make this transition prior to the 27th and those who don't will start filling tickets on the 27th.

**Comment by janpio** [comment]
> A lot of the docs today steer people away from using two-factor on the CI

What do you refer to here? Fastlane (via spaceship) should fully support 2FA (and the older 2 step verification), also on CI via the session cookie.

**Comment by abotkin-cpi** [comment]
@janpio 

https://docs.fastlane.tools/best-practices/continuous-integration/

```
Two-step or Two-factor auth

Separate Apple ID for CI

The easiest way to get fastlane running on a CI system is to create a separate Apple ID that doesn't have 2-factor auth enabled, with a long, randomly generated password. Additionally make sure the newly created Apple account has limited access to only the apps and resources it needs.

There are multiple reasons on why this approach is much easier:

An Apple ID session is only valid for a certain region, meaning if your CI system is in a different region than your local machine, you'll run into issues
An Apple ID session is only valid for up to a month, meaning you'll have to generate a new session every month. Usually you'd only know about it when your build starts failing
There is nothing fastlane can do better in that regard, as these are technical limitations on how App Store Connect sessions are handled.

Creating a separate Apple ID allows you to limit the permission scope, have a randomly generated password, and will make it much easier for you to set up CI using fastlane.
```

**Comment by janpio** [comment]
I am currently in the process of updating this page in the documentation to highlight the ways to work with 2FA (and of course remove the outdated information about the separate Apple ID). Should be merged soon-ish.

Important to note: Fastlane already fully supports 2FA, so we fortunately don't have to do too much work here.

**Comment by jeremyspatrick** [comment]
>Fastlane already fully supports 2FA, so we fortunately don't have to do too much work here.

@janpio What about for users that are unable to log into a production machine to type in an mfa code into the terminal? Fastlane may support 2FA in the terminal but it is not prepared for the apple change requiring 2FA. Having 2FA as a requirement breaks our development process. 

Is there a way to use the fastlane application specific password for cert, sigh, produce

**Comment by janpio** [comment]
Yes: https://docs.fastlane.tools/best-practices/continuous-integration/#security-code-and-session

**Comment by jeremyspatrick** [comment]
@janpio won't this ENV session variable expire after a month?

**Comment by janpio** [comment]
More or less, yes. (We don't have current data on the exact session validity) But it allows you to not having to enter a 2FA token _each_ time, as you would have to do without the session cookie.
