### ISSUE TITLE
Observations on the Fastlane/Spaceship session length

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#14301]
After the topic how long the `FASTLANE_SESSION` is valid came up in https://github.com/fastlane/fastlane/issues/14239, @ZonD80 [asked](https://github.com/fastlane/fastlane/issues/14239#issuecomment-465919376):

> What if just ping apple after entering 2FA code every N hours to keep session alive? is it an option?

This led to [me answering](https://github.com/fastlane/fastlane/issues/14239#issuecomment-466056523):

> @ZonD80 That depends on if they actually extend the session length, and if spaceship correctly handles updating the session cookie. Some testing there would be greatly appreciated!

Fortunately he took the "bait" and [replied](https://github.com/fastlane/fastlane/issues/14239#issuecomment-466059554):

> @janpio okay, i'm on it. We will test it on Friday.

and [later](https://github.com/fastlane/fastlane/issues/14239#issuecomment-466356753)

> @janpio here are some tests:
> _Spaceship::Portal.login(email, password)_ - acquires 2FA session cookie and with second login it remains the same - so no cookie is updated after login. However, via browser, apple sends the same cookies, but with another expiration date (+year). **I guess we need to change behavior to updating of local session cookies with every login/request.**
> 
> Upon cookie deletion (removal of file) - it requires new 2FA PIN code, so i guess their "Trust" button is only cookie life extension, because it is not working if i using incognito mode.
> 
> I've placed a worker in our system to auth on dev portal every 600 seconds, let's take a look, will it survive till Monday or not.

As this discussion and further observations might not be of interest for all the people in that issue, I created this one where we can continue.

**Comment by janpio** [comment]
Some official information from Apple on how long logins with 2FA should be valid:

> **Will I need to enter a verification code every time I sign in to my Apple Developer account?**
>
> Once two-factor authentication is enabled, you’ll need to enter a verification code every time you sign in, unless you choose to trust the browser, in which case you won’t be asked for a verification code again from that computer for **30 days**. You may be asked to re-verify if you reset or change browsers.

via https://developer.apple.com/support/account/authentication/

**Comment by LanceMcCarthy** [comment]
Currently is a real PITA to have to generate and reset my session cookie is Azure DevOps every day I need a build to upload :)

It seems I don't need to re-enter my password or get a new 2FA code when executing `fastlane spaceauth -u user@email`, but I'm guessing this is where the 30 limit @janpio just mentioned will be a big problem.

**Short-term fix?**
Automatically update FASTLANE_SESSION value when using `spaceauth -u user@email`

I've always had to copy cookie out of the CLI (manually or by entering "Y" when spaceauth is done).   Is there a command switch that I can use to automatically update the current value of the FASTLANE_SESSION variable? 

Example: `fastlane spaceauth -u user@email -UPDATE_FASTLANE_SESSION`?


I know about the `export FASTLANE_SESSION='cookie_is_here'` command, but it looks like the cookie has to be pasted in between the single quotes. 

How do I automatically do that without interaction?  Or am I doing it wrong and the FASTLANE_SESSION is already set once spaceauth completes?


Thanks, and sorry for any nooby questions. I've been using Fastlane for a while, but it's been all hands-off until Apple made this change to Account Holder roles.

**Comment by janpio** [comment]
Please open a new issue about this @LanceMcCarthy. This is actually more a CI/Azure Pipelines question than a Fastlane question. (I will remove your comment here (and this answer) as soon as you have opened a new issue.)

**Comment by LanceMcCarthy** [comment]
Hi @janpio ,

I think I muddied the waters by mentioning Azure DevOps, my apologies :) 

It's completely irrelevant because all of these operations are happening on my local Mac (DevOps simply runs Faslane commands remotely on the Mac on my desk).

I've opened https://github.com/fastlane/fastlane/issues/14305 to continue the discussion and request feature 

(PS - It's likely that Fastlane already does it, and I just don't know the command. It's not obvious from the docs)

**Comment by zargox** [comment]
Guys,

Regarding "Account Holder role", it is needed to have this for "individual" companies for creating session cookies in Fastlane. For other organizations it is not needed to work with fastlane session cookies, you can add your email address as a member, and access the account.

**Comment by ZonD80** [comment]
2FA session is still alive after launch on Friday with login every 600 seconds

**Comment by janpio** [comment]
Awesome, so updating the session cookie might be something to look into. Can you share your setup so we can reproduce this?

**Comment by ZonD80** [comment]
How can i share it, what exactly do you need?

**Comment by janpio** [comment]
I was referring to:

> I've placed a worker in our system to auth on dev portal every 600 seconds, let's take a look, will it survive till Monday or not.

What exactly does this do and how?

**Comment by ZonD80** [comment]
`#!/usr/bin/env ruby

email = "EMAIL"
password = "PASS"

require "spaceship"
require "net/http"

puts "Logging into account #{email} with #{password}"


puts "logging to dev portal"

Spaceship::Portal.login(email, password)


puts "OK"

exit 0`

We just set this script to run every 600 seconds in a loop - that's it, it always gave us "OK" after first entering of 2FA code on Friday.

**Comment by janpio** [comment]
Thanks.

That leaves the question: How is fastlane's session/cookie system different than the website, where you do not need to re-login after x hours/days and not have to keep polling the login method to keep it alive?

**Comment by ZonD80** [comment]
OK i have an answer:)

I've tested if further - in fact you only need cookie with name "myacinfo", it can be grabbed from browser session and placed into fastlane cookie file (or otherwise, from fastlane to browser), (ofc if you have same country/IP/subnet) as your CI system (i've tested with ssh -D and proxy in browser).
Apple sends the same cookie with another expiration date.

Technically they should update last access time of this session and keep it valid after 30 days of last access time, otherwise workflow will may be broken when session becomes invalid. But, we need to wait for 30 days with active usage of this session to check it out.
So just pinging with this session may be an option...

**Comment by ZonD80** [comment]
LOL and you can just keep your myacinfo, change IP to another country - and still be authorised. It's... okay.

**Comment by janpio** [comment]
I will have to go deep into the code again to be able to verify this, but I thought this was already how it worked. (But maybe not if `FASTLANE_SESSION` is set - maybe we have to change that behavior to only use the ENV provided session on first usage, then the local file (but I _also_ think this should be how it works already))

**Comment by LanceMcCarthy** [comment]
Has anyone just tried to increase the `max_age` value in the cookie? Right now it looks like it's only set to **1800**, which might be the cause of our problems.

![image](https://user-images.githubusercontent.com/3520532/53349744-c419b580-38eb-11e9-82f2-e3cce8d120a4.png)

**Comment by RacingWang** [comment]
Hi all, I only run the upload action in my fastfile, and I setup the FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD env already. However, it still requires me entering the password and 2FA code of my Apple ID before uploading. Why?

**Comment by LanceMcCarthy** [comment]
@RacingWang This is because Apple made a change to their rules for Apple IDs that have App Manager level permissions: they must have 2FA enabled.

An easy workaround for this is to just create a new Apple ID that doesn't have 2FA enabled and generate an App-Specific-Password for that account. 

Add that account to your dev portal with only `developer` permission and use that account for your Fastlane uploads.

**Comment by RacingWang** [comment]
@LanceMcCarthy Thank you for the reply. By the fastlane document, it seems to me that the application specific password can be a solution of CI service without 2FA (https://docs.fastlane.tools/best-practices/continuous-integration/#use-of-application-specific-passwords-and-spaceauth). BTW, I just found that I asked in the wrong thread lol, I should post to https://github.com/fastlane/fastlane/issues/14239 .

**Comment by mgrebenets** [comment]
I've ran into similar issues recently.

I've noticed that `spaceauth` outputs 2 cookie objects in the `FASTLANE_SESSION` variable:
one for `apple.com` domain with `max_age` empty and another one for `olympus.itunes.apple.com` domain with `max_age: 1800` (30 min).

If I use this `FASTLANE_SESSION` value on CI box, then I have to do 2FA every 30 minutes, which is not ideal and spaceship documentation says it should be around 30 days.

Then I looked into `${HOME}/.fastlane/spaceship/<apple-id>/cookie` and I can see that is has much more cookie objects in there, actually 4.
The cookie that seems to make all the difference is for `domain: idmsa.apple.com` and has `max_age: 2592000` (30 days).

So what I tried is take contents of `${HOME}/.fastlane/spaceship/<apple-id>/cookie` and it all into `FASTLANE_SESSION` on CI box.
I can confirm that after 30 minutes since last use the session did not expire and I was able to use `pilot` command without the need to generate new `FASTLANE_SESSION`.

The question is why does `spaceauth` output short version of the cookie that lasts for 30 minutes only? The cookie created on my dev laptop works on CI box all the same.

@janpio

**Comment by janpio** [comment]
Nice observation @mgrebenets. 

I actually don't really understand what is happening with the cookies, I can just link you to the code that select/keeps them: https://github.com/fastlane/fastlane/blob/2d8124410943c0c1fdbf7729b339006cb95d343b/spaceship/lib/spaceship/spaceauth_runner.rb#L30-L48 or the "blame" version of that: https://github.com/fastlane/fastlane/blame/2d8124410943c0c1fdbf7729b339006cb95d343b/spaceship/lib/spaceship/spaceauth_runner.rb#L30-L48 Maybe the PRs behind those changes tell you a bit what was the thinking there.

If including the idmsa.apple.com cookie helps, we can of course adapt that code.

**Comment by LanceMcCarthy** [comment]
The `idmsa.apple.com` cookie for spaceship would be fantastic, it would keep the CI/CD builds that rely on the FASTLANE_SESSION variable (i.e. Azure DevOps) at the same valid timeframe to the 30 day expectation.

Nice catch @mgrebenets

**Comment by janpio** [comment]
If that is the case, a PR for `spaceauth` would be very welcome - which then could also be tested by more people before rolling this out to all users.

**Comment by mgrebenets** [comment]
So I'd just have to figure out what's the "needed" cookie.

The code is this:

```ruby
      # We remove all the un-needed cookies
      cookies.select! do |cookie|
        cookie.name.start_with?("myacinfo") || cookie.name == 'dqsid'
      end
```

The cookie that has 30 days expiration day doesn't have a clean name:

`name: DES5d9905bb34aa91d4867f38ebd3b2664d1`

It starts with "DES" so it probably could do something with [DES](https://en.wikipedia.org/wiki/Data_Encryption_Standard).
If this cookie always starts with "DES", it wouldn't be difficult change to do.

Could anyone else confirm that they also have a cookie names like "DES...." in their `~/.fastlane/spaceship/<apple-id>/cookie`?

**Comment by mgrebenets** [comment]
I can confirm that adding just that one extra "DES" cookie for `idmsa.apple.com` domain works fine with FASTLANE_SESSION my setup.

The question I still got is how to pick that one cookie from all cookies.
If `DES` prefix is something that identifies the cookie in all cases, then that could be the fix.
Unless Apple later changes that prefix.
Another option is to look for cookie by "idmsa.apple.com" `domain` parameter and pick the one that has non-empty (and largest) `max_age` value...

Of course, there's always of option of just using all cookies, which increases the size of env variable but is more future proof.

**Comment by mgrebenets** [comment]
Oh, and the comment in the same file:

```ruby
      # The only value we actually need is the "DES5c148586daa451e55afb017aa62418f91" cookie
      # We're not sure if the key changes
```

so we do need that one and it gets filtered out :)

**Comment by janpio** [comment]
Yeah, that comment confused me as well - but the blame/history of the file might tell you a bit if that was just forgotten when something else was changed or if it is something else. Pretty confusing.

**Comment by ZonD80** [comment]
Looks like they have limited session to one day.
But, here is solution (thanks to stackoverflow):
`#! /usr/bin/env osascript
tell application "System Events"
    if name of every process contains "FollowUpUI" then
        tell window 1 of process "FollowUpUI"
            click button "Allow"
            delay 2
            set code to value of static text 1 of group 1
            log (code)
            click button "Done"
        end tell
    else
        log ("Couldn't find 2FA window")
    end if
end tell
return`
