### ISSUE TITLE
Path to project only works in prompt and not in Fastfile

### ISSUE THREAD

**Issue by vance** [fastlane/fastlane#14383]
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

Fastlane version 2.117.1

### Issue Description

in Fastfile
```
private_lane :build_enterprise do
      disable_automatic_code_signing(
          path: "../ios/App/App.xcodeproj",
```

prompted with `Couldn't automatically detect the project file, please provide a
path:`

when i enter the path exactly as I have it in my Fastfile, it works... 

found this issue https://github.com/fastlane/fastlane/issues/6516 but if I try pointing to the workspace, it says `Could not find option 'workspace' in the list of available options`

I also tried adding a `Dir.chdir("..") do` block to eliminate the `../` in the path, but that also does not work. did a `sh("pwd")` and it is in the correct directory. 

this is my project structure 
![image](https://user-images.githubusercontent.com/145471/54156620-db849280-4403-11e9-8600-2ea9f39e55e7.png)

Osx High Sierra
Xcode 10.1

##### Command executed

--capture_output does nothing....

**Comment by mollyIV** [comment]
👋 @vance 

I had a look at the code of `automatic_code_signing` action:

https://github.com/fastlane/fastlane/blob/9c894c997f3ac7f7c6263709b08c62bc236ee9d0/fastlane/lib/fastlane/actions/automatic_code_signing.rb#L8

☝️ it's using `File.expand_path(path)` under the hood. According to [ruby docs](https://ruby-doc.org/core-2.1.1/File.html):

> Converts a pathname to an absolute pathname. Relative paths are referenced from the current working directory of the process unless dir_string is given, in which case it will be used as the starting point.

So the solution for your issue is just passing the relative path:

```ruby
private_lane :build_enterprise do
      disable_automatic_code_signing(
          path: "ios/App/App.xcodeproj",
``` 

As an improvement we could tweak the documentation of the [`path` param](https://docs.fastlane.tools/actions/automatic_code_signing/#parameters) of `automatic_code_signing`, maybe something like: "Relative path to your Xcode project".

Wondering if the example from [the documentation](https://docs.fastlane.tools/actions/automatic_code_signing/#8-examples):

```
disable_automatic_code_signing(
  path: "demo-project/demo/demo.xcodeproj"
)
```

☝️ was clear for you or you thought it was the absolute path? 🤔 

Please let us know if that helped 👍

**Comment by johnknapprs** [comment]
Be sure to read the docs.  This is expected behavior for all actions vs in-lane user code.

https://docs.fastlane.tools/advanced/fastlane/#directory-behavior

> Notice how every action and every plugin's code runs in the root of the project, while all user code from the Fastfile runs inside the ./fastlane directory.

**Comment by vance** [comment]
Thanks, the paths were correct. I figured out the error was from setting the team, but it could not update the project. Basically, it was failing _before_ the compile step. Some failing on line X might have been helpful. So, doing this fixed it:
```
 update_project_team(path: "ios/App/App.xcodeproj", teamid: "TIMAPPLE")
```
