### ISSUE TITLE
[spaceship] Using the official App Store Connect API?

### ISSUE THREAD

**Issue by julien-c** [fastlane/fastlane#14405]
#### Question Description

Haven't been able to find a thread about this, so posting my question here:

The [doc for spaceship](https://github.com/fastlane/fastlane/tree/master/spaceship) mentions that the lib implements [5 different API endpoints](https://github.com/fastlane/fastlane/tree/master/spaceship#api-endpoints).

Last year, Apple shipped an official [App Store Connect API](https://developer.apple.com/documentation/appstoreconnectapi) whose endpoint is `api.appstoreconnect.apple.com` and which performs a few of the tasks that spaceship does. 

As far as I can tell, fastlane doesn't use this official API. 
Any architectural reason for this? It this something that's on the roadmap, or have you just not needed it yet?

**Comment by julien-c** [comment]
@joshdholtz @janpio Let me know if there's a better channel for something's that more of an architecture/design question.

**Comment by mollyIV** [comment]
👋 @julien-c 

Encourage you to check this thread: https://github.com/fastlane/fastlane/issues/12713 🙇

**Comment by julien-c** [comment]
Awesome, thanks @mollyIV, not sure why I couldn't find it in the first place.

**Comment by joshdholtz** [comment]
@mollyIV Thanks for linking to that comment!

@julien-c Thanks for bringing to my attention that it is hard to find 😊 It something we would **love** to do but its not possible for us to fully move to it due to limited feature set and a completely different authentication system. We do have _some_ API integrated here (because of old APIs being deprecated and requiring the use of the new ones) - https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/connect_api/client.rb. However, this implementation is highly likely to change yet as there are probably some improvements we can do due the standard spaceship API to make it a little be easier to use or easier to maintain.

But I did pin issue https://github.com/fastlane/fastlane/issues/12713 now so that it is easier to find 👌 

I'm going to close for now as we have the pinned issue to have conversations in 😉
