### ISSUE TITLE
supply: should package_name be read from APK?

### ISSUE THREAD

**Issue by HolySamosa** [fastlane/fastlane#14487]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
supply

#### Question Description

When executing `fastlane supply`, it picks up the APK in the working directory but still prompts for _package_name_ to be provided:
```
[10:59:48]: To not be asked about this value, you can specify it using 'package_name'
[10:59:48]: The package name of the application to use: 
```
In the the __supply__ documentation, the examples don't provide the package name via the command line, which suggests that it isn't required if the APK is present.

Should __supply__ read the package name from the APK?

**Comment by janpio** [comment]
I am not aware of such a feature, but is some time since I have looked at the `supply` source.

If you want to take a peak:
https://github.com/fastlane/fastlane/tree/master/supply/lib/supply
https://github.com/fastlane/fastlane/blob/3fe3a7e91527f79512bf095519604a1132bd88b3/supply/lib/supply/commands_generator.rb#L28-L40
The second link is the method that is executed on `fastlane supply`, so this can be your starting point.

Note that it _does_ try to load the `package_name` from the `Supplyfile` and use whatever is supplied on the command line though.

**Comment by HolySamosa** [comment]
Ah ha!  Thanks, @janpio!

I didn't realize that supply supported a `Supplyfile`.  I had previously checked the code for importing metadata and saw no mention of a `Supplyfile` and it wasn't mentioned in the docs, so I assumed it wasn't a supported feature.

**Comment by janpio** [comment]
Ohoh, hope I didn't lie *check* No, exists and works.
