### ISSUE TITLE
Fastfile without a fastlane directory?

### ISSUE THREAD

**Issue by HolySamosa** [fastlane/fastlane#14616]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Fastfile without a fastlane directory?

#### Question Description

I expect this has been addressed elsewhere, but I wasn't able to find any relevant issue.

It seems that this may not be possible, but I would like to execute the `fastlane` CLI configured with a Fastfile in the current working directory, rather than requiring a `fastlane` subdirectory.  If this isn't currently supported, is it a feature request that would be considered?

This is probably more background that is necessary and may be a bit confusing, but our use of fastlane is a bit different than most.  At our educational institution we use fastlane `deliver` and `supply` to manage the store submissions of IPA and .xcarchives that have been created by students and other external developers.  We have an existing folder structure which contains the IPA, Deliverfile and metadata subfolders for each app.  We would like to now add a Fastfile to this app directory to handle a more complex automation than can be supported with a Deliverfile alone.  Requiring a `fastlane` directory in order to use a `Fastfile` will require significant refactoring of our folder structure and process, and make our Git-based process for accepting metadata from the external developers less user friendly.

Thanks!

**Comment by mgrebenets** [comment]
Hi @HolySamosa 

Just curious what exactly is the directory layout in your case?
All all apps sitting in one repo (monorepo)?
Do different users checkout/use only parts of the repo related to their app and thus need a `Fastfile` in each folder?

Otherwise, you could have `fastlane/Fastfile` sitting in the repo root and since most deliver tasks are same and differ only in payload/credentials, you could do something:

`WORKING_DIR=path/to/app bundle exec fastlane deliver`
where `WORKING_DIR` is path that Fastlane scripts can read and `chdir` into it before running actions.

It could be `bundle exec fastlane deliver_app path:path/to/app`, where `deliver_app` is a thin wrapper around `deliver` that pretty much navigates to app folder and then runs fastlane actions based on that folder contents.

Not sure if that will work, the description lacks some details to understand exact workflow.

Why would creating `fastlane` folder be an issue though?
Maybe something as crazy as a symlink will work?
E.g. use `.fastlane/Fastfile` so the folder is not visible in Finder by default, but then create a symlink like `Fastfile -> .fastlane/Fastfile`?

**Comment by salmanasiddiqui** [comment]
with the details you provided, I think creating `fastlane/Fastfile` but keeping rest of your folder structure would work fine. I am not sure about `Deliverfile` but you can pass the path of `metadata` and `screenshot` directory, when calling `upload_to_app_store`. 

If `Deliverfile` is required inside `fastlane` directory, then creating symlink (as suggested by @mgrebenets) inside `fastlane` directory, pointing to `../Deliverfile` should do the trick.

**Comment by HolySamosa** [comment]
Thanks, @salmanasiddiqui and @mgrebenets.  I ended up using your suggested work-arounds, with a `fastlane/Fastfile`for each submission folder that imports a common shared `Fastfile`.  

So that developers don't have to muck w/ the `Appfile` and `Delivefile` that has been moved to the `fastlane/` directory,  these file now read values from `app_identifier.txt`,` app_version.txt` and `price_tier.txt` files to I've added to the `metadata/` directory, like so:
```
app_identifier File.read("../metadata/app_identifier.txt")
```

Closing my issue.  But I still think it could be useful for some use cases to optionally read the `Fastfile` from the current directory or from another directory as specified via the CLI.  :-)

Thanks!
