### ISSUE TITLE
Creating a new Enterprise Profile/Cert instead of renewing

### ISSUE THREAD

**Issue by jwilliams-handy** [fastlane/fastlane#14701]
### Question Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Match

No

No

#### Question Description

I'm using enterprise distribution for managing certificates and profiles of one of my apps. Right now from what I can see the only option for creating a new profile and certificate for enterprise is to use the `force` option. However, this option is not viable for my use case because it will revoke the prior certificate/profile pair which will negatively impact our business. Apple used to limit the amount of enterprise distribution profiles you could create to two but I have not run into that limitation creating them manually. Is it possible to instead of nuking the prior cert/profile pair that it would just create a new one instead so we can use match to be proactive about updating this so we don't have downtime in production?

**Comment by janpio** [comment]
I have no personal experience with this, but from reading your description it seems that "the only option for creating a new profile and certificate for enterprise is to use the `force` option" was probably added because "Apple used to limit the amount of enterprise distribution profiles you could create to two", would that thinking be correct?

Can everybody with enterprise certificates now manually create an unlimited numbers of those?

**Comment by jwilliams-handy** [comment]
Enterprise was a second-class citizen of `match` when it was first released because of security concerns so I don't think that's the reason. The property was just intended to forcibly create a new cert/profile or not. But there are no consequences when you use the force option for distributions other than enterprise.

I don't know the limit as Apple doesn't advertise it. I was able to create a few through the console with no problem though through testing.

**Comment by janpio** [comment]
Okay, then one step back:

> Right now from what I can see the only option for creating a new profile and certificate for enterprise is to use the `force` option.

Why is that? I assume you are getting some error message without it?
What commands exactly were you using? `sigh` or `match`?

**Comment by jwilliams-handy** [comment]
There’s no error message. Since one exists already and it’s valid match just pulls down the existing one. If I pass the force parameter it forces it to create a new one which is disastrous for enterprise. 

I have not tried sigh yet. I’ve only used match. Match would be ideal because we are storing the rest of our certs/profiles there now and would like to keep them in one place.

**Comment by janpio** [comment]
Ok, so the problem is that `match` assumes 1 cert/profile per app. 
This is fine for normal certificates, where revoking a current certificate doesn't matter, and you can just `nuke` everything that is currently there and start over. It is bad for enterprise certificates, where revoking means bricking apps.

All correct?

Then maybe one workaround would be to be able to tell _match_ to ignore a specific enterprise cert/profile as if it didn't exist. Then using it would just create a new one and work with that. true?

**Comment by jwilliams-handy** [comment]
Yes, that's correct.

Yes, that makes sense but sounds like it'd be a feature request more than anything. I was just hopeful this was already built.

**Comment by janpio** [comment]
match is historically _very_ careful about enterprise certs and profiles.
I don't know if this is already possible, I haven't looked at the documentation or code here yet - just tried to understand the problem and see if that understanding was correct to what your situation.
