### ISSUE TITLE
FASTLANE_EXPLICIT_OPEN_SIMULATOR

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#14721]
The two remaining uses of `FASTLANE_EXPLICIT_OPEN_SIMULATOR` look a bit like artifacts that were forgotten to be removed: https://github.com/fastlane/fastlane/search?q=FASTLANE_EXPLICIT_OPEN_SIMULATOR
Should `FASTLANE_EXPLICIT_OPEN_SIMULATOR` be documented? 
What can this be used for?

**Comment by jaleksynas** [comment]
These are pretty widespread as solutions to various internet searches.  I'd be happy to formalize the manual "pre-launch" of a simulator and get all the simulator management that occurs within the scan option cleaned up.  Generally I try to keep backward compatible functionality, but this may be a case to clear them out.

The main use case is to address a timeout error that xcode will throw when the build phase of a project takes longer than the simulator start timeout.

Example; 
`xcodebuild test` builds and then runs tests, the timer for the simulator to be ready starts at the beginning (rather than between build and test). Large projects will timeout before running any tests.

The `FASTLANE_EXPLICIT_OPEN_SIMULATOR`  flag allows a simulator to be manually started BEFORE the build (better parallelism in some ways).  When xcodebuild gets to the test phase the simulator is already started and the tests run.

Overall I would suggest this as a _formal_ option to scan `launch_first_simulator` perhaps.  This would integrate well and could "default" to `ENV['FASTLANE_EXPLICIT_OPEN_SIMULATOR']` to maintain backward function.

The only other challenge is wether or not this flag should imply the `killall Simulator` step as it does today.

**Comment by janpio** [comment]
Thanks for the explanation @jaleksynas, all a bit over my head tbh.

From looking at the code this ENV var only seems relevant for `scan`, the other use in `snapshot` is limited to Xcode8 which is probably not relevant any more. Correct?

Looking at the previous comments, this _used_ to be more present and important in the codebase, is that true?

**Comment by jaleksynas** [comment]
I believe both these statements to be true. Xcode 8 is not relevant any
longer (though complete cleanup is beyond the scope of this discussion).
As for the scan usage of the variable, launching a simulator before the
build is still a useful feature, allowing boot time to occur in parallel to
application build. I think this special ENV variable should be deprecated
for a formal scan option that properly documents and exposes itself.

**Comment by jaleksynas** [comment]
I believe the appropriate end-state for `scan` is now released, a formal option is created and the default value is that of this undocumented variable for backward compatibility.

**Comment by janpio** [comment]
via #14718
