### ISSUE TITLE
fastlane init does nothing, hangs

### ISSUE THREAD

**Issue by jeffreyjackson** [fastlane/fastlane#1476]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (fastlane -v):
Do you use bundler, rbenv or rvm?

**Comment by vpolouchkine** [comment]
How did you install fastlane? Do you use rbenv, rvm, chruby?

**Comment by dusek** [comment]
I maybe have same issue. It takes fastlane very long to start doing anything (but once it starts, it seems fine). This did not happen before I upgraded to the latest fastlane (i.e. did not happen with 1.61.0, but started after upgrading to 1.66.0).

Happens on 2 computers:
- one is using OS X 10.11.3 system ruby (2.0.0p645), with `GEM_HOME=$HOME/.gem`
- one is using rbenv, ruby 2.2.4

Both have latest software (`bundle update` ran this morning, fastlane 1.66.0).

I just discovered on the second machine (using `rbenv`) that the problem is mitigated when launching fastlane with bundler: `bundle exec fastlane ...`. When launching fastlane directly (i.e. `fastlane ...` when in the directory where the Gemfile is), the delay happens.

HTH (both those experiencing the issue, and the developers working on fastlane).

**Comment by asfalcone** [comment]
Can you give `gem cleanup` a try and see if that speeds things up for you?

**Comment by dusek** [comment]
@asfalcone thanks, it seems to do the trick (on machine 2 at least)! (fastlane now starts immediately)

**Comment by dusek** [comment]
(at least for me, not sure about the OP)

**Comment by jeffreyjackson** [comment]
yeah all good
thank you!
