### ISSUE TITLE
Frameit for Android in the future

### ISSUE THREAD

**Issue by milhauscz** [fastlane/fastlane#14796]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Is Frameit for Android planned

#### Question Description
Hi, in the company where I work we use the frameit tool for our iOS screenshots. However, Android is not supported. I found a lot of other GitHub issues in fastlane regarding this problem, all of them closed without any further information, including a [refused pull request](https://github.com/fastlane/fastlane/pull/6509/files) so I came to the conclusion there is no interest in adapting frameit for Android. That's why I started a frameit_android as a completely separate project which reuses as much of the original frameit as possible and with minimum amount of code changes I would like to achieve the Android support. However, I'd like to ask if there are any plans for supporting Android anyway so that I don't invest too much effort in this project. Thanks.

**Comment by janpio** [comment]
#6509 was refused because it was for a former version of _frameit_ and also added the functionality in a way that didn't really make sense (adding the Android devices in `deliver` which only deals with iOS uploads).

We are always open to add new functionality to fastlane and frameit, and being able to use Android device frames would be a great new feature!

Of course it has to make sense, so if you are interested in contributing to fastlane, best create a feature request issue where you describe how it should work, what exactly should be implemented, and maybe also how you would implement it. With that impulse, I am sure we can look at the suggestion and see how it would fit the big picture of fastlane and if we have any other suggestions that could improve the idea and implementation.

I would really like to see that! 🚀

**Comment by milhauscz** [comment]
Thank you for the explanation. In that case, I will first finish the separate project which will also help me familiarize with Ruby and later in July when I get back from vacation I will start the feature request issue and make suggestions how to merge it in some elegant way, especially regarding duplicate code.

**Comment by janpio** [comment]
I think it would be better to create an issue now and start a discussion how this feature could or should work in the context of fastlane - otherwise you might invest a lot of time without knowing some limitations or context that would improve your implementation.
