### ISSUE TITLE
Get push certificate with Spaceship and Store Connect API

### ISSUE THREAD

**Issue by jasperjorna** [fastlane/fastlane#14946]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Spaceship

I've updated to the latest version of Fastlane `2.126.0`. If I understand correctly the Store Connect API is supported in this version. I've set up environment variables as described in the relevant PR: https://github.com/fastlane/fastlane/pull/14888

I'm not quite sure about a few things though; will providing Fastlane with the correct environment variables be enough so that it automatically uses the new API where possible, or do I have to manually authenticate in my Fastfile and call the required endpoints?

I'm mostly trying to use the new API in order to get a push certificate, as this normally requires 2-factor authentication.

Thanks!

**Comment by joshdholtz** [comment]
@jasperjorna Heyyyyy 👋 So version `2.126.0` really only finalized the interface for the `Spaceship::ConnectAPI` module, implemented a bunch of APIs, and add support for those APIs in `pilot`.

This version, however, did not add migrate over other tools like `pem`, `cert`, and `sigh` **yet** 😇 These are next on our list of tools to tackle. We know have the infrastructure to start making those changes but the big change to make the `Spaceship::ConnectAPI` module had to happen first.

_fastlane_ will support the new App Store Connect API with the current cookie/web session like it does now so that you _shouldn't_ have to make a JWT token to make use of them. However, upcoming version of _fastlane_ will allow auth the the JWT token and will use that over the cookie/web session where it can.

There will be some _fastlane_ roadmaps that are coming out in the next few days that will provide this information and more in a better spot for everyone to read. Also, when the other tools do migrate over to the new API, there will be a more official migration docs (if any are needed) in order to take advantage of that 😊

So in the mean time there isn't much to do unless you are looking to implement some `Spaceship::ConnectAPI` directly but stay tuned for the implementation of this into other tools 😊

**Comment by jasperjorna** [comment]
Hi @joshdholtz - thanks for the information!

Ah, got ya. So the groundwork is done. :)

So the "current cookie/web" session you are referring to is not something I can use in CI with the `pem` tool as of yet? I managed to get everything working up till the point where I prompts me for a 2-factor code that I obviously cannot enter in a CI build. Saving the cookie from a manual authentication method as an environment variable in CircleCI didn't fool it unfortunately.

Thanks for the hard work, looking forward to seeing the Connect API take shape. :)

**Comment by joshdholtz** [comment]
@jasperjorna There are a _few_ ways to get around the 2FA if you are using a CI.

1) Create another account specifically for _fastlane_ if you aren't using a "Personal" account. This is the preferred method.
2) If you can't get around not using 2FA, you can store your cookie session (which last for 30 days I believe) in an environment variable on you CI (but this doesn't feel great)

I will see how soon I can get his push stuff cert done for you 😊 Maybe you can beta test it out for me if you don't mind? 😇

**Comment by jasperjorna** [comment]
@joshdholtz Hmm, I never got option 2 working with the cookie session saved in an environment variable. I'll have to try out option 1 with a personal account.

Of course, I'd be happy to beta test some new things. We've actually got a load of apps depending on Fastlane. :)

**Comment by joshdholtz** [comment]
Perfect! Stay tuned 😜

**Comment by MEnnabah** [comment]
@joshdholtz I can understand that the current version `2.126.0` is not fully utilizing the App Store Connect new APIs in modules like `cert`. No?

Our problem fully falls signing with a 2FA account, because we're not running an interactive session.

What we tried is the following workflow:
-  Generating App Specific Password and set it to `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`.
- `bundle exec fastlane test -u appstoreusername@gmail.com`.
- Still asks for a password and 6 digits code.


Quoting your comment
> There are a few ways to get around the 2FA if you are using a CI.
> 
> Create another account specifically for fastlane if you aren't using a "Personal" account. This is the preferred method.
> If you can't get around not using 2FA, you can store your cookie session (which last for 30 days I believe) in an environment variable on you CI (but this doesn't feel great)
> 

I have a question on point 2. Does this mean using Spaceship on a local machine and then use the cookie session on the CI machine?

We can NOT use the second option because of technical reasons. But we can use the first one. However, I am looking for help in:

- In our workflow, did we do it wrong? Are we missing anything?
- Are we dependent on Apple to use `cert` with App Specific Password? 
- If not, will it ever be soon?


Thank you so much for you and Fastlane, and really sorry for taking this long.
