### ISSUE TITLE
Frameit - Arabic font not rendering correctly

### ISSUE THREAD

**Issue by mtrezza** [fastlane/fastlane#14941]
Frameit does not render Arabic fonts correctly, the letters are not connected.

The Apple App Store will support Arabic localization from iOS 13 (presumably sometime this fall).  Hence the issue can be expected to grow in importance as more people will face it.

Issue #7522 was supposed to be fixed in #8131, but that fix never got merged.

**Comment by janpio** [comment]
Thanks for bringing this to our attention @mtrezza.

#8131 had problems (adding a new dependency, copying over code from another repository) which still exist, so this won't be easily solvable.

Is there maybe a better solution to this problem?

(One possible way to avoid the dependency is to only use it if an option is set, so that it can be manually installed by users. Right now https://github.com/fastlane/fastlane/pull/8131/files#diff-6ce4147575536ba03e17a0ef4f9b2a15R278 would always be used, which would effectively make this a permanent dependency.)

**Comment by mtrezza** [comment]
Don't close, open issue.

**Comment by mtrezza** [comment]
Should not be closed
