### ISSUE TITLE
Match is installing the unrelated certs if there are more certs in repo

### ISSUE THREAD

**Issue by xbchebrowb** [fastlane/fastlane#14980]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Match is installing the unrelated certs if there are more certs in repo
In my git repo I do have more than one cert.

Cert_Project1_APN.cer
Cert_Project1_APN.p12
Cert_Project2_APN.cer
Cert_Project2_APN.p12

I see below log in travis

```
DEBUG [2019-07-03 21:10:37.16]: Your certificate 'Cert_Project1_APN.cer' is valid
INFO [2019-07-03 21:10:37.16]: Installing certificate...
INFO [2019-07-03 21:10:37.16]: $ security list-keychains -d user
INFO [2019-07-03 21:10:37.19]: ▸     "/Users/travis/Library/Keychains/ios-build.keychain-db"
INFO [2019-07-03 21:10:37.19]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/travis/Library/Keychains/ios-build.keychain-db
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
INFO [2019-07-03 21:10:37.24]: $ security list-keychains -d user
INFO [2019-07-03 21:10:37.26]: ▸     "/Users/travis/Library/Keychains/ios-build.keychain-db"
DEBUG [2019-07-03 21:10:37.26]: Installing WWDR Cert: curl -f -o /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/AppleWWDRCA20190703-2965-sb3tym https://developer.apple.com/certificationauthority/AppleWWDRCA.cer && security import /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/AppleWWDRCA20190703-2965-sb3tym -k /Users/travis/Library/Keychains/ios-build.keychain-db
INFO [2019-07-03 21:10:37.45]: ▸ 1 certificate imported.
INFO [2019-07-03 21:10:37.45]: ▸ 100  1062  100  1062    0     0   9544      0 --:--:-- --:--:-- --:--:--  9567
ERROR [2019-07-03 21:10:37.77]: There are no local code signing identities found.
You can run `security find-identity -v -p codesigning ios-build.keychain` to get this output.
This Stack Overflow thread has more information: https://stackoverflow.com/q/35390072/774.
(Check in Keychain Access for an expired WWDR certificate: https://stackoverflow.com/a/35409835/774 has more info.)
INFO [2019-07-03 21:10:37.78]: $ security import /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/d20190703-2965-l4h8qk/certs/distribution/Cert_Project1_APN.cer -k '/Users/travis/Library/Keychains/ios-build.keychain-db' -P '' -T /usr/bin/codesign -T /usr/bin/security
INFO [2019-07-03 21:10:37.86]: ▸ 1 certificate imported.
INFO [2019-07-03 21:10:37.88]: Setting key partition list... (this can take a minute if there are a lot of keys installed)
INFO [2019-07-03 21:10:37.88]: $ security set-key-partition-list -S apple-tool:,apple: -k [secure] /Users/travis/Library/Keychains/ios-build.keychain-db 1> /dev/null
ERROR [2019-07-03 21:10:37.92]: security: SecItemCopyMatching: The specified item could not be found in the keychain.
INFO [2019-07-03 21:10:37.92]: $ security import /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/d20190703-2965-l4h8qk/certs/distribution/Cert_Project2_APN.p12 -k '/Users/travis/Library/Keychains/ios-build.keychain-db' -P '' -T /usr/bin/codesign -T /usr/bin/security
INFO [2019-07-03 21:10:38.03]: ▸ 1 identity imported.
INFO [2019-07-03 21:10:38.05]: Setting key partition list... (this can take a minute if there are a lot of keys installed)
INFO [2019-07-03 21:10:38.05]: $ security set-key-partition-list -S apple-tool:,apple: -k [secure] /Users/travis/Library/Keychains/ios-build.keychain-db 1> /dev/null
```

I think the bug is in 

`github/fastlane/match/lib/match/runner.rb`

In function `fetch_certificate`

line 196 should be replaced

```
private_key_path = cert_path.gsub(".cer", ".p12")
Utils.import(private_key_path, params[:keychain_name], password: params[:keychain_password])
```

**Comment by janpio** [comment]
@xbchebrowb Thanks for opening an issue. What is the actual problem in the output you posted? What is broken or wrong?

Also: We have issue templates because we need the information we ask for. In your case for example I have no idea what `Fastfile` you are actually running, or if your fastlane version is not 2 years outdated and all the other environment information we need. Please update your issue to include that information as @fastlane-bot also asked for.

**Comment by DavidBrunow** [comment]
I'm running into this same issue. The problem is that the script is not matching the name of the key to the name of the certificate. In the output above the certificate is `Cert_Project1_APN.cer` and the key is `Cert_Project2_APN.p12`.

**Comment by janpio** [comment]
I still don't understand the problem @DavidBrunow. What is the problem of additional certificates being installed if they are part of the match repository?

**Comment by DavidBrunow** [comment]
The problem is that match is choosing to install the wrong key for the certificate it is installing. In the given example, this is the current behavior:

Certificate Installed: `Cert_Project1_APN.cer`
Key Installed: `Cert_Project2_APN.p12`

The desired behavior would be:

Certificate Installed: `Cert_Project1_APN.cer`
Key Installed: `Cert_Project1_APN.p12`

The project number (or whatever other naming is being used for certificates and keys) should match between the certificate and the key.

I hope that is more clear?

**Comment by janpio** [comment]
Yes, that sounds like an actual problem.

Did you create and import the certs manually or did you use `match` to create them? Without looking for the details, I thought it was naming both certificate and key with the certificate ID on creation automatically and be able to use this to connect the dots and install the correct one.

**Comment by DavidBrunow** [comment]
I created and imported the certs manually to match the naming convention of the certs created by `match` -- the name of the cert matches the name of the private key. 

Above, @xbchebrowb found a place that might need to be changed to use the same name for the private key as the certificate.

> I think the bug is in
> 
> github/fastlane/match/lib/match/runner.rb
> 
> In function fetch_certificate
> 
> line 196 should be replaced
> 
> private_key_path = cert_path.gsub(".cer", ".p12")
> Utils.import(private_key_path, params[:keychain_name], password: params[:keychain_password])

I can make a PR for this but don't have much time to work on it at the moment with iOS 13 coming soon.

**Comment by janpio** [comment]
The line number doesn't match, but I assume this refers to this:
https://github.com/fastlane/fastlane/blob/d7e02e48e74c754d9d9194025815324d7380a479/match/lib/match/runner.rb#L171
Currently it uses the last key it touched, but it obviously makes sense to install the matching one - correct?

**Comment by janpio** [comment]
Oh, now I think I understand the problem causing this as well! `match` probably is just not set up to handle more than certificate per match repo structure, which usually only happens when you want to have stuff from more than one team in the repo. The instructions for that case are here: https://docs.fastlane.tools/actions/match/#multiple-teams Another pointer that it was designed for one set of certificates is that it explicitly takes about one certificate, and multiple provisioning profiles: https://docs.fastlane.tools/actions/match/#handle-multiple-apps-per-developerdistribution-certificate

I am not actually sure the suggested change above will really fix the problem because of that. The certificate it choose is also just the _last_ one, which may or may not be the one you want to use: https://github.com/fastlane/fastlane/blob/d7e02e48e74c754d9d9194025815324d7380a479/match/lib/match/runner.rb#L146 Correct?

**Comment by DavidBrunow** [comment]
I think you're right. My use case was to support the new Apple Development and Distribution certificates so that they can be used for iOS 13 builds (included macCatalyst) while also still supporting the current iOS Development and Distribution certificates. It sounds like that is not a viable path forward and I'll just use a different branch in the code signing repo to hold the new variety.

Not sure if this resolves the original poster's concerns, but it does mine. Thanks!

**Comment by janpio** [comment]
Let's see waht @xbchebrowb thinks.

The `.last` stuff is a code smell anyway, as it can lead to undefined behavior like this. Maybe it would be enough to add a warning (and docs link) when there are more than 1 set of certificates per repo branch.

But on the other hand, getting rid of the `.last` stuff wouldn't be bad in general.

**Comment by xbchebrowb** [comment]
This is a bug in the code.
The issue will arise  only If there are more than one certs in the repo.

In https://github.com/fastlane/fastlane/blob/master/match/lib/match/runner.rb

line 131 is a function.

 def fetch_certificate(params: nil, working_directory: nil)

In this function, first we install the cert then install the key.

at line 171 key is installed.

`Utils.import(keys.last, params[:keychain_name], password: params[:keychain_password])`

if you see in the above line `keys.last` might be different key than the cert you installed, if there are more than one cert/key in the directory.
