### ISSUE TITLE
Upload android app bundle instead of APK to the playstore

### ISSUE THREAD

**Issue by rnkhouse** [fastlane/fastlane#15053]
I have this configuration to upload `.apk` to the Playstore which is working fine.

    lane :playstore do
      gradle(task: "clean")
      gradle(
        task: 'assemble',
        build_type: 'Release',
        properties: {
          "android.injected.signing.store.file" => "Keystore.jks",
          "android.injected.signing.store.password" => "abc",
          "android.injected.signing.key.alias" => "abc",
          "android.injected.signing.key.password" => "abc"
        }
      )
      upload_to_play_store(track: 'alpha')
    end

But, instead of `apk` file I want to upload `.aab` app bundle. How can I do it?
I checked in `app/build/outputs` directory and there is no `aab` directory generated.

**Comment by janpio** [comment]
You can't right now, as the API fastlane supply/upload_to_play_store is using doesn't support bundles. This will get fixed when https://github.com/fastlane/fastlane/issues/14573 is tackled.

To actually get the `.aab` file you have to adapt the `gradle` call, from `task: 'assemble',` to `task: 'bundle', I think.

**Comment by FinnGu** [comment]
> To actually get the .aab file you have to adapt the gradle call, from task: 'assemble', to `task: 'bundle', I think.

That's exactly all that is needed for it to work. I have not yet uploaded to the alpha track, but my internal test track works just fine.

```
gradle(task: 'bundle', flavor: 'myflavor', build_type: 'Release', project_dir: 'android/')
supply(
      track: 'internal', 
      package_name:'com.example.myflavor',
      metadata_path: './fastlane/metadata/android/myflavor',
      json_key: './fastlane/mykey.json'
    )
```

**Comment by janpio** [comment]
Oh, that would be interesting. Then this would just be a doc update. Thanks @FinnGu - let me know if you tried it @rnkhouse

**Comment by FinnGu** [comment]
There is already some documentation on supply's side of things to be found [here](https://docs.fastlane.tools/actions/supply/#uploading-an-aab).

The [gradle documentation](https://docs.fastlane.tools/actions/gradle/) however could be updated to reflect this. Currently it mentions the shared values `SharedValues::GRADLE_AAB_OUTPUT_PATH` and `SharedValues::GRADLE_ALL_AAB_OUTPUT_PATHS`, but not the task `bundle` to actually create an AAB instead of an APK.

**Comment by janpio** [comment]
Do you want to create a quick PR adding a `task: bundle` exmaple to `self.example_code`? I think on position 2 or after the later after the "sign and zipalign" one would be a good place. 

(When you're at it, you can also change "If you need to pass sensitive information through the `gradle` action, and don't want the generated command to be printed before it is run, you can suppress that:" and "Delete the build directory and generated APKs" from ruby comments to proper text similar to "To pass any other CLI flags to gradle use:" to clean this page up a bit)

**Comment by FinnGu** [comment]
I just noticed that the documentation moved to its own repository. I don't have time right now to get mkdocs running, sorry.

**Comment by janpio** [comment]
Not needed at all fortunately, just edit the file at https://github.com/fastlane/fastlane/edit/master/fastlane/lib/fastlane/actions/gradle.rb and create the PR - all the rest is done automatically.

**Comment by FinnGu** [comment]
Looks like I was on the right track after all, this morning 🙈

I have made the changes you suggested in [PR 15058](https://github.com/fastlane/fastlane/pull/15058).

However I am not so sure about moving the texts outside of the code sections. The docs look better that way, but this kind of works against having `self.example_code` as an array that automatically wraps each example as formatted ruby code. Also I could not find any other action where there was plain text above the code examples. And lastly, using this method it is not possible to have plain text before the first example.

I think we should stick to having text inside code examples as comments or otherwise the existing structure of `self.example_code` should be reworked so that it is the same for all actions.

**Comment by rnkhouse** [comment]
So, I changed it with `bundle`:

    lane :playstore do
      gradle(task: "clean")
      gradle(
        task: 'bundle',
        build_type: 'Release',
        properties: {
          "android.injected.signing.store.file" => "Keystore.jks",
          "android.injected.signing.store.password" => "abc",
          "android.injected.signing.key.alias" => "abc",
          "android.injected.signing.key.password" => "abc"
        }
      )
      upload_to_play_store(track: 'alpha')
    end

Build is successful. But, there is no .aab files?

**Comment by FinnGu** [comment]
> Build is successful. But, there is no .aab files?

Do you mean there is no .aab file generated? Or do you mean that an old .apk file got uploaded?

In your inital post you mentioned that the directory `app/build/outputs/aab` does not exist. Try looking for `app/build/outputs/bundle` instead. That is the default location, I think.

**Comment by rnkhouse** [comment]
@FinnGu 
`app/build/outputs/` directory is empty.

**Comment by FinnGu** [comment]
Fastlane executes this gradle command for the code I provided: `MyProject/android/gradlew bundleMyFlavorRelease -p android/`.

Does your command look similar? You could try executing that gradle command without fastlane to check if the command itself is missing some parameters. In my case, I had to add the `-p` parameter to specify the project directory, because the default of `./` was not working for my react-native configuration. The `app/build/outputs` directory is also relative to the project directory.

**Comment by rnkhouse** [comment]
@FinnGu 
I think I found the mistake. I didn't apply this command `fastlane supply init`
Now, it's working.

**Comment by FinnGu** [comment]
I'm glad you were able to fix it :)

@janpio Can we close this issue? The main question is resolved and further discussion about the documentation can continue in PR #15058
