### ISSUE TITLE
Proper way for deploying fastlane based cloud build and deploy service

### ISSUE THREAD

**Issue by bhavincb** [fastlane/fastlane#15050]
### Question Checklist

- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Fastlane on cloud server with IOS certificates generate and app store deploy

#### Question Description

we wanted to build cloud based service where user can send project zip file and fastlane will build, sign and deploy for both platforms. but we are lost when it comes to way for converting whole project to cloud service. can you please tell us best practice for deploying fastlane to cloud?

**Comment by max-ott** [comment]
Hi @bhavincb, this is an open source project and not really the right place to ask how to make a business/service out of it. There are a lot of guides that can help you with the `fastlane` setup over at https://docs.fastlane.tools/ and if you have any specific code questions/problems, we're more than happy to help. 

Otherwise I recommend looking for a freelancer/developer with extensive `fastlane/spaceship` background, who can help you with your task, but your question goes beyond the scope of normal issues.
