### ISSUE TITLE
Fastlane for "Individual" iTunes Account

### ISSUE THREAD

**Issue by pujabigstep** [fastlane/fastlane#15123]
### Question Checklist

- [ ] Updated fastlane to the latest version: Yes
- [ ] I read the [Contribution Guidelines]: 
 Yes(https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description
 How to use Fastlane for the Individual Type iTunes Account, as in this case, we do not have access to provide the permission for "accessing certificates and provisioning profiles"

**Comment by janpio** [comment]
Ping @max-ott

**Comment by max-ott** [comment]
@pujabigstep Not sure what the real question is here. Depending on your access level, you can use different `fastlane/spaceship` functions. If you do not have access to profiles & certificates, you cannot of course generate any profiles. You can manage most things on App Store Connect, though.

Please specify the functionality, otherwise it's really hard to help/answer!
