### ISSUE TITLE
Environment for Matchfile 

### ISSUE THREAD

**Issue by sssbohdan** [fastlane/fastlane#15155]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Is that possible to use environment variables for `Matchfile`?

#### Question Description
I run comman `fastlane match --env Name` and getting:

```
[✔] 🚀 
invalid option: --env
```
But when I change `ENV` with actual values and run `fastlane match` everything goes well.

**Matchfile:**
```
git_url ENV['GIT_URL']
app_identifier ENV['ALL_BUNDLE_IDENTIFIERS']
username ENV['USERNAME']
```

**.env.Name:**
```
GIT_URL = "rep url"
USERNAME = "username@gmail.com"
ALL_BUNDLE_IDENTIFIERS = ["first", "second"]
```

**Comment by janpio** [comment]
It's very possible that `--env` is only implemented for lanes and the main `fastlane` command, not `fastlane match`, `fastlane cert` etc.: https://docs.fastlane.tools/advanced/other/#environment-variables

That means you could probably work around that by using the `match` action instead of the `fastlane match` CLI command (if that has all the functionality you want to use).
