### ISSUE TITLE
two_step_or_factor_client.r

### ISSUE THREAD

**Issue by wangduan023** [fastlane/fastlane#15162]
### Question Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

#### Question Description

 two_step_or_factor_client ask fun , how to wait web api return,not console input

**Comment by janpio** [comment]
That is currently not something that is implemented. You can of course try to find a way to pipe some input to stdin, but I am not sure about the timing here. The other way would be to "hack" fastlane to call an API instead of reading from a prompt. A fastlane plugin could pretty easily "overwrite" (monkey patch)  the method that asks for the input and call an API instead - ruby is pretty flexible here.
