### ISSUE TITLE
plugin_scores: Fastlane docs parse only the last line of multiline action Description

### ISSUE THREAD

**Issue by dotdoom** [fastlane/fastlane#15201]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

On docs.fastlane.tools, action description is only the last line when multi-line Ruby string is used:

https://github.com/fastlane/docs/blob/93169702a4f3c090824c08747f3b7050f3094ee1/plugin_scores_cache.yml#L4560

vs

https://github.com/dotdoom/fastlane-plugin-flutter/blob/23d517049d11da95563d35f76bfd44a64eb54eeb/lib/fastlane/plugin/flutter/actions/flutter_generate_action.rb#L36-L39

**Comment by janpio** [comment]
Turns out although this is a docs problem, the code for this actually _does_ like in `fastlane/fastlane` as a special action: https://github.com/fastlane/fastlane/blob/master/fastlane/actions/plugin_scores.rb

**Comment by janpio** [comment]
The problem is probably inside this somewhere: https://github.com/fastlane/fastlane/blob/master/fastlane/helper/plugin_scores_helper.rb

**Comment by getaaron** [comment]
The action is parsed into a file:

```ruby
              actions = Dir["**/actions/*.rb"].map do |action_file|
                FastlaneActionFileParser.new.parse_file(action_file)
              end
```

The `FastlaneActionFileParser` iterates each line. It basically looks for a string, and places it in `last_string_statement` until `is_end?` returns `true`.

The parser even implicitly acknowledges multi-line strings won't work with the comment:

```ruby
# All the ways ruby can represent single-line strings
```

So we either need to:

- Add multiline string support to `FastlaneActionFileParser`, or
- Disallow multiline strings in fastlane actions (maybe some kind of spec in https://github.com/fastlane/fastlane/tree/master/fastlane/spec/plugins_specs?)

**Comment by getaaron** [comment]
Also as far as I can tell, `FastlaneActionFileParser` isn't under test :(

**Comment by mollyIV** [comment]
Hey guys 👋 

@getaaron thank you so much for your help! ❤️ 

I've spent some time on investigation of this issue and would like to share my findings:

1. PR with the fix is ready for review 

I created the PR with the fix, although @dotdoom you will need to update the description of your plugin. More details in the PR's description. 

2. Workaround

As a quick workaround, you could write a description in a single line. A long, single line description renders pretty well on [`Available Plugins`](https://docs.fastlane.tools/plugins/available-plugins/) site, i.e. `airwatch_workspaceone`

![image](https://user-images.githubusercontent.com/10795657/63411820-a2ab0980-c3f6-11e9-94ca-c8f50bced17f.png)

🙇

**Comment by dotdoom** [comment]
Thank you, I made this [change](https://github.com/dotdoom/fastlane-plugin-flutter/commit/63ede188f18ea6f7a795dbf8dda71c21297273b7) when I discovered about this issue, but looks like it hasn't been picked up yet:

https://docs.fastlane.tools/plugins/available-plugins/#flutter

Thanks @mollyIV for sending a PR so quickly and @janpio for CCing me on it.

**Comment by janpio** [comment]
I think update of this is only done on release of fastlane.
