### ISSUE TITLE
Feature Request : Webex Teams and Microsoft teams Webhooks implementation

### ISSUE THREAD

**Issue by hrushie** [fastlane/fastlane#15234]
#### Motivation Behind Feature
 I have been trying to add communication bot from jenkins to notify webex teams and Microsoft teams for build success and url of build, either it is hockey or appcenter or artifactory

#### Feature Description
Create notification feature like slack regarding the build status in Webex teams and Microsoft teams 

There will be no drawbacks as it will be the new feature plugin

**Comment by janpio** [comment]
That sounds like a pretty good candidate for a fastlane plugin!

That way the actual logic could be implemented and tested without any commitment needed from the core contributors, and if it turns out to be super popular and used very often it can maybe still be integrated to the core action further down the line.

You can read more about creating a plugin here: https://docs.fastlane.tools/plugins/create-plugin/
