### ISSUE TITLE
Fastlane 2.124.0 is still trying to use signet 0.12.0 on ruby 2.3

### ISSUE THREAD

**Issue by Nonnus** [fastlane/fastlane#15497]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Updated Fastlane to version 2.124.0, which is supposed to `[fastlane] pin signet to 0.11 if Ruby 2.3 or less` but it looks like it is still trying to use signet 0.12.0 on ruby 2.3:

<img width="747" alt="Screenshot 2019-10-15 at 05 27 39" src="https://user-images.githubusercontent.com/54864/66797892-874b0f00-ef0c-11e9-931d-f6845a5e9c5e.png">

##### Command executed
`bundle install`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by janpio** [comment]
cc @joshdholtz

**Comment by Nonnus** [comment]
After reading the info on https://github.com/fastlane/fastlane/pull/15483 I tried running `bundle update` again and, once again, it installed `signet 0.12`, here is the output:

```
> ruby -v
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18]

> bundle update
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.......
Using CFPropertyList 3.0.1
Using public_suffix 2.0.5
Using addressable 2.7.0
Using atomos 0.1.3
Using babosa 1.0.3
Using bundler 2.0.1
Using claide 1.0.3
Using colored 1.2
Using colored2 3.1.2
Using colorize 0.8.1
Using highline 1.7.10
Using commander-fastlane 4.4.6
Using declarative 0.0.10
Using declarative-option 0.1.0
Using digest-crc 0.4.1
Using unf_ext 0.0.7.6
Using unf 0.1.4
Using domain_name 0.5.20190701
Using dotenv 2.7.5
Using emoji_regex 1.0.1
Using excon 0.67.0
Using multipart-post 2.0.0
Using faraday 0.17.0
Using http-cookie 1.0.3
Using faraday-cookie_jar 0.0.6
Using faraday_middleware 0.13.1
Using fastimage 2.1.7
Using gh_inspector 1.1.3
Using jwt 2.1.0
Using memoist 0.16.0
Fetching multi_json 1.14.1 (was 1.14.0)
Installing multi_json 1.14.1 (was 1.14.0)
Using os 1.0.1
**Using signet 0.12.0 (was 0.11.0)**
Using googleauth 0.6.7
Using httpclient 2.8.3
Using mime-types-data 3.2019.1009
Using mime-types 3.3
Using uber 0.1.0
Using representable 3.0.4
Using retriable 3.1.2
Using google-api-client 0.23.9
Using google-cloud-env 1.2.1
Fetching google-cloud-core 1.3.2 (was 1.3.1)
Installing google-cloud-core 1.3.2 (was 1.3.1)
Using google-cloud-storage 1.16.0
Using json 2.2.0
Using mini_magick 4.9.5
Using multi_xml 0.6.0
Using plist 3.5.0
Using rubyzip 1.3.0
Using security 0.1.3
Using naturally 2.2.0
Using simctl 1.6.6
Using slack-notifier 2.3.2
Using terminal-notifier 2.0.0
Using unicode-display_width 1.6.0
Using terminal-table 1.8.0
Using tty-screen 0.7.0
Using tty-cursor 0.7.0
Using tty-spinner 0.9.1
Using word_wrap 1.0.0
Using nanaimo 0.2.6
Fetching xcodeproj 1.13.0 (was 1.12.0)
Installing xcodeproj 1.13.0 (was 1.12.0)
Using rouge 2.0.7
Using xcpretty 0.3.0
Using xcpretty-travis-formatter 1.0.0
**Using fastlane 2.134.0**
Using xctest_list 1.1.8
Fetching fastlane-plugin-test_center 3.8.7 (was 3.8.6)
Installing fastlane-plugin-test_center 3.8.7 (was 3.8.6)
Bundle updated!
```

**Comment by Nonnus** [comment]
please disregard this issue, while testing I found out I am running `ruby 2.6.1p33 `, hence why it was updating signet to `0.12`

**Comment by Gabriel-diez** [comment]
The issue is still present.
I am using ruby 2.3.8 on ubuntu.

`> ruby -v
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-linux]
`

output

`> bundle install
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies....................................
Using CFPropertyList 3.0.1
Using public_suffix 2.0.5
Using addressable 2.7.0
Using atomos 0.1.3
Using babosa 1.0.3
Using bundler 2.0.2
Using claide 1.0.3
Using colored 1.2
Using colored2 3.1.2
Using highline 1.7.10
Using commander-fastlane 4.4.6
Using declarative 0.0.10
Using declarative-option 0.1.0
Using digest-crc 0.4.1
Using unf_ext 0.0.7.6
Using unf 0.1.4
Using domain_name 0.5.20190701
Using dotenv 2.7.5
Using emoji_regex 1.0.1
Using excon 0.67.0
Using multipart-post 2.0.0
Using faraday 0.17.0
Using http-cookie 1.0.3
Using faraday-cookie_jar 0.0.6
Using faraday_middleware 0.13.1
Using fastimage 2.1.7
Using gh_inspector 1.1.3
Using jwt 2.1.0
Using memoist 0.16.0
Using multi_json 1.14.1
Using os 1.0.1
Fetching signet 0.12.0
Installing signet 0.12.0
Gem::InstallError: signet requires Ruby version >= 2.4.0.
An error occurred while installing signet (0.12.0), and Bundler cannot continue.
Make sure that `gem install signet -v '0.12.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  fastlane was resolved to 2.134.0, which depends on
    google-cloud-storage was resolved to 1.16.0, which depends on
      google-api-client was resolved to 0.23.9, which depends on
        googleauth was resolved to 0.6.7, which depends on
          signet
`

**Comment by shepting** [comment]
Confirming this is the case for Ruby 2.3.1 on macOS as well.
```ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin17]```

```bundle update fastlane
Fetching signet 0.12.0 (was 0.11.0)
Installing signet 0.12.0 (was 0.11.0)
Gem::InstallError: signet requires Ruby version >= 2.4.0.
An error occurred while installing signet (0.12.0), and Bundler cannot continue.
Make sure that `gem install signet -v '0.12.0' --source 'https://gems.d.musta.ch/'` succeeds before bundling.

In Gemfile:
  fastlane was resolved to 2.134.0, which depends on
    google-cloud-storage was resolved to 1.16.0, which depends on
      google-api-client was resolved to 0.23.9, which depends on
        googleauth was resolved to 0.6.7, which depends on
          signet```

**Comment by janpio** [comment]
See https://github.com/fastlane/fastlane/issues/15522 for an open issue about this

**Comment by dazuma** [comment]
@Gabriel-diez @shepting Just do `bundle update` (not `bundle install` or `bundle update fastlane`). This will ensure _all_ gems in your bundle are updated to versions that are compatible with your version of Ruby.
