### ISSUE TITLE
When installing via homebrew it downloads version 2.28.3  instead of the latest version

### ISSUE THREAD

**Issue by Daniel-Griffiths** [fastlane/fastlane#15496]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When installing fastlane via homebrew using `brew cask install fastlane` it always downloads version `2.28.3 `

Installing via ruby gems using the command `sudo gem install fastlane -NV` it correctly installs the latest version.

##### Command executed

```
brew cask install fastlane
```

My OS is Mac OS Catalina

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15                                       |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.15 (19A583)                     |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2019-10-10**
</details>

**Comment by regularberry** [comment]
Thanks for this. I couldn't figure out why my fresh install of fastlane was failing with the error: [!] undefined method `each' for nil:NilClass

But installing from ruby gems instead of brew made it work :+1:

**Comment by janpio** [comment]
cc @joshdholtz

**Comment by garylai** [comment]
I think it is because one of the dependencies fails to update:
```
ERROR:  Error installing fastlane:
	signet requires Ruby version >= 2.4.0.
```
The brew package seems to be still using ruby 2.2?

**Comment by joypatel04** [comment]
@joshdholtz @janpio Any update on this issue?

**Comment by joshdholtz** [comment]
Looking into! Will update when I have more info

**Comment by nickrnet** [comment]
@joshdholtz Here's what I'm getting on my up-to-date Mojave machine.
[brew-cask-install-fastlane.txt](https://github.com/fastlane/fastlane/files/3805132/brew-cask-install-fastlane.txt)

**Comment by algera** [comment]
Here is what I am using as a temporary workaround while this Homebrew installation issue is being considered.

Note: I could not install via gems b/c of the organization of Xcode 11 w/ Mojave.  In order to correct that setup and get on Fastlane 2.134.0.  If you are using a later version of MacOS, consider updating the command line tools executable package command.
 
## Trash existing homebrew installation
`brew cask uninstall fastlane`

## Reinstall header files on Mac
```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
sudo xcodebuild -license accept
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
```

## Now update Ruby to v2.6.5 as Ruby v2.3 (default on Mojave) will not work with Fastlane

```
brew update
brew install ruby-build
brew install rbenv
rbenv install 2.6.5
rbenv global 2.6.5
export PATH="$HOME/.rbenv/shims:$PATH"
sudo gem install fastlane -NV
```

**Comment by Katsz** [comment]
Due to enormous amount of people used to install all the things via homebrew maybe we should just prune all fastlane versions <= 2.28 from it?
I don't think there is a single person in the wild that uses 2.28 consciously.

**Comment by Larusso** [comment]
@Katsz How do you want to do that. It's an unversioned cask. It downloads a zip file from this unversioned URL `https://fastlane.tools/fastlane.zip`

**Comment by joshdholtz** [comment]
Heyyyy 👋  I'm currently working on a PR for this! 

### Problem
- Packaged _fastlane_ used Ruby 2.2 which is too old for some _fastlane_ dependencies and causes installation issues leading to packaged _fastlane_ installed version `2.28.3`
- Packaged _fastlane_ can also only be built/repackaged on OSX 10.1

### Solution
- Build new packaged _fastlane_ with Ruby 2.4 on Catalina
- Ruby will also be built on the during the installation process (if not already installed) 
  - This makes packaged _fastlane_ smaller but the first install longer

We are still undergoing some testing but my goal is to get it released next week 🤞 If anybody is willing to help test this please let me know!

**Comment by Katsz** [comment]
@Larusso my bad, wasn't aware fastlane is `cask`'ed

**Comment by Larusso** [comment]
@joshdholtz I tried it out and it failed for me. With the changes you propose you should also think about moving the whole thing into a brew formular. Because installing ruby etc during installation time is not really what brew cask is for.

**Comment by joshdholtz** [comment]
@Larusso I'll look into! I'm not a fan of my changes I made with install Ruby but it "works" 😬 I'll look into this 😊

**Comment by joypatel04** [comment]
@joshdholtz  Will your changes work on macOS Mojave? 

I am still running on Mojave to avoid issues   (If there is any) running with React-native.

**Comment by joshdholtz** [comment]
Yup yup! It will 😊 I have both a Catalina and Mojave machine that I’m testing this on

**Comment by nickrnet** [comment]
Any updates on this? I'm needing to get 2.136 or greater because of https://github.com/fastlane/fastlane/issues/14573

**Comment by chrisvire** [comment]
Our [product](https://software.sil.org/scriptureappbuilder) uses fastlane and depends on installing fastlane via https://fastlane.tools/fastlane.zip.  Will that distribution mechanism be updated so that it can be updated to latest fastlane instead of being stuck on 2.28.3?  Just an FYI that this isn't limited to homebrew.

**Comment by janpio** [comment]
Thanks for this context @chrisvire, @joshdholtz is working on fixing this.

**Comment by Larusso** [comment]
For anyone not able to wait for the official fix. I added some fixes/customization to the pull request from @joshdholtz. Some of the changes are tailored for my needs and preferences.
You can find the diff here:
https://github.com/wooga/packaged-fastlane/commit/6e591d7fcecf9a4e2e825a9a3d8961f35858e5fc

In short:
- removed all prompts (I have no user input at install time)
- update the shim script so I can symlink the file to `/usr/local/bin` (I did this for my custom cask file)
- removed the brew openssl installation since ruby-build will download the correct openssl version (I have no idea why some random version from brew is the preferred solution?)
- changed the install path to install to the current dir (I did this for my custom cask file and I don't like programs in the home directory)

I adjusted my custom cask file which can be found here:
https://github.com/wooga/homebrew-tools/blob/master/Casks/fastlane.rb

I'm running with this fix the last couple of days and everything works so far for me.
I hope this might be of help for anyone.

**Comment by joshdholtz** [comment]
@Larusso That is great! Do you mind making a PR into my PR for that? That would be so 💯

**Comment by Larusso** [comment]
@joshdholtz I'll take it without my custom modifications with the install path?

**Comment by joshdholtz** [comment]
@joshdholtz Yeah yeah, sorry! I should have mentioned that. Not enough coffee yet 🙃 I appreciate all your testing on this and want to make sure that you get credit for your changes/time as well. I got sidetracked with some other fixes that needed to get made but this is now number 1 priority

**Comment by joshdholtz** [comment]
Hey, everyone! This is all fixed now 😊 

## So...
1. The `brew cask install fastlane` is no longer a thing
2. The homebrew install of fastlane has been migrated to a formula which means:
    - Uninstall cask `brew cask uninstall fastlane`
    - Remove any fastlane cask stuff from you path (.bash_profile, .bashrc, .zshrc, etc)
3. Run `brew install fastlane`
    - This depends on homebrew version of openssl and ruby 2.5 so things should be 💯 and install quickly
    - This new method won't autoupdate (which was a bit confusing, IMO) so you will need to run `brew upgrade fastlane` when new versions drop

This is ready to go as of this morning 😊  There will be official announcements, docs, and migration notes coming out later 💪 

Sorry about this taking so long 😇 It was quite an adventure.

Ping me if anybody has any questions!

**Comment by chrisvire** [comment]
Does this also fix installing using using https://fastlane.tools/fastlane.zip?

Our software uses fastlane and downloads from that url.

**Comment by joshdholtz** [comment]
@chrisvire That zip file is actually going to be removed here soon 😇 That was the cause of all the problem because it was being bundled with an old version of Ruby and the way that that was designed does not work well with newer versions of Ruby. I'm not exactly sure how your systems work but I would recommend using `brew install fastlane` or pulling down the fastlane from source and running `gem build fastlane.gemspec` and installing the gem that that builds.

**Comment by chrisvire** [comment]
We can’t require a dependency on homebrew. We need the zip distribution that includes ruby.

**Comment by patelhiren** [comment]
@joshdholtz Running `brew install fastlane` installed the latest available version. However running a lane that uses the `gym` command was failing. Turned out `xcpretty` was not installed via the brew command. I manually installed via `sudo gem install xcpretty`. The error went away after that. Anyway to automate the xcpretty install when installed via homebrew?
