### ISSUE TITLE
How to enable Sign in with Apple?

### ISSUE THREAD

**Issue by tmaly1980** [fastlane/fastlane#15707]
#### Motivation Behind Feature
To automate enabling Sign in with Apple via fastlane

#### Feature Description
XCode 11 has a "Sign In with Apple" feature, and under the App ID configuration on developer.apple.com, there is a way to enable this feature and set the app as a Primary App ID or group with another Primary App ID. Can fastlane support this?

I'm currently on 2.137.0 and there doesn't seem to be any code that explicitly supports this. It seems like Spaceship would need to be updated to support it as well, but I simply don't know how to do it myself.

**Comment by DADDYBOZO** [comment]
Hi there,

We are looking forward to have this feature in Fastlane. Do you plan to develop it soon?

**Comment by gabegolla** [comment]
It would be nice to have this feature soon especially because Apple is starting to rejected apps based on missing Sign in with Apple:

"Additionally, we continue to find that your app uses a third-party login service but does not also offer Sign in with Apple.
To resolve this issue, it would be appropriate to offer Sign in with Apple as an equivalent login option. Sign in with Apple is required unless your app is entirely dependent upon integration with the third-party login.
We look forward to reviewing your revised app.
Best Regards,
App Store Review"

**Comment by alessioarsuffi** [comment]
I don't know if this helps, but enabling Sign In with Apple in https://developer.apple.com/account/resources and using 
`fastlane match --force`
solved my problem, of course is not completely automated by fastlane, but that works right now :)
