### ISSUE TITLE
upload_symbols_to_crashlytics fails Shell command exited with exit status 8 instead of 0.

### ISSUE THREAD

**Issue by claudioviola** [fastlane/fastlane#15736]
### Question Checklist

- [X ] Updated fastlane to the latest version
- [ X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Updated to fastlane-2.137.0
I've trying to upload symbols to **Firebase Crashlytics** with this command

`upload_symbols_to_crashlytics` fails and show this error
`Shell command exited with exit status 8 instead of 0.`

This is the result
![Schermata 2019-11-28 alle 16 28 33](https://user-images.githubusercontent.com/6689594/69818044-3c573380-11fc-11ea-90d1-17e8d03cf614.png)

I saw other issues on this problem but any one helped me to fix it

#### Question Description
This is my code

```
          lane :refresh_dsyms do |options|

		download_dsyms(
			app_identifier: 'my.packageapp.name',
			version: 'latest'
		)

		upload_symbols_to_crashlytics(
			dsym_paths: lane_context[SharedValues::DSYM_PATHS],
			gsp_path:"../env/dev/ios/GoogleService-Info.plist",
		)

		clean_build_artifacts()
    end

**Comment by ricmatsui** [comment]
Ran into the same issue. Fastlane is not reporting the full error message.

@claudioviola Try downloading a .dSYM and then manually running `ios/Pods/Fabric/upload-symbols -gsp ../env/dev/ios/GoogleService-Info.plist -p ios $PATH_TO_DSYM`. For me, the full error message was:
```
error: could not complete submission of dSYM at ******.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=4 "This version of OSX is not able to perform the necessary dSYM transformations." UserInfo={NSLocalizedFailureReason=This version of OSX is not able to perform the necessary dSYM transformations.}
```
This is probably because I am running Catalina now. I upgraded Crashlytics 3.12.0 -> 3.14.0 and Fabric 1.9.0 -> 1.10.2, `pod update Crashlytics`, and I was able to upload with fastlane using `upload_symbols_to_crashlytics`.

It would be better if Fastlane reported the full error message from Fabric/upload-symbols instead of only the exit code.

**Comment by twelve17** [comment]
@ricmatsui Thanks a ton for that very useful information.  In my case, `Fabric` and `Crashlytics` dependencies are hardcoded to the older versions in the [current podfile of the react-native-firebase/crashlytics package|https://github.com/invertase/react-native-firebase/blob/547d0a2d74a68808b29063f9b3aa3e1ac38551fc/packages/crashlytics/RNFBCrashlytics.podspec#L13].  However, I can override those dependencies in my `Podfile` [like this|https://invertase.io/oss/react-native-firebase/guides/overriding-native-sdk-versions#ios]:

```
  # Override Fabric SDK Version
  $FabricSDKVersion = '1.10.2'

  # Override Crashlytics SDK Version
  $CrashlyticsSDKVersion = '3.14.0'
```
