### ISSUE TITLE
Creating an Apple Account without 2FA

### ISSUE THREAD

**Issue by mobdevross** [fastlane/fastlane#16545]
### Question Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject

Apple account creation without 2FA

#### Question Description

Hi, I’m following guidance on trying to run Fastlane on CI but can’t work out how to create an Apple account for use with the Apple developer program without 2FA. I’ve tried creating an account with and without an invitation to the developer team. Does anyone know if Apple are now enforcing 2FA on all accounts?

**Comment by max-ott** [comment]
No, you can still invite Apple IDs to your team (even as an admin role) without 2FA enable. The only caveat is that you will need a business / organization account for this to work. Personal developer accounts cannot give access to the developer center.

**Comment by markreynoso** [comment]
I have created accounts both by invitation from multiple organizational accounts as well as simply creating one from https://appleid.apple.com/account#!&page=create. I have tried them numerous times with the same result. Since the end of 5/2020 they have all required 2FA. There is not an explicit statement during the creation of the ID that 2FA will be enables, but it is automatically on every time.

**Comment by joshdholtz** [comment]
@mobdevross @marcomorain Thanks for reporting this! I was able to create one without 2FA during in the middle of May but I have not tried since. I will also try today to verify but I trust the reports you are given 😊 

I will then update the docs and try to figure out if there are ways we can work around this.

**Comment by superpeteblaze** [comment]
Same issue here. It looks like creating an Apple account now requires verification via phone. I assumed this was just a one time verification, but it appears it auto-enables 2FA.

**Comment by hollanderbart** [comment]
I got the same issue. You're not able to create new AppleIDs without 2FA auto-enabled. And there's no way to disable 2FA after it's enabled. 
What a mess :-(

**Comment by max-ott** [comment]
It's no longer possible to create Apple IDs without 2FA. @joshdholtz is working hard to enable authentication across the board with the new App Store Connect API, which allows authentication through the key etc.
