### ISSUE TITLE
Deliver doesn't delete old screenshots

### ISSUE THREAD

**Issue by bb-git** [fastlane/fastlane#17424]
The latest version of fastlane doesn't delete old screenshots. The html file for verification looks fine, but then the message 
```
Too many screenshots found for device 'APP_IPHONE_55'
Too many screenshots found for device 'APP_IPHONE_65'
```
appears for every language.
I'm using fastlane 2.162.0

**Comment by rogerluan** [comment]
Hey @bb-git 👋 

Could you follow the [right issue template](https://raw.githubusercontent.com/fastlane/fastlane/master/.github/ISSUE_TEMPLATE/REGRESSION.md) to submit useful information? This will help us track down the bug faster.

@ainame I wonder if you'd be curious to take a look at this issue? 😁🙏

**Comment by ainame** [comment]
On top of the template info, to clarify your situation, can you elaborate on what change you were going to apply to screenshots? 
So example -
* The app has x screenshots for 6.5-inch screenshots on each region on the current released version
* The next version was going to replace those all screenshots with completely new ones
* etc...

There are a few cases where `deliver` may miss such deletions...

1. You didn't set `true` to `overwrite_screenshots` option
2. Local screenshots directory's structure doesn't match supported regions on App Store Connect  https://github.com/fastlane/fastlane/issues/17380#issuecomment-704396944
(There might be more but I'm not aware of rest)

> Too many screenshots found for device 'APP_IPHONE_55'

What I assume from those messages is that you try to replace old screenshots without `overwrite_screenshots` but `deliver` didn't delete old ones (this is actually expected behaviour) so that App Store Connect got both old and new screenshots mixed. Then next time you tried, it appeared to exceed the limit of 10 screenshots due to that reason (maybe the situation would be like 6 old images + 4 new images are uploaded and 2 new images still remain not uploaded status... or something 🤔). 

This is my guess😅 

> The html file for verification looks fine

This is confusing but the generated HTML is meant to see local screenshots, I think. It has nothing with uploading results apparently.

**Comment by ainame** [comment]
@bb-git 

On top of the template info, to clarify your situation, can you elaborate on what change you were going to apply to screenshots? 
So example -
* The app has x screenshots for 6.5-inch screenshots on each region on the current released version
* The next version was going to replace those all screenshots with completely new ones
* etc...

There are a few cases where `deliver` may miss such deletions...

1. You didn't set `true` to `overwrite_screenshots` option
2. Local screenshots directory's structure doesn't match supported regions on App Store Connect  https://github.com/fastlane/fastlane/issues/17380#issuecomment-704396944
(There might be more but I'm not aware of rest)

> Too many screenshots found for device 'APP_IPHONE_55'

What I assume from those messages is that you try to replace old screenshots without `overwrite_screenshots` but `deliver` didn't delete old ones (this is actually expected behaviour) so that App Store Connect got both old and new screenshots mixed. Then next time you tried, it appeared to exceed the limit of 10 screenshots due to that reason (maybe the situation would be like 6 old images + 4 new images are uploaded and 2 new images still remain not uploaded status... or something 🤔). 

This is my guess😅 

> The html file for verification looks fine

This is confusing but the generated HTML is meant to see local screenshots, I think. It has nothing with uploading results apparently.

**Comment by bb-git** [comment]
Thanks for the hint! I didn't have the `overwrite_screenshots` option included. As I used the lane for years, I didn't even consider something like this. You saved me a lot of time :).
