### ISSUE TITLE
Invalid transport parameter

### ISSUE THREAD

**Issue by ainopara** [fastlane/fastlane#17453]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: Since #16774 merged

### Regression Description
We specify a custom DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS env parameter to make itmsTransporter to use our proxy to speed up upload. 
We also not specify a -t parameter intentionally to let itmsTranspoter determine best trasport method for us. 
#16774 introduce a check which force DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS contains `-t ` else it will report `Invalid transport parameter`. Which is against what Apple suggested mentioned in #16774. 
Is that a bug?

**Comment by ainopara** [comment]
Thank you bot, I know output of `fastlane env` is not included, but I think that is not needed since I already find out the issue and have a solution ( remove the check or remove a `!`).

**Comment by max-ott** [comment]
Might be related: https://github.com/fastlane/fastlane/issues/17448

**Comment by rogerluan** [comment]
Your logic seems right to me. The code doesn't seem to match what's on the docs and the code comments. I tried removing the `!` but 10 specs failed. I haven't analyzed whether the specs are fundamentally wrong, or if this needs other type of solution. 

@ainopara contributions are welcome! If you decide to take a look at this issue and end up opening a PR, feel free to tag me in! 😊

**Comment by ainopara** [comment]
I suggest change the error to a warning so that it will not block any current configurations.

**Comment by rogerluan** [comment]
I agree with you @ainopara - from what I can tell, the boolean condition is inverted and it should be fixed. However, since there are users that _do_ pass the `-t` option and it _is_ a valid option that users can pass (i.e. it's not an actually illegal parameter), we shouldn't stop users from using it - although we can nicely advise them not to 😊 


I have changed the logic to "if there's a `-t` parameter, warn and proceed". However, there were 2 specs that were in place to prevent anything other than "-t " to be a valid parameter for the `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS` env var. My question to you is: are you passing `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS` env var with options that are listed under Apple's documentation, and are not `-t`? 
I assumed so, and updated the documentation based on this assumption. Let me know what value you're sending in to `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS` as that would help me have a better understanding of users' needs 😊 

The PR can be found, reviewed and tested here 😁  https://github.com/fastlane/fastlane/pull/17793

If you could help us test it, that'd be super! 🚀 I hope this fix resolves the issue for you!

**Comment by ainopara** [comment]
Thank you for your PR!👍

> are you passing DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS env var with options that are listed under Apple's documentation, and are not -t?

Yes, I'm currently using these parameters to tell itmsTransporter to use our proxy server to upload. these parameters seems works for every java program and since itmsTransporter is a java program, it should work for itmsTransporter too. 
I tested these parameters about 1-2 years ago, and found out adding that can speed up our upload at the moment.

```
-DsocksProxyHost=the.proxy.domain -DsocksProxyPort=8080
```

**Comment by rogerluan** [comment]
Very very interesting! I believe the changes I made are correct then 🙏 Thanks for sharing! 🎉
