### ISSUE TITLE
Download DSYMs action broken

### ISSUE THREAD

**Issue by gasigo** [fastlane/fastlane#17677]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have a Bitrise workflow to download DSYM files from the App Store Connect and upload them to Firebase. The step to download the DSYM files is not working anymore since last week.

##### Command executed
`Fastlane::Actions::DownloadDsymsAction.run username:ENV["ASC_APPLE_ID"], app_identifier:ENV["BUNDLE_ID"], team_id:ENV["TEAM_ID"], version:"latest"`

##### Complete output when running fastlane, including the stack trace and command used
```
[09:43:25]: Login to App Store Connect ([REDACTED])
[09:43:28]: Login successful
/Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.168.0/spaceship/lib/spaceship/connect_api.rb:79:in `map': undefined method `to_sym' for nil:NilClass (NoMethodError)
	from /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.168.0/fastlane/lib/fastlane/actions/download_dsyms.rb:37:in `run'
	from /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise928764210/step_src/ruby_content_file.rb:4:in `<main>'
--- finished ---
```

**Comment by rogerluan** [comment]
Hey @gasigo 👋 

You're not sending `platform` to your `download_dsyms` action. You shouldn't need to invoke "run" explicitly - let `download_dsyms` action build its parameters on its own by simply calling `download_dsyms(<your params here>)`.

`platform` has a default value, but since you're not invoking the action the designed way, it's not initializing the default parameters 🤷 

Three ways to fix this problem:
a. call `download_dsyms(< your params here>)`
b. pass `platform:"ios"` parameter
c. set `DOWNLOAD_DSYMS_PLATFORM` env var to "ios"

What intrigued me is that you said it broke in Nov/2020, so I checked and this changed here: https://github.com/fastlane/fastlane/commit/a4bb7ccc28690e3d8f873963767fdbe0ce74a999

For this reason, I'll update the action's options documentation to state that platform is no longer optional 👍 This will give a more user friendly error message for anyone else facing this issue.

**Comment by rogerluan** [comment]
@gasigo if you follow either of those solutions, you should have the issue resolved 👍 let me know if those don't work for you. I'm closing this issue for now.
