### ISSUE TITLE
Failed to install Fastlane on CentOS or Ubuntu

### ISSUE THREAD

**Issue by DreamPWJ** [fastlane/fastlane#17943]
![image](https://user-images.githubusercontent.com/16730031/104163063-bd897e00-5430-11eb-9010-cd9a35c9db3b.png)

**Comment by Henriet3** [comment]
Choosing Fastlane for automatic publishing mobile apps to the store is no wonder. It's the most preferred way to publish apps automatically.

**Comment by ainame** [comment]
This is more like an issue on your end. It looks like you couldn't install `unf_ext` gem that has native extensions. Meaning your system would miss building tools like C++ compiler. So maybe try `apt-get build-essential` or something. 

https://github.com/knu/ruby-unf_ext

**Comment by DreamPWJ** [comment]
Apt-get install build-essential-y apt-get install build-essential-y apt-get install build-essential-y       ERROR: Failed to build gem native extension.

**Comment by ainame** [comment]
@DreamPWJ Sorry I can't help you any more without more info. But probably this is the root cause?

<img width="1027" alt="Screenshot 2021-01-19 at 10 01 56" src="https://user-images.githubusercontent.com/748949/105018837-5f1a5c00-5a3d-11eb-9d79-1f74747537a0.png">

Try `apt-get install ruby-dev` or something.
