### ISSUE TITLE
-disable-concurrent-testing is deprecated in run_tests

### ISSUE THREAD

**Issue by tevelee** [fastlane/fastlane#18024]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When run_tests with `disable_concurrent_testing: true` is performed, the output shows the following warning:
"Warning: -disable-concurrent-testing is deprecated. Use -disable-concurrent-destination-testing instead."
I use the latest Xcode (12.3) and toolchain set.

Indeed, [run_tests uses the old flag](https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/test_command_generator.rb#L48) when assembling the xcodebuild command.

##### Command executed

`bundle exec fastlane tests`

```
run_tests(
      scheme: "Tests",
      skip_build: false,
      reset_simulator: true,
      prelaunch_simulator: true,
      skip_slack: true,
      result_bundle: true,
      use_clang_report_name: true,
      include_simulator_logs: true,
      disable_concurrent_testing: true
    )

**Comment by minuscorp** [comment]
When does the new flag got introduced in xcodebuild?

**Comment by tejassharma96** [comment]
I just went through the release notes for xcode 10-13.5 and couldn't find which version it was deprecated in 😭  
https://developer.apple.com/documentation/xcode-release-notes

I did find this tweet from an apple dev: https://twitter.com/aikoniv/status/1042309204801798144?lang=en  
He references this flag on Sep 19 2018, which matches the Xcode 10 release date (Sep 17 2018 - https://xcodereleases.com/), so it probably existed since then. I'm not sure how long it's been deprecated for.

**Comment by tejassharma96** [comment]
Are there any plans to update this flag?
