### ISSUE TITLE
You can do it using spaceship - [the Spaceship docs](https://github.com/fastlane/fastlane/blob/master/spaceship/docs/AppStoreConnect.md) has a bit more details, but in essence something like the following should work:

### ISSUE THREAD

**Issue by shankarthayalan1703** [fastlane/fastlane#18217]
You can do it using spaceship - [the Spaceship docs](https://github.com/fastlane/fastlane/blob/master/spaceship/docs/AppStoreConnect.md) has a bit more details, but in essence something like the following should work:

```ruby

:lane release_app do |options|
  Spaceship::Tunes.login # assuming FASTLANE_USER and FASTLANE_PASSWORD are set
  Spaceship::Tunes.select_team(team_id) # if required
  
  app = Spaceship::Tunes::Application.find("com.my.app")
  edit_version = app.edit_version
  
  # ...  some validation of version etc ...
  
  edit_version.release!
end
```

_Originally posted by @Hiroto-N in https://github.com/fastlane/fastlane/issues/15977#issuecomment-584542057_

**Comment by shankarthayalan1703** [comment]
Hi @janpio @joshdholtz , Getting error when we changed **Spaceship::Tunes** to **Spaceship::ConnectAPI**. 


Here's my lane 

lane :developerRelease do
puts "developerRelease"
	token = Spaceship::ConnectAPI::Token.create(
		   key_id: "ABCD",
		   issuer_id: "1234-4321",
		   filepath: "ABCD.p8",
	)
	Spaceship::ConnectAPI.token = token
	app = Spaceship::ConnectAPI::App.find(ENV['app_identifier'])
	v = app.get_edit_app_store_version(platform: Spaceship::ConnectAPI::Platform::IOS)
	puts v.version
	v.release!
end


Can you please help me with this??

**Comment by max-ott** [comment]
Please don't ping collaborators if this project with your personal questions, this is just rude. If you have questions about your code, use discussions, Stackoverflow or hire a developer to help you. It's not clear to me what exactly you want to achieve. The old code does no longer work, because it uses deprecated endpoints from Apple. The other one should work, just make sure you are not simply using the old logic with the new models, as they are completely different.
