### ISSUE TITLE
"No 'teamID' specified and no team ID found in the archive"

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1825]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/4329185?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @AvdLee - Imported from <a href='https://github.com/fastlane/gym/issues/204'>fastlane/gym#204</a>
        </td>
      </tr>
    </table>

Using gym as followed from the terminal:
```
gym build -s MyApp
```

I'm getting the following error:
```
Error Domain=IDEFoundationErrorDomain Code=1 "No 'teamID' specified and no team ID found in the archive" UserInfo={NSLocalizedDescription=No 'teamID' specified and no team ID found in the archive}
```

Any idea how to fix this?

I've checked my team setting in the project, which is setted correctly.

**Comment by AvdLee** [comment]
For me this one can be closed.

**Comment by KrauseFx** [comment]
👍

**Comment by false** [comment]
I had this issue for a month ; It was indeed fixed by using the "use legacy build" arg, but unfortunately the built IPAs were marked as unsigned for the AppStore (-> hence I could not upload them to iTunes Connect).

The real issue was my distribution certificates marked as "always trust" in my keychain. When I set my certificates back to system default, the "No 'teamID' specified ..." issue was gone and I didn't have to use legacy build anymore.
