### ISSUE TITLE
Add Symbols folder to the ipa

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1869]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/680442?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @CraigSiemens - Imported from <a href='https://github.com/fastlane/gym/issues/51'>fastlane/gym#51</a>
        </td>
      </tr>
    </table>

It would be great if there was an option to add the `Symbols` folder to the `ipa` just like Xcode does so crash reports from iTunes Connect can be symbolicated.

I have been using a `fastlane` action to do this but I think it would be good if it was part of `gym`. I only know enough Ruby to make me dangerous, but here is the action if anyone want to add it to `gym`.

```ruby
ipa_path = File.expand_path(Actions.lane_context[Actions::SharedValues::IPA_OUTPUT_PATH])
app_name = File.basename(ipa_path, ".ipa")
folder_path = File.dirname(ipa_path)

Dir.mktmpdir do |dir|
    app_binary = File.join(dir, "Payload", "#{app_name}.app", app_name)
    symbols = File.join(dir, "Symbols")

    Actions.sh "unzip \"#{ipa_path}\" -d \"#{dir}\""
    Actions.sh "mkdir \"#{symbols}\""
    Actions.sh "xcrun symbols -noTextInSOD -noDaemon -arch all -symbolsPackageDir \"#{symbols}\" \"#{app_binary}\""

    all_folders = Dir.glob(File.join(dir, "*")).map { |f| "\"#{File.basename(f)}\"" }.join(" ")

    Actions.sh "cd \"#{dir}\" && zip -r \"#{ipa_path}\" #{all_folders}"
end
```

**Comment by Cyclic** [comment]
@KrauseFx, sorry if this issue is addressed elsewhere, but after running fastlane beta, submitting the app to the app store, and then viewing crashes, I am unable to see the line numbers in the Crashes section of Windows > Organizer. According to Apple, it should be possible to navigate to the crash line number in Xcode. We also use Rollbar. Is there a recommended way for users to get at the line numbers from a fastlane beta build?

<img width="682" alt="7_viewingcrashreportsteps_2x" src="https://cloud.githubusercontent.com/assets/553800/14650271/ed1a4bc2-061f-11e6-8f3b-663b828fb417.png">
 https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/AnalyzingCrashReports/AnalyzingCrashReports.html

**Comment by TKBurner** [comment]
@Cyclic Thanks for reaching out. Are you using Bitcode in your app? It seems like this issue is more related to Apple, but if you are using Bitcode, it'd be interesting to check and see if all your dSYM files are available via iTunes connect. Thanks!

**Comment by Cyclic** [comment]
@TKBurner no, we're not using Bitcode yet.

**Comment by TKBurner** [comment]
@Cyclic Thanks for following up. It seems like you should file a radar with Apple. Can you update this thread when you hear back from their team? Thanks!

**Comment by kdawgwilk** [comment]
Is it possible that you have to download the new dSYMs generated by Apple in the organizer before they can be symbolicated in organizer also?

**Comment by TKBurner** [comment]
@kdawgwilk Hi, hope you are doing well. If you are using bitcode this is most likely the case. Thanks!

**Comment by orkenstein** [comment]
@KrauseFx As far as I understand, now it's only available to include symbols with `gym`. But in my current project we use *Unreal Editor* to build the app and `.DSYM`. So, is it possible to include `.symbols` into existing `.ipa` now?

**Comment by orkenstein** [comment]
@CraigSiemens where does it actually takes `.DSYM` from?
