### ISSUE TITLE
Old version stuck on processing makes 'Waiting for iTunes Connect to process new build' wait forever

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1889]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/2995710?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @kerrmarin - Imported from <a href='https://github.com/fastlane/pilot/issues/97'>fastlane/pilot#97</a>
        </td>
      </tr>
    </table>

Hi there,

I have an app that has older versions that are stuck on "processing" and they have been for a few days now. This means that Pilot will keep waiting and waiting even though the current version has processed correctly. It would be great if Pilot only waited for builds of the current version, or even better, if it only waited for the specific build and version that was uploaded.

Thanks

**Comment by timcamber** [comment]
I'm seeing this too. It looks like this could be fixed around [line 78 of `pilot`'s `build_manager.rb`](https://github.com/fastlane/fastlane/blob/master/pilot/lib/pilot/build_manager.rb#L78) by, instead of checking that there are 0 builds processing, checking that the latest / just-uploaded build is processing. I don't have enough Ruby knowledge to fix this myself; does this seem like a reasonable solution?
