### ISSUE TITLE
fastlane plugin for amazon appstore

### ISSUE THREAD

**Issue by felixwortmann** [fastlane/fastlane#19010]
### Discussed in https://github.com/fastlane/fastlane/discussions/19009

<div type='discussions-op-text'>

<sup>Originally posted by **felixwortmann** June 26, 2021</sup>
Since Windows 11 was announced to support Android apps from the amazon appstore, I guess the demand for a fastlane plugin for the amazon appstore is bigger than ever. I saw #1963 and #15148, which are both closed by now. Is there anything happening on this topic? Can we expect this feature to be supported at some point?</div>

**Comment by joshdholtz** [comment]
@felixwortmann Heyyy 👋  I saw that announcement and actually thought that it was time to make this plugin 😊 I'll be adding this to my list if nobody gets to it first 💪

**Comment by Kunkel9** [comment]
Fastlane touts itself as the easiest way to automate deployments for mobile apps. It offers integrations with other CLI tools and APIs including Xcode, Android SDK, Gradle, iTunes App Store, Google Play Store, Git, AWS S3, etc. We adopted it because we found it to be:

Easy to set up (just install a Ruby gem)
Flexible, with an easy to read syntax (most commands have self-descriptive aliases)
Open Source and free to use
Widely adopted and well maintained (acquired by Google in 2017)
Easy to integrate with CI systems (though 2FA presents challenges, as we’ll see)

**Comment by Summerlin459** [comment]
Fastlane plugin for App Center ... A Fastlane plugin that allows to cache Carthage​/Build folder in Amazon S3. ... Gradoservice plugin to rule apps releases.

**Comment by max-ott** [comment]
Feature requests should be in discussions and not in issues. Thanks Josh for keeping an eye on the topic!
