### ISSUE TITLE
supply - unknown keyword: changes_not_sent_for_review

### ISSUE THREAD

**Issue by codyrotwein** [fastlane/fastlane#19208]
I'm getting the following error when trying to upload a build to Google Play with fastlane:
`Traceback (most recent call last):
	35: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	34: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	33: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `<main>'
	32: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `load'
	31: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/bin/fastlane:23:in `<top (required)>'
	30: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	29: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	28: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	27: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	26: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	25: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	24: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	23: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	22: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	21: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	20: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	19: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	18: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	17: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	16: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	15: from Fastfile:314:in `block in parsing_binding'
	14: from Fastfile:314:in `each'
	13: from Fastfile:369:in `block (2 levels) in parsing_binding'
	12: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	11: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	10: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	 9: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 8: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 7: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 6: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 5: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
	 4: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/supply/lib/supply/uploader.rb:40:in `perform_upload'
	 3: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/supply/lib/supply/client.rb:165:in `commit_current_edit!'
	 2: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/supply/lib/supply/client.rb:81:in `call_google_api'
	 1: from /Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/fastlane-2.190.0/supply/lib/supply/client.rb:166:in `block in commit_current_edit!'
/Users/codyrotwein/.rvm/gems/ruby-2.6.3/gems/google-api-client-0.53.0/generated/google/apis/androidpublisher_v3/service.rb:72:in `commit_edit': [!] unknown keyword: changes_not_sent_for_review (ArgumentError)`

It just started doing this. I'm on the latest fastlane version - 2.190.0

**Comment by pfay-fc** [comment]
Same here after updating from 2.189.0 to 2.190.0, presumably related to this addition https://github.com/fastlane/fastlane/commit/167087b4a3433042ac6725e88f51ea7961ce18f1

Not sure what the problem is immediately though, I agree as that commit claims that androidpublisher_v3 0.3.0 is the version of gem that added that param, from this commit https://github.com/googleapis/google-api-ruby-client/commit/339a7ccd1c614cfbf8653417db364f2f15ee727c

In my gemfile lock I have:
```
    fastlane (2.190.0)
      CFPropertyList (>= 2.3, < 4.0.0)
      addressable (>= 2.8, < 3.0.0)
      artifactory (~> 3.0)
      aws-sdk-s3 (~> 1.0)
      babosa (>= 1.0.3, < 2.0.0)
      bundler (>= 1.12.0, < 3.0.0)
      colored
      commander (~> 4.6)
      dotenv (>= 2.1.1, < 3.0.0)
      emoji_regex (>= 0.1, < 4.0)
      excon (>= 0.71.0, < 1.0.0)
      faraday (~> 1.0)
      faraday-cookie_jar (~> 0.0.6)
      faraday_middleware (~> 1.0)
      fastimage (>= 2.1.0, < 3.0.0)
      gh_inspector (>= 1.1.2, < 2.0.0)
      google-apis-androidpublisher_v3 (~> 0.3)
      google-apis-playcustomapp_v1 (~> 0.1)
      google-cloud-storage (~> 1.31)
      highline (~> 2.0)
      json (< 3.0.0)
      jwt (>= 2.1.0, < 3)
      mini_magick (>= 4.9.4, < 5.0.0)
      multipart-post (~> 2.0.0)
      naturally (~> 2.2)
      plist (>= 3.1.0, < 4.0.0)
      rubyzip (>= 2.0.0, < 3.0.0)
      security (= 0.1.3)
      simctl (~> 1.6.3)
      terminal-notifier (>= 2.0.0, < 3.0.0)
      terminal-table (>= 1.4.5, < 2.0.0)
      tty-screen (>= 0.6.3, < 1.0.0)
      tty-spinner (>= 0.8.0, < 1.0.0)
      word_wrap (~> 1.0.0)
      xcodeproj (>= 1.13.0, < 2.0.0)
      xcpretty (~> 0.3.0)
      xcpretty-travis-formatter (>= 0.0.3)
...
    google-api-client (0.53.0)
      google-apis-core (~> 0.1)
      google-apis-generator (~> 0.1)
    google-apis-androidpublisher_v3 (0.10.0)
      google-apis-core (>= 0.4, < 2.a)
```

But then I have the same stack as cody - and **note that the androidpublisher_v3 code that's actually being called isn't from the android publisher gem - it's from the google-api-client gem!**

So the end of my stack is
```
ArgumentError: [!] unknown keyword: :changes_not_sent_for_review
/usr/local/lib/ruby/gems/2.7.0/gems/google-api-client-0.53.0/generated/google/apis/androidpublisher_v3/service.rb:72:in `commit_edit'
```
and that version of commit_edit certainly does not have the `changes_not_sent_for_review` param

If instead it had called the proper gem `/usr/local/lib/ruby/gems/2.7.0/gems/google-apis-androidpublisher_v3-0.10.0/lib/google/apis/androidpublisher_v3/service.rb` - that file DOES have the param as expected.

I am not sure what causes it to use that wrong version of androidpublisher though, I'm not very familiar with ruby or gems.

**Comment by rock-tran** [comment]
I got this too. Can't release app by fastlane. I have to publish bundle manually !!!

**Comment by codyrotwein** [comment]
For now, I had to downgrade fastlane to 2.188.0 in order to get past this issue.

**Comment by Ashley5582** [comment]
Pleased to see your issue as I think I have the same problem, I am also confused and in need of light on this same issue. Need help.

**Comment by pfay-fc** [comment]
There is some more discussion of what version of android publisher to lock in in this PR https://github.com/fastlane/fastlane/pull/19117#issuecomment-887711159

For me the problem was not with that being the wrong verison, but rather with the older version of `google-api-client` (0.53.0) being called, rather than the `google-apis-androidpublisher_v3` gem. I had another plugin/dependency that was using the `google-api-client` - and switching that to use `google-apis-androidpublisher_v3` was what's required. That fixed it for me.

The change I had to make to my plugin is here: https://github.com/tigger0jk/fastlane-plugin-playship/commit/13d875c7436322d88ffc4913dc6ccbe40fc01880
