### ISSUE TITLE
Add branch name to slack notification

### ISSUE THREAD

**Issue by fastlane-bot-helper** [fastlane/fastlane#1945]
<table>
      <tr>
        <td>
          <img src='https://avatars0.githubusercontent.com/u/248861?v=3&s=70' width='35'>
        </td>
        <td>
          Original issue by @nvh - Imported from <a href='https://github.com/fastlane/scan/issues/14'>fastlane/scan#14</a>
        </td>
      </tr>
    </table>

It would be nice if the notification in slack (optionally) shows the branch name that the tests were run with.

**Comment by esteluk** [comment]
This would be incredibly useful to have, even if it just takes the form of a custom message.

**Comment by TKBurner** [comment]
@esteluk Thanks for following up. I'm going to send out your PR so we can get some eyes on it. 👍

**Comment by esteluk** [comment]
Ta :)

**Comment by OrRosenblatt** [comment]
I have a similar use case in my company. We want to add to Slack’s scan results message much more content (for example, a link for the build in the CI system and the list of commits that cause test failures).
The suggested solution doesn’t cover our need because attachment doesn’t support markdown formatting. 
May I suggest another PR, based on setting Slack’s message text as the optional ‘slack_message’ argument (instead of inserting this argument as an attachment)?
