### ISSUE TITLE
Scan + Xcode 13.1: WARNING: Using the first of multiple matching destinations

### ISSUE THREAD

**Issue by apps4everyone** [fastlane/fastlane#19579]
When using scan with Xcode 13.1

```
scan({
    devices: ["iPhone 13"],
    ....
  })
```

there is a warning:
WARNING: Using the first of multiple matching destinations

This makes it harder to have CI logs cleaner to easier find some errors.

![image](https://user-images.githubusercontent.com/1915802/156748810-ac3c5728-d3e1-4276-8500-ca7265030be2.png)

**Comment by apps4everyone** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 12.0.1                                                  |
| Ruby                        | 3.0.2                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.33.0                                      |
| Installation Source         | ~/.gem/bin/fastlane                                     |
| Host                        | macOS 12.0.1 (21A559)                                   |
| Ruby Lib Dir                | ~/.rbenv/versions/3.0.2/lib                             |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                             |
| Is contained                | false                                                   |
| Is homebrew                 | false                                                   |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode-13.1..app/Contents/Developer/ |
| Xcode Version               | 13.1                                                    |
| Swift Version               | 5.5.0                                                   |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.197.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter | 1.11.1  | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.5        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| google-cloud-env                | 1.5.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| tsort                           | 0.1.0        |
| uri                             | 0.10.1       |
| set                             | 1.0.1        |
| CFPropertyList                  | 3.0.4        |
| unicode-display_width           | 1.8.0        |
| excon                           | 0.88.0       |
| ruby2_keywords                  | 0.0.5        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.8.0        |
| unf_ext                         | 0.0.8        |
| faraday_middleware              | 1.2.0        |
| json                            | 2.6.1        |
| bundler                         | 2.2.26       |
| jwt                             | 2.3.0        |
| webrick                         | 1.7.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.16.0       |
| os                              | 1.1.1        |
| memoist                         | 0.16.2       |
| googleauth                      | 1.1.0        |
| mini_mime                       | 1.1.2        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.1        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.6.0        |
| google-apis-androidpublisher_v3 | 0.13.0       |
| google-cloud-errors             | 1.2.0        |
| google-apis-iamcredentials_v1   | 0.8.0        |
| google-apis-storage_v1          | 0.9.0        |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| emoji_regex                     | 3.2.3        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.4.0        |
| aws-partitions                  | 1.525.0      |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.122.0      |
| aws-sdk-kms                     | 1.51.0       |
| aws-sdk-s3                      | 1.105.0      |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| pathname                        | 0.1.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.2.0        |
| date                            | 3.1.0        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| openssl                         | 2.2.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.2        |
| io-wait                         | 0.1.0        |
| zlib                            | 1.1.0        |
| resolv                          | 0.2.0        |
| securerandom                    | 0.1.0        |
| digest                          | 3.0.0        |
| time                            | 0.1.0        |
| open-uri                        | 0.1.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.0        |
| rack                            | 2.2.3        |
| rack-test                       | 1.1.0        |
| fileutils                       | 1.5.0        |
| tempfile                        | 0.1.1        |
| delegate                        | 0.2.0        |
| tmpdir                          | 0.1.2        |
| ostruct                         | 0.3.1        |
| strscan                         | 3.0.0        |
| english                         | 0.7.1        |
| erb                             | 2.2.0        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.7        |
| base64                          | 0.1.0        |
| singleton                       | 0.1.1        |
| net-http                        | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.0        |
| nokogiri                        | 1.12.5       |
| racc                            | 1.6.0        |
| prettyprint                     | 0.1.0        |
| pp                              | 0.1.0        |
| find                            | 0.1.0        |
| yaml                            | 0.1.1        |
| psych                           | 3.3.0        |
| fastlane-plugin-appcenter       | 1.11.1       |
| csv                             | 3.2.0        |
</details>


*generated on:* **2021-11-05**
</details>

**Comment by apps4everyone** [comment]
`xcrun instruments -s devices` should be change to:
`xcrun xctrace list devices`

**Comment by apps4everyone** [comment]
react-native fix: https://githubmemory.com/repo/facebook/react-native/issues/32331

**Comment by apps4everyone** [comment]
@joshdholtz just FYI.

**Comment by apps4everyone** [comment]
look's like still relevant for Xcode 13.2 RC

**Comment by zanefairbanks** [comment]
And still an issue with Xcode 13.2 proper.

**Comment by Sherlouk** [comment]
Looks to still be a problem with Xcode 13.2.1

Has anybody managed to workaround this problem? I'm getting stuck with an error because it's not picking up the device I'm specifying? (Any iOS Device is the first one it picks up)

>xcodebuild: error: Failed to build project XXX with scheme XXX
>Reason: Cannot test target “UnitTests” on “Any iOS Device”: Tests must be run on a concrete device

**Comment by Sherlouk** [comment]
@gobetti Hey 👋  So I am specifying a device (iPhone 12 Pro) but it's not detecting it which is, on reflection, showing a slightly different error to the one mentioned here. I'll open a new issue with my details as to not distract from this thread. Apologies all.

**Comment by bnickel** [comment]
I'm getting this issue as well.  It's just a warning but it's bothersome.  The message logs when `xcodebuild -resolvePackageDependencies` is running.  It's called without a destination presumably because it doesn't need one to do the job, but `xcodebuild` thinks it is.

The source lane:

```ruby
  lane :swiftui_unit_tests do
    scan(
      workspace: "Heap-Integration.xcworkspace",
      scheme: "Heap.SwiftUI",
      testplan: "SwiftUI Unit Tests",
      destination: "platform=iOS Simulator,id=#{@udid}",
      result_bundle: true,
      include_simulator_logs: false
    )
  end
```

The message:

```text
[15:53:09]: ------------------
[15:53:09]: --- Step: scan ---
[15:53:09]: ------------------
[15:53:09]: Resolving Swift Package Manager dependencies...
[15:53:09]: $ xcodebuild -resolvePackageDependencies -workspace Heap-Integration.xcworkspace -scheme Heap.SwiftUI
[15:53:10]: ▸ Command line invocation:
[15:53:10]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace Heap-Integration.xcworkspace -scheme Heap.SwiftUI
[15:53:10]: ▸ User defaults from command line:
[15:53:10]: ▸     IDEPackageSupportUseBuiltinSCM = YES
[15:53:11]: ▸ Resolve Package Graph
[15:53:11]: ▸ Resolved source packages:
[15:53:11]: ▸   Swifter: https://github.com/heap/swifter.git @ 1.4.7-Xcode12
[15:53:11]: ▸ --- xcodebuild: WARNING: Using the first of multiple matching destinations:
...
```

**Comment by apps4everyone** [comment]
any news here? thx

**Comment by mcaylus** [comment]
I am also facing the exact same issue as described originally. Is there any plan regarding this?

**Comment by lanserxt** [comment]
+1 
`▸ --- xcodebuild: WARNING: Using the first of multiple matching destinations:
`

**Comment by AliSoftware** [comment]
Same here, and the even more annoying thing with this warning is that, since we're using Buildkite as a CI, and any line starting with `---` is [interpreted as a collapsible section in the logs](https://buildkite.com/docs/pipelines/managing-log-output#collapsing-output), this makes it super hard to navigate the logs, and cut the logs into sections in random places which don't make sense, hiding important sections (like actual fastlane steps running) under those.

### Concrete Example

Here's a concrete example of how it makes it all quite unusable in our CI logs:

<img width="1118" alt="Screenshot 2022-06-20 at 19 21 47" src="https://user-images.githubusercontent.com/216089/174652898-77bb58f4-0c26-4c51-a61c-2b2404dac96d.png">

In the example above our `Fastfile`'s lane looks something like this (over-simplified):
```
scan(build_for_testing: true, …)
create_missing_simulators_for_screenshots # custom lane of ours
[true, false].each do |dark_mode_enabled|
      capture_ios_screenshots(…, test_without_building: true, dark_mode: dark_mode_enabled, devices: …)
end
```

And in the CI logs screenshoted above, this shows like this

- `xcodebuild: WARNING: Using the first of multiple matching destinations: | 4s` (mostly empty, just list of sims)
- `xcodebuild: WARNING: Using the first of multiple matching destinations: | 11s` (mostly empty, just list of sims)
- `xcodebuild: WARNING: Using the first of multiple matching destinations: | 11s` (mostly empty, just list of sims)
- `xcodebuild: WARNING: Using the first of multiple matching destinations: | 8m 43s`
   - "Summary for scan 2.206.2" ASCII table
   - Invocation of scan ("Compiling …" logs)
   - Call of our custom `create_missing_simulators_for_screenshots` lane
   - Header for "Step: capture_ios_screenshots"
   - Calls for `xcodebuild -resolvePackageDependencies` and `xcodebuild -showBuildSettings` made by that action
   - And that's it; the logs for the actual run of `capture_ios_screenshots` (aka `snapshot`) are in another section below instead.
- `xcodebuild: WARNING: Using the first of multiple matching destinations: | 3s` (mostly empty, just list of sims)
- `xcodebuild: WARNING: Using the first of multiple matching destinations: | 18s` (mostly empty, just list of sims)
- `xcodebuild: WARNING: Using the first of multiple matching destinations: | 8s` (mostly empty, just list of sims)
- `xcodebuild: WARNING: Using the first of multiple matching destinations: | 12m 15s`
   - "Summary for snapshot 2.206.2" ASCII table
   - Logs for that actual first run of `snapshot` (aka `capture_ios_screenshots`)
   - "snapshot results" ASCII table
   - Header for "Step: capture_ios_screenshots" (the 2nd invocation, for dark mode)
   - Calls for `xcodebuild -resolvePackageDependencies` and `xcodebuild -showBuildSettings` made by that action
   - And that's it; the logs for the actual run of `capture_ios_screenshots` (aka `snapshot`) are in another section below instead.
- `xcodebuild: WARNING: Using the first of multiple matching destinations: | 3s` (mostly empty, just list of sims)
- `xcodebuild: WARNING: Using the first of multiple matching destinations: | 4s` (mostly empty, just list of sims)
- `xcodebuild: WARNING: Using the first of multiple matching destinations: | 11s` (mostly empty, just list of sims)
- `xcodebuild: WARNING: Using the first of multiple matching destinations: | 9m 5s`
   - "Summary for snapshot 2.206.2" ASCII table (the 2nd run for dark mode)
   - Logs for that actual first run of `snapshot` (aka `capture_ios_screenshots`)
   - "snapshot results" ASCII table
   - "fastlane summary" final ASCII table


You can see how those unwanted `--- xcodebuild: WARNING: …` spread into our logs completely mess up everything and makes it quite complicated to follow and debug our logs!

**Comment by crazymanish** [comment]
i think, i know the fix to resolve this warning... 🤞  will try to open a PR to test...and update this thread

**Comment by gobetti** [comment]
still happening with 2.207.0
