### ISSUE TITLE
[pem] [spaceship] New "Apple Sandbox Push Services" certificate type

### ISSUE THREAD

**Issue by igor-makarov** [fastlane/fastlane#19878]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Looks like apple added a new certificate type ID.

##### Command executed
```
pem --app_identifier "$prefix" --team_id "$team" --output_path "build/push_certs" --pem_name "DEV_$name" --development --force
```

### Error

```
[!] Apple provided the following error info:
	The selected team does not have a program membership that is eligible for this feature.  If you need assistance, please contact Apple Developer Program Support. https://developer.apple.com/support
```

### Details

After this, I created a certificate in the web portal manually and inspected the web data. This is an excerpt from the certificate JSON:

```
      "certificateTypeId" : "JKG5JZ54H7",
      "requesterEmail" : "XXX",
      "displayName" : "XXXXX",
      "requesterLastName" : "Makarov",
      "ownerId" : "XXX",
      "platform" : "IOS",
      "certificateTypeName" : "Apple Sandbox Push Services",
      "isManaged" : false,
      "requesterFirstName" : "igor",
      "permissions" : {
        "rotate" : false,
        "download" : true,
        "approve" : true,
        "revoke" : true
      }
```

As you can see, there's a new type "Apple Sandbox Push Services" (type `JKG5JZ54H7`) which replaces "APNs Development iOS" (type `BKLRAVXMGM`).

I don't know if simply replacing the certificate type in `spaceship/lib/spaceship/portal/certificate.rb` is enough. From my manual testing, it worked but I'm not sure how this works with regards to compatibility.

@joshdholtz can you advise?

Thank you.

**Comment by nageshkumarmishra** [comment]
When this issue will get resolve???

**Comment by nageshkumarmishra** [comment]
Any update on this guys??

**Comment by valerio-castelli** [comment]
I haven't been able to investigate this yet, but I can confirm that I'm seeing the issue on my company's developer account as well. The issue seems to have in fact to do with the deprecation of the legacy `APNs Development iOS` certificate type (which still exists on Apple's Developer Portal, but perhaps can't be renewed) and the new `Apple Sandbox Push Services` certificate type. 

I'll investigate if there's any major difference between the two and if substituting the certificate type is sufficient; the fact that your manual testing showed that it worked seems quite promising.
