### ISSUE TITLE
The resource 'resetRatingsRequests' does not exist 

### ISSUE THREAD

**Issue by reishka** [fastlane/fastlane#20098]
Attempting to upload an IPA and submit for appstore review while also resetting app ratings, and fastlane quits out with: The URL path is not valid - The resource 'resetRatingsRequests' does not exist. I saw pre-existing issue [19250](https://github.com/fastlane/fastlane/issues/19250)  but it looks like it was closed out without resolution. This issue still exists.

**Comment by Russel476** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

**Comment by reishka** [comment]
@Russel476 Yes, I understand why items get auto-closed. I'm simply stating that the issue still exists and has not been resolved with any of the latest updates. My intention is not to _duplicate_ an existing item, but the already-existing item is closed, and closed for comments, so I can't even re-open to say, "hey, this problem is still here".

**Comment by roman4864** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest fastlane version and check if that solves the issue. Let us know if that works for you by adding a comment 👍
