### ISSUE TITLE
anil fastlane

### ISSUE THREAD

**Issue by anil150847** [fastlane/fastlane#20278]

**Comment by anil150847** [comment]
Hi,Lukasz I hope You are doing well.Like I have implemented fastlane in my
app and given some test cases for the app they are working fine but I want
to know that how can we fetch our test reports in android.I hope you
understand my question.

Thanks in advance

**Comment by lucgrabowski** [comment]
Hi, I've closed the issue, because description was empty. I don't use fastlane for Android. Check out docs http://docs.fastlane.tools/ and available plugins list: http://docs.fastlane.tools/plugins/available-plugins. If you don't find the answer there, please open a discussion https://github.com/fastlane/fastlane/discussions and maybe some community member will be able to help. Best regards

**Comment by anil150847** [comment]
Hi,How can we get test reports of ios for fastlane
