### ISSUE TITLE
 Could not retrieve response as fastlane runs in non-interactive mode\e[0m (FastlaneCore::Interface::FastlaneCrash)

### ISSUE THREAD

**Issue by JackyXman** [fastlane/fastlane#20607]
/opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': \e[31m[!] Could not retrieve response as fastlane runs in non-interactive mode\e[0m (FastlaneCore::Interface::FastlaneCrash)
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:170:in `verify_interactive!'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:129:in `input'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/project.rb:47:in `block in select_project'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/project.rb:46:in `loop'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/project.rb:46:in `select_project'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/project.rb:41:in `detect_projects'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/fastlane-2.209.0/gym/lib/gym/detect_values.rb:18:in `set_additional_default_values'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/fastlane-2.209.0/gym/lib/gym/module.rb:15:in `config='
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/fastlane-2.209.0/gym/lib/gym/manager.rb:8:in `work'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/fastlane-2.209.0/gym/lib/gym/commands_generator.rb:45:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/fastlane-2.209.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/fastlane-2.209.0/gym/lib/gym/commands_generator.rb:76:in `run'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/fastlane-2.209.0/gym/lib/gym/commands_generator.rb:16:in `start'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/fastlane-2.209.0/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/gems/fastlane-2.209.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.209.0/libexec/bin/fastlane:25:in `<main>'

**Comment by hasanmakane** [comment]
The only possible reason would be that Fastlane is asking for input and it needs interactive mode. when running the lane from other than terminal directly. Fastlane run in non-interactive mode. so when its that and needs input that happens.

could be asking for apple authentication maybe. you need to show your lane. and some logging.

**Comment by brux88** [comment]
i have the same problem

**Comment by kozmotronik** [comment]
It looks like a library or dependency issue. My OS is OpenSuse Tumbleweed. So I tried a workaround and managed to execute `fastlane init` command successfuly. Here is my workaround:
Before we get into it, I'll assume that you have docker installed in your system and docker daemon is active. Also note that in my case I use a Gemfile to use fastlane in my project, whose content is:
```ruby
source "https://rubygems.org"

gem "fastlane"
```
See the fastlane docs for further information on how to use fastlane with budler.

## 1. Create a docker file
Create a docker file with the following content:
```
FROM ubuntu

# Install system dependencies for fastlane
RUN apt update -qq && apt install -qq -y --no-install-recommends \
        apt-transport-https \
        curl \
        file \
        gcc \
        git \
        g++ \
        gnupg2 \
        libgl1 \
        libtcmalloc-minimal4 \
        make \
        openjdk-8-jdk-headless \
        openssh-client \
        python3 \
        rsync \
        ruby \
        ruby-dev \
        tzdata \
        unzip \
        sudo \
        ninja-build \
        zip \
    && gem install bundler \
    && rm -rf /var/lib/apt/lists/*;

# Create a working directory for the project
RUN mkdir androidProjectDir
# Later we mount the project directory on the host to this directory with docker
VOLUME androidProjectDir

WORKDIR androidProjectDir
```
Then save it in the same level directory which your project's directory resides in. It should look like something like this:
```
AndroidProjects
├── Dockerfile
├── YourAndroidProject

```

## 2. Create a docker image
Open a terminal in the same directory where the Dockerfile is and build the docker image using the following command:
```bash
$ docker build -t ubuntu-fastlane .
```
I named the image as ***ubuntu-fastlane*** but you can name your image whatever you want. Then wait for docker to finish building your image.

## 3. Run the docker image created in previous step
Change the directory to your project's directory using the `cd` (`cd YourAndroidProject`) command in the same terminal that we opened in the previous step. Now we run our ***ubuntu-fastlane*** image using the following command.
```bash
$ docker run -it -v .:/androidProjectDir ubuntu-fastlane
```
The `-v` option is for mounting volumes from the host system or vice versa. So we mounted the ***YourAndroidProject*** directory from our host to the ***/androidProjectDir*** in the docker image. After running the command above, you shoud see an interactive shell from the docker image spawned within the same terminal. 
### ATTENTION
Practice with care because the commands we execute in the interactive shell of the docker image will affect the host file system.

## 4. Execute bundle update
Before executing any fastlane command, we should execute the update command so that the bundler install the needed files and libraries for fastlane:
```bash
$ bundle update
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
and so on...
```
Wait it to finish the installation and then continue to the next step.

## 5. Init Fastlane for your Android project
Hopefully, if everything went well so far, then we can init the fastlane for our project.
```bash
$ bundle exec fastlane init
```
Provide the needed information about your project that fastlane will ask. Fastlane should init and automatically generate the *Fastfile* and *Appfile* files in *./fastlane/* directory.
