### ISSUE TITLE
Problems using Fastlane with Unity + iOS + Teamcity

### ISSUE THREAD

**Issue by galvesribeiro** [fastlane/fastlane#21367]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to build a Unity project with fastlane for iOS. The build part works fine but apparently it is failing on the archive part of the build. 

If I get the command line and put it direct in the terminal on the same build agent with the same checkout, it would work just fine. Not when I run from the build pipeline on TeamCity. I'm using the manual code sign mode.

##### Command executed

```
/opt/homebrew/bin/fastlane ios build_ipa \
  bundle_identifier:"[BUNDLE_ID_REDACTED]" \
  code_sign_identity:"Apple Distribution" \
  provisioning_profile_name:"DM.GameClient (iOS Distribution)" \
  team_id:"[TEAM_ID_REDACTED]"
```

##### Complete output when running fastlane, including the stack trace and command used

[Xcode_Build_iOS_5534.79.log](https://github.com/fastlane/fastlane/files/11931750/Xcode_Build_iOS_5534.79.log)

> The log is big so GitHub was complaining about posting it here as text.

### Environment

> Check build log above. The first task is `fastlane env`

**Comment by colejd** [comment]
@galvesribeiro, what worked for you? Having the same issue.

**Comment by colejd** [comment]
Okay, figured it out. In my case, the script was succeeding when run through the terminal via VNC, but not when using SSH or the build agent. Turns out it's a permissions issue. 

When you run a script, the OS takes away keychain permissions depending on how the script was started (for example, with SSH). This causes Fastlane's temporary keychain logic (`setup_ci`) to fail silently, leading to some really vague failures when trying to codesign. You can verify if you're having this problem if you run `security show-keychain-info login.keychain`. If the output is `security: SecKeychainCopySettings login.keychain: User interaction is not allowed.`, then your session isn't trusted by the OS, and modifications to the keychain will fail. You might find that you get that output if you run the command using SSH, but not when you run it in the Terminal using VNC - that's the crux of it.

To fix, we made our build agent a login item, which is trusted by the OS in the same way as if you'd run it in Terminal yourself - meaning it has permission to modify the keychain. [Context here](https://youtrack.jetbrains.com/issue/TW-53307).

**Comment by galvesribeiro** [comment]
@colejd sorry for the delay.

That was precisely my problem. Both with Jenkins and TeamCity. The agent session wasn't running with the correct user. The I've created the launchd plist file with the user and no luck.

After that, I noticed that there was a flag which tells the launchd agent that it should use a full session as a daemon. When I did that, and started using the temporary keychain, then it started working.

Thanks for the heads up.
