### ISSUE TITLE
Hey folks I sped up your S3Storage by 100x

### ISSUE THREAD

**Issue by nuzayets** [fastlane/fastlane#21610]
I do not want to formalize this into a PR but you were *so close*.

First, add to your Matchfile: `s3_object_prefix("#{ENV['TEAM_ID']}/")`

And apply this patch to `s3_storage.rb`:
```diff
--- fastlane-2.216.0/match/lib/match/storage/s3_storage.rb
+++ s3_storage.rb
@@ -181,6 +181,7 @@
       end
 
       def strip_s3_object_prefix(object_path)
+        return object_path if s3_object_prefix == "#{self.team_id}/"
         object_path.gsub(/^#{s3_object_prefix}/, "")
       end
```

Obviously you want to do it a little better than this quick hack, but come on. You're already prefixing everything in S3 with the `team_id`. Why are you iterating over every file in the bucket!? If you wanted to download all the certs, why are you overwriting them on every invocation? 

We have hundreds of certs. I don't want to know how many folks are out there with thousands of certs, downloading their entire S3 bucket one by one on every build. AWS and the CI providers are certainly very happy.

**Comment by rogerluan** [comment]
This is awesome @nuzayets!

I can formalize this into a PR if you don't feel like, although I encourage you to do so so you can become an official contributor of _fastlane_ ☺️

Do you happen to have a testing steps or how I can set up and reproduce this env to observe the 100x improvement? That'd be great and make it a lot easier to make this available to all users using _fastlane_ 😊

Great find, thank you!

**Comment by christy2951hernandez** [comment]
It sounds like you’ve made a significant improvement to the S3 storage mechanism by optimizing the way the s3_object_prefix is handled. Your approach to modify the strip_s3_object_prefix method to immediately return the object_path if the s3_object_prefix matches the team_id is a clever way to avoid unnecessary iterations over every file in the bucket.
`# Patch for s3_storage.rb to optimize S3 object prefix handling

# ... [previous code]

def strip_s3_object_prefix(object_path)
  # Return the object path immediately if the s3_object_prefix matches the team_id
  return object_path if s3_object_prefix == "#{self.team_id}/"
  
  # Otherwise, strip the s3_object_prefix from the object path
  object_path.gsub(/^#{s3_object_prefix}/, "")
end

# ... [following code]
`
This optimization should indeed reduce the overhead of downloading unnecessary files, especially for teams with a large number of certificates. It’s a good practice to contribute such improvements back to the community, as it can benefit many users. Even if you’re not keen on formalizing this into a pull request (PR), sharing your findings in the project’s issues or discussions might encourage someone else to do so.

Thank you for sharing this optimization with the community!

**Comment by rmont881** [comment]
@rogerluan Looks like someone else got a PR up for this back in August, any way you could take a look? Running a patched version of fastlane with the changes from it cut 8 minutes of needless cert downloading from our builds.

**Comment by nuzayets** [comment]
https://github.com/fastlane/fastlane/pull/22199

Looks like this is resolved. Took a while, but thanks!
