### ISSUE TITLE
match: Provisioning profile doesn't match the entitlements file's value for the com.apple.developer.ClassKit-environment entitlement

### ISSUE THREAD

**Issue by nathanfallet** [fastlane/fastlane#27583]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Creating a project with the ClassKit capability, and using a match certificate.

Development profile is working, but production (app store) profile is having the wrong value for `com.apple.developer.ClassKit-environment`.

Here are the keys for the development profile:
```xml
<key>com.apple.developer.ClassKit-environment</key>
		<array>
				<string>production</string>
				<string>development</string>
		</array>
```
Here are the keys for the app store profile:
```xml
<key>com.apple.developer.ClassKit-environment</key>
		<array>
				<string>production</string>
		</array>
```

##### Command executed
```
fastlane match init
fastlane match appstore
```

##### Complete output when running fastlane, including the stack trace and command used

```
Error: Provisioning profile "match AppStore me.nathanfallet.LaTeXCards.dev" doesn't match the entitlements file's value for the com.apple.developer.ClassKit-environment entitlement. Profile qualification is using entitlement definitions that may be out of date. Connect to network to update. (in target 'LaTeX Cards' from project 'LaTeXCards')
```

The issue can also be seen in Xcode directly:
![image](https://github.com/user-attachments/assets/4ef0da59-71ee-4894-89c0-ad5d68ef1af7)

**Comment by rose987a** [comment]
Hello,
I also have same issue.
Best Regards
rose987a

**Comment by ruby05guy** [comment]
Hi,

This issue is a great example of the complexities that can arise when working with code signing and provisioning profiles in Xcode, especially when using tools like Fastlane to automate the process. It’s interesting how the ClassKit capability adds an additional layer of complexity by requiring specific environment settings (production and development), and how even a small mismatch can cause issues during app submission. I think what stands out here is the importance of maintaining synchronization between your project settings and your profiles in the Apple Developer portal. It's easy to overlook the finer details, like the ClassKit-environment key, when profiles are managed automatically by tools like Fastlane. For those new to Fastlane, it’s a great reminder that while automation saves time, it requires a deep understanding of how the tool interacts with your Apple Developer account and provisioning profiles.

**Comment by nathanfallet** [comment]
The only working solution I found for now is to update Xcode .entitlement file and set classkit environment to production manually.
