### ISSUE TITLE
[Feature] One Fastfile Template for multiple apps

### ISSUE THREAD

**Issue by mathiasAichinger** [fastlane/fastlane#327]
As we have many apps we want to have one fastfile as template file, because the deploy steps are the same for every app. We would parameterize it then via Appfile or .Env files. 

Currently we are distributing our old build script as Pod which is included in every app.

What do you think about such a feature? Any other ideas?

**Comment by KrauseFx** [comment]
@mathiasAichinger Many companies use `fastlane` to deploy hundreds of apps completely automatically. One example setup can be found on the [example page](https://github.com/fastlane/examples/tree/master/SunApps). 

Since this is all Ruby, you can easily put an almost empty `Fastfile` in your project folder and `require` the actual `Fastfile` shared across all your apps. Also just using environment variables for values that are different is probably a good and easy way to accomplish this.

You suggest to put the `fastlane` configuration files into a pod to use it in every project? Have you tried it? Can you configure your local pod to not deploy any of the files, but only have them locally?

**Comment by KrauseFx** [comment]
@mathiasAichinger Does that answer your question? Do you need any further help?

**Comment by mathiasAichinger** [comment]
@KrauseFx We are still trying around. It's not possible to import lanes via `require` right?

**Comment by KrauseFx** [comment]
@mathiasAichinger you can always import other Ruby files using `require`, which may also contain lanes. With the new lane switching technique you can easily call other lanes from within lanes.

**Comment by mathiasAichinger** [comment]
@KrauseFx the new lane switching technique could be the missing part for our solution. We will try this the next days.

**Comment by JaviSoto** [comment]
Hi @mathiasAichinger!
Did you get a chance to try this out? :)

**Comment by kordziu** [comment]
HI @KrauseFx . I am just about to add some my question to the one questioned here...

We would like having one global .env file, stored in centralized place, next to global Fastfile for our organization, and add/overwrite more specific areas with .env.default and i.e. .env.development files.

While importing our global Fastfile works pretty well with import_from_git command we have issues making .env file stored in the same repository is visible from scope of "child" Fastfile.

Is there any chance making it work with current release of Fastlane?

thanks a lot!
Paweł

**Comment by ohwutup** [comment]
Going to close this issue and mark it as a feature request. Feel free to leave a comment here if anyone would like to step in and submit a PR to help out with the `.env` files! 🌵
