### ISSUE TITLE
Supply - New App creation?

### ISSUE THREAD

**Issue by jacao** [fastlane/fastlane#3694]
Supply currently handles Android App updates, are their any plans to automate the "Add new Application" functionality for the Play store, for APKs that have not been uploaded before?

**Comment by asfalcone** [comment]
Hi @jacao This is isn't currently possible with the [API](https://github.com/google/google-api-ruby-client) available from Google. If it were made possible in the API then we'd love to review a PR that adds that functionality! Going to close this issue for now since it isn't something we can do at this time.

**Comment by jacao** [comment]
Thanks, thought that was the case, annoying that Google have'nt opened it up yet!

May have to do some browser automation for the meantime.
