### ISSUE TITLE
New Action Template uses deprecated `is_string` param

### ISSUE THREAD

**Issue by marcomorain** [fastlane/fastlane#3720]
When you create a new action using `fastlane new_action`, the action that is produced from the template uses the `is_string` parameter to FastLaneCore::ConfigItem. This is produced from this template:

https://github.com/fastlane/fastlane/blob/a6641e6e4b990cbf7e421384ada0f11b21d42930/fastlane/lib/assets/custom_action_template.rb#L52

The template should use the `type` parameter instead as documented here: https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/configuration/config_item.rb#L14

**Comment by lacostej** [comment]
That's interesting. I was looking at how to fix this properly on top of #3707 but realized that I would probably need to add tests to make sure the lack of Boolean type doesn't cause strange issues.

In fact, according to my tests, if you want a boolean, you need to pass `is_string: false` otherwise `data_type` is set to `String` (because there's no data_type for Booleans.)

Maybe @KrauseFx  has some input on that ?

**Comment by lacostej** [comment]
![image](https://cloud.githubusercontent.com/assets/24282/13761497/400580de-ea39-11e5-8422-a41b76fcc41b.png)

**Comment by KrauseFx** [comment]
Thanks @marcomorain, nice catch! Unfortunately there is no type for Boolean in Ruby, so we can't just use `type: Bool` as far as I know.

**Comment by lacostej** [comment]
We could
1. ask people to use `TrueClass` or `FalseClass` for boolean but that would make some weird code / config
2. create a Boolean class ...
3. forget about this ?

**Comment by KrauseFx** [comment]
Maybe not show a deprecated warning and lave it like is?

**Comment by lacostej** [comment]
Maybe. I just find the API confusing. One tells to not use `is_string` but it's compulsory for booleans...

**Comment by nmccann** [comment]
I also ran into this issue recently. I was trying to create a parameter that expected an `Array` object, but initially thought it wasn't possible due to the template's usage of `is_string`. Only through some searching was I able to find that the `type` parameter should be used and that it has built-in support for converting string input into an `Array` if the `ConfigItem's` `type` is equal to `Array`.

I think using `type` instead of the deprecated `is_string` would help to expose this functionality to new users.

To @lacostej's point about Boolean, I've been using `type: Object` which works. It's not really clear, but neither is `is_string: false` - I think the other benefits of using `type` make up for this.
