### ISSUE TITLE
Security risk of sharing apple account?

### ISSUE THREAD

**Issue by pavm035** [fastlane/fastlane#3861]
Hi,

How much safer it is to share apple account? Since many of the ruby scripts does various jobs of connecting different apple web services like dev.apple.com, itunesconnect.apple.com etc..?

Also how it will be future proof? Are the Apple apis' used under the hood public? Are they not fragile with new release of Xcode?

But keeping all these things aside, it's really an amazing idea that comes into reality a lot kudos to you... :)

Thanks
Pavan

**Comment by vpolouchkine** [comment]
Which tool are you referring specifically?

**Comment by pavm035** [comment]
For example sigh, deliver, pilot in order to run them they need apple credential beforehand, how they will be secured and what's the guarantee that fast lane will not use it internally?

Also all web services public from Apple? If not are they not fragile ?

Thanks

**Comment by TKBurner** [comment]
Hi, Thanks for following up. With our tools you auth directly with Apple rather than through our services. This means that you'll be only communicating directly with Apple on HTTPS. We depend on Apple's API points of Xcode, Itunes Connect, and Apple Developer portal and their stability. We are committed to growing Fastlane and only increasing functionality.

Thanks!
