### ISSUE TITLE
Possibly inconsistent commander gem version requirement

### ISSUE THREAD

**Issue by mokagio** [fastlane/fastlane#3966]
Hello all :smile:, first of all thanks for the great work you guys are putting into fastlane :clap: 

I just run in some dependency resolution in a project using fastlane and other gems.

In particular I noticed that `fastlane_core` depends on [`commander`](https://github.com/commander-rb/commander) with [version requirement `= 4.3.5`](https://github.com/fastlane/fastlane/blob/master/fastlane_core/fastlane_core.gemspec#L27), while other tools have a less strict requirement. For example [`credentials_manager` requires `>= 4.3.5`](https://github.com/fastlane/fastlane/blob/master/credentials_manager/credentials_manager.gemspec#L25), and [`krausefx-shenzhen` requires `~> 4.3`](https://github.com/fastlane/shenzhen/blob/master/shenzhen.gemspec#L17).

In my gemset case this issue resulted in fastlane version `1.54.0` being pulled, which is quite older than the latest version at the time of writing, `1.68.0`.

I looked up the [`commander` changelog](https://github.com/commander-rb/commander/blob/master/History.rdoc) and I don't see a reason to lock the version to `4.3.5`, actually I would argue its requirement should be changed into `~> 4.4`.

I am obviously lacking **a lot** of context behind the dependencies decisions on this suite of tools so I though I'd ask about it :smile: 

Thanks

**Comment by mfurtak** [comment]
Hi @mokagio - thanks for your kind words and great question! :smile: 

`fastlane_core` is locking `commander` at version **4.3.5** because it overrides some `commander` behavior via monkey-patching [here](https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb ). This helps us to provide good error reporting behavior for all of the `fastlane` command-line tools. Because our implementation changes an important method and involves copying and modifying `commander`'s code, we wanted to be sure that updates to commander didn't make our patch stop working in unexpected ways.

Since the other tools that you mention don't depend on `fastlane_core`, and can be used entirely separately from `fastlane`, it didn't seem necessary to limit their `commander` dependency in the same way.

It does seem odd to me that you should resolve to `fastlane` **1.54.0**, though. If you're willing to share your `Gemfile.lock` I'd be happy to try to sort out why :+1:

**Comment by mokagio** [comment]
@mfurtak Oh I see, I suspected there would have been a reason 😄 Fair enough...

I know you guys have your hands full with the Fastlane work, but have you considered trying to merge your upgrade into `commander` itself? I'm always worried by monkey patching 😳 

As for the resolution issue, thanks a lot for offering your help 🙏 , but I already solved it 👍
