### ISSUE TITLE
How to tell deliver only upload specified locale?

### ISSUE THREAD

**Issue by aabulkhairov** [fastlane/fastlane#4160]
### Use case

I have 10 languages.
I just edited one (japanese). I want deliver to upload only japanese, so that i don't waste time uploading the other languages that are already actual.

**Comment by TKBurner** [comment]
Great question @aabulkhairov! I'm going to circle back with the team and see what we can do 👍

**Comment by nextorlg** [comment]
11 locales here... I really need this feature otherwise for small changes I have to do it manually in itunesconnect to save time (and later in the deliver files to keep consistency).

It would be nice to have the option to select one locale but also to skip the screenshots, for example when you only want to update the description.

**Comment by TKBurner** [comment]
@nextorlg Thanks for following up. For now this is a feature request because we don't support single language upload. However, we will leave this open as it's seems to be a more common use case than we predicted. I'll also mark this as help wanted in case anyone is interested in helping 👍

**Comment by KrauseFx** [comment]
The long-term goal is that `deliver` is smart enough to detect what has changed (which metadata, which screenshots, etc.) and only upload the things that have changed. @lacostej actually started working on this via this PR: https://github.com/fastlane/fastlane/pull/3755

I'll close this issue for now, as the goal is to actually fix the underlying issue, instead of trying to work around the symptoms 👍
