### ISSUE TITLE
How to set the -ferror-limit when using Fastlane

### ISSUE THREAD

**Issue by gfpacheco** [fastlane/fastlane#453]
I have an iOS project that uses a few CocoaPods that throw a lot of warnings when compiled.

In my Podfile I have the `inhibit_all_warnings!` that prevent the warnings from showing up on Xcode build.

When I use Fastlane it throws the `fatal error: too many errors emitted, stopping now [-ferror-limit=]` error.

[This](http://stackoverflow.com/a/17925872/1732725) answer tells me that adding the `-ferror-limit=0` argument make it ignore the warnings and continue compiling.

I tried adding `xcargs: '-ferror-limit=0'` to the ipa action call in Fastfile, but it didn't work.

How can I make the Fastlane's ipa action to ignore the warnings and continue compiling?

**Comment by JaviSoto** [comment]
Hi @gfpacheco!

You may have seen that recently we released a new tool called [`scan`](https://github.com/fastlane/scan) which works wonders to run your unit tests :) I'm gonna close this issue for now since this refers to the old tool, but feel free to comment and we'll reopen it if you'd still like to get some help. Thanks!
