### ISSUE TITLE
Cocoapods 1.0 --repo-update

### ISSUE THREAD

**Issue by MickeyHub** [fastlane/fastlane#4624]
CocoaPods has release 1.0 version,  `pod install` do not update repo by default, so the `cocoapods` action will update ? although we can use sh "pod install --repo-update".

**Comment by jcampbell05** [comment]
Could you explain what the problem is more clearly ?

**Comment by TKBurner** [comment]
Hi @MickeyHub! Great to hear from you again. Can you fill out the issue template, https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md 

The more details you provide the faster we'll be able to research this 👍

**Comment by bassrock** [comment]
I think this has to do with https://github.com/fastlane/fastlane/issues/4497

**Comment by waltermvp** [comment]
@jcampbell05 
The issue is that if you locally update to a newer version of a pod that does not exist on a "CI MAC" a job may fail. This is due to the nature of how Cocoapods works. If the "CI Mac" does not have the spec of the pod version, cocoapods will not know that the new version exists and fail. This can be fixed with an action that calls 'pod repo update' which updates the local repo with all new pod specs.

Not sure if the above is clear, I can further elaborate if necessary.

**Comment by waltermvp** [comment]
Now that I think about it it may be a good fit to pass in a something like `update_master_repo` to the current `cocoapods` action

**Comment by TKBurner** [comment]
@waltermvp Are you interested in submitting a PR around this? I think it'd be interesting. Thanks!

**Comment by waltermvp** [comment]
@TKBurner would not mind giving it a try. Any good examples you would recommend I look at since I don't have a whole lot of  experience outside of Objective-C / Swift.

**Comment by TKBurner** [comment]
Hi @waltermvp Thanks for following up. You can find more info here, https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md and https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/action.rb

Thanks!
