### ISSUE TITLE
frameit requires a PSD to be in the devices folder to run

### ISSUE THREAD

**Issue by aral** [fastlane/fastlane#4673]
### New Issue Checklist

- [x] Updated fastlane to the latest version (1.89.0)
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Frameit will not run unless there’s a PSD file in the devices folder. This is a pain when you already have converted the PSD files and don’t want to keep them around (to save space + to keep the directory neater).

### Enhancement request

Check for existence of one or more PNGs instead and continue with framing if they’re found.

### Workaround

In the meanwhile, here’s a one-pixel PSD and the corresponding PNG that will skip the PSD check without your having to have all the Apple PSDs in the directory:

[skip-device-installation.zip](https://github.com/fastlane/fastlane/files/265857/skip-device-installation.zip)

**Comment by KrauseFx** [comment]
Thanks for submitting this issue @aral, this definitely shouldn't happen. I looked at the code base and found the following
```ruby
    def frames_exist?
      (Dir["#{templates_path}/**/*.psd"].count + Dir["../**/*sRGB.png"].count) > 0
    end
```
which means, it should actually find `.png` files as well, however it seems like it can't find them due to the `sRGB`. Could you send me the list of file names you currently have in the directory?

Thanks for helping me with this 👍

**Comment by KrauseFx** [comment]
Oh, seems like the `.png` files are not being looked for in the templates path, but in the local directory instead. Could you still send me the list of names, just to be sure 👍
