### ISSUE TITLE
Add support for HockeyApp "libs" parameter for Android NDK symbols from .so files

### ISSUE THREAD

**Issue by triplef** [fastlane/fastlane#4786]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Improvement Description

HockeyApp for Android supports symbolicating crashes in native (NDK) code by uploading a ZIP of the .so files as [described in their knowledgebase](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-ndk-early-access#symbolication):

> Put all .so files from the project folders `obj/local/$ABI/` into a .zip file. On HockeyApp, click on your version, then on "History" below "Builds", then on the tab "Symbols". There should be a button "Process .so files". Click it to upload the .zip with your .so files, then HockeyApp will dump the symbols and create the symbols.zip.

> If you upload your builds through the API, you can set this file as the param `libs`.

I’d like to propose adding the `libs` param as an option to the HockeyApp action similar to the existing `dsym` parameter.

Please let me know if this is something of interest and I’ll go ahead with a pull request. This will require the option to be implemented in Shenzhen first (see nomad/shenzhen#321).

**Comment by asfalcone** [comment]
@triplef Thanks for submitting this issue to talk about this request. Unfortunately [`shenzhen`](https://github.com/nomad/shenzhen) is no longer maintained by the original author, so I don't think your issue is going to get any attention there. 

We do have a [fork](https://github.com/fastlane/shenzhen/) of `shenzhen` that can be modified if neccessary. If this feature is critical to your workflow and you'd like to submit a PR there to add the libs param, I will be happy to review it. Let me know if you plan to do that. Thanks 👍

**Comment by triplef** [comment]
Sounds great, thanks for the feedback @asfalcone! I probably won’t get to it for a bit but I’m planning to take a stab at it in a couple of weeks.

**Comment by asfalcone** [comment]
Sounds good! just @ mention me in that PR or drop the link here so it doesn't get missed 😄
