### ISSUE TITLE
Hockey command does not distribute properly to a given team

### ISSUE THREAD

**Issue by gapl** [fastlane/fastlane#4816]
### Issue Description

When running the `hockey` command inside a lane of ours, we are specifying the team to which we want this app to be added. This is disregarded however as the app is not automatically added to that team.

### Configuration Files

Example for team with id `11111`

Fastfile:
```ruby
...

hockey(
        api_token: options[:hockey_api_token],
        notes: "Feature version for " + branch_name,
        notes_type: "0",
        release_type: "2",
        teams: "11111"
)

...
```

### Environment

fastlane version: fastlane 1.89.0

Do you use bundler to execute fastlane? No

Do you use a Ruby environment manager? No

**Comment by vpolouchkine** [comment]
Thanks for the report, we'll take a look.

**Comment by gapl** [comment]
Is there any known progress on this? It is quite a hassle to manually distribute every build to specific teams.

**Comment by vpolouchkine** [comment]
Nothing yet, sorry.

**Comment by mfurtak** [comment]
It's worth noting that [Hockey describes this parameter](https://support.hockeyapp.net/kb/api/api-versions#upload-version) as "restrict download to comma-separated list of team IDs". I don't know how/if that is meant to correlate to adding apps to teams from Hockey's point of view.

I do not see anything wrong with the way this value is passed through our action. But since I am not set up with Hockey, it'd be great to have help from the community on this!
