### ISSUE TITLE
[Not an issue] Q: What is the use of the pass phrase in a pem ?

### ISSUE THREAD

**Issue by CesarDominguez** [fastlane/fastlane#4942]
This is a non issue, just technical question and I thought that you are maybe the most informed person I could know in the matter :D

**Q: Which kind of security do the pem passphrases gives, is there a magical thing about it?**

My coworkers are reluctant to use pem (which is my entry point into further suggestions of fastlane) because it doesn't lets you work with a passphrase and 'is more insecure', but no one of us actually knows how insecure and worst of all, all our passphrases are the same and as easy as 'qwerty'. I instantly thought of you to be the most knowledgable on the matter and thats why I'm asking this selfish question :P

**Comment by vpolouchkine** [comment]
There is no magic involved. Take a look at [CredentialsManager](https://github.com/fastlane/fastlane/tree/master/credentials_manager) for information how this password is stored.

**Comment by KrauseFx** [comment]
You're referring to the PEM passphrase, right? 

There are a few issues for that already, like https://github.com/fastlane/fastlane/issues/2808, https://github.com/fastlane/fastlane/issues/2814, https://github.com/fastlane/fastlane/issues/2821 and https://github.com/fastlane/fastlane/issues/2848.

To sum up: pem doens't set a passphrase since it doesn't add a lot of security, you have the file on your local machine, and upload it straight to your server. It can only be abused when you have both the pem file and access to a database of associated UDIDs of devices. That means your server must be hacked for that to happen. And if that's the case, you can always revoke the push certificate on the developer portal.

Let me know if that helps 👍

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
