### ISSUE TITLE
Enabling Apple Pay with Produce

### ISSUE THREAD

**Issue by getreup** [fastlane/fastlane#5100]
I see all the other services there, but is there a way to enable apple pay in an app through produce?

**Comment by vpolouchkine** [comment]
Pretty sure it's not possible at the moment.

**Comment by sogko** [comment]
Hi @vpolouchkine 

I'm wondering if there is a chance that this might get another look, it seems that something has changed since the last time this issue was reviewed.

I've investigated into the requests for enabling/disabling services in the Dev Portal (via `/account/ios/identifiers/updateService.action` and found the following services maps to the `featureType` value

Service Name | `featureType` | Available in v1.2.1
--------------|---------------|-------------------
App Groups | `APG3427HIY` | :white_check_mark:
Apple Pay | `OM633U5T5G` | :no_entry_sign:
Associated Domains | `SKC3T5S89Y` | :white_check_mark:
Data Protection | `dataProtection`  | :white_check_mark:
Game Center | `gameCenter` | :no_entry_sign:
HealthKit | `HK421J6T7P` | :white_check_mark:
HomeKit | `homeKit` | :white_check_mark:
iCloud | `iCloud` | :white_check_mark:
In-App Purchase |` inAppPurchase` | :no_entry_sign:
Inter-App Audio | `IAD53UNK2F` | :white_check_mark:
Personal VPN | `V66P55NK2I` | :white_check_mark:
Push Notifications | `push` | :white_check_mark:
SiriKit | `SI015DKUHP` | :no_entry_sign:
Wallet / Passbook | `pass` | :white_check_mark:
Wireless Accessory Configuration | `WC421J6T7P` | :white_check_mark:

Disclaimer: I am not familiar with fastlane/spaceship codebase and I have only looked into this under an hour to find a solution, I apologise if I appear ignorant in how the spaceship lib works, cos I am lol.
But I'd appreciate if someone familiar with the code would help to nudge to the right direction.

Looking at [spaceship/portal/app_service.rb](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/app_service.rb), it seems that there is a possibility to enable/disable Apple Pay service, along with other currently not supported services.

The HTTP request to __enable__ the above services:

```
https://developer.apple.com/services-account/<accountId>/account/ios/identifiers/updateService.action?
content-type=text/x-url-arguments&accept=application/json&
requestId=<requestId>&
userLocale=en_US&
teamId=<teamId>&
displayId=<displayId>&
featureType=<featureType>&
featureValue=yes
```

The HTTP request to __disable__ the above services:

```
https://developer.apple.com/services-account/<accountId>/account/ios/identifiers/updateService.action?
content-type=text/x-url-arguments&accept=application/json&
requestId=<requestId>&
userLocale=en_US&
teamId=<teamId>&
displayId=<displayId>&
featureType=<featureType>&
featureValue=no
```

Additional note: Currently in `v1.2.1`, the AppService uses a different `service_uri` for `push`, (i.e `account/ios/identifiers/updatePushService.action`), but it seems that currently there is no need for that. `push` service can be disabled/enabled using `updateService.action`

Hope that this gets looked into and allow us to enable more services through `produce`, because that would be great.

Cheers!

**Comment by sogko** [comment]
Awesome, the related PR #6820 that allows you to enable/disable Apple Pay services just got merged

**Comment by TKBurner** [comment]
@sogko Thanks for updating this thread 👍
