### ISSUE TITLE
Sigh Enterprise Failed Login

### ISSUE THREAD

**Issue by ohwutup** [fastlane/fastlane#5169]
Hello, I'm trying to use sigh with an enterprise only account and I am getting this error.
```
[!] Apple provided the following error info:
    authentication.failed
    Your session has expired.  Please log in.
```
Just to confirm, I have used sigh with non enterprise accounts with no trouble.
Am I doing something wrong? or was there never a fix made for this issue?

references: https://github.com/fastlane/fastlane/issues/3486#issuecomment-226232097

**Comment by vpolouchkine** [comment]
Potentially another report https://github.com/fastlane/fastlane/issues/5124

**Comment by tagyro** [comment]
*bump*  
I'm using two different developer accounts: a "norma" one and a enterprise one - the problem is with the enterprise account.
I understand that using an enterprise account you don't have access to iTunes Connect (TestFlight) but you can still distribute apps via hockey.
IMHO we should be able to use fastlane (match/sigh) even with an enterprise account, even though we won't be able to use pilot.

**Comment by ohwutup** [comment]
Closing this in favor of https://github.com/fastlane/fastlane/issues/5124.
