### ISSUE TITLE
When  we support gitlab-ci-multi-runner ?

### ISSUE THREAD

**Issue by FlyingNoob** [fastlane/fastlane#5243]
I hope fastlane can support gitlab-ci-multi-runner. 
gitlab-ci-multi-runner can solve the problem" somebody integration ci for self－host".

**Comment by hjanuschka** [comment]
we are using fastlane, and building with gitlab-ci and multi-runner, where do you see problems?


e.g `gitlab-ci.yml`


```bash
stages:
  - do_unit_test
  - do_build_testflight
  - do_screenshots


Release Build:
  dependencies: []
  stage: do_build_testflight
  artifacts:
    paths:
      - FiveXFive/fastlane/screenshots
      - FiveXFive/fastlane/logs
  script:
    - fastlane testflight
  tags: 
    - ios
  only: 
     - /^release-.*$/
     - master

Unit Tests:
  dependencies: []
  stage: do_unit_test
  artifacts:
    paths:
      - FiveXFive/fastlane/screenshots
      - FiveXFive/fastlane/logs
  script:
    - fastlane tests
  tags:
    - ios
  except:
    - /^cibuild.*$/

Screenshots:
  dependencies: []
  stage: do_screenshots
  artifacts:
    paths:
      - FiveXFive/fastlane/screenshots
      - FiveXFive/fastlane/logs
  script:
    - fastlane snapshot
  tags:
    - ios
  only:
    - /^screenshot-.*$/
```


having nearby zero logic in the `.gitlab-ci.yml` all the magic comes from `fastlane/Fastfile`

**Comment by FlyingNoob** [comment]
@hjanuschka Thanks ! It's so cool

**Comment by tanhuiya** [comment]
@hedjirog  Hi,I use fastlane in my githun-runner,and the runner is my computer ,I can do well in my project ,as well manully in gitlab-runner .But when I submit to gitlab ,the runner excute failed .here is full stack track

/Users/tanhui/.rvm/gems/ruby-2.2.3/gems/xcpretty-0.2.2/lib/xcpretty/parser.rb:383:in `===': invalid byte sequence in US-ASCII (ArgumentError)
from /Users/tanhui/.rvm/gems/ruby-2.2.3/gems/xcpretty-0.2.2/lib/xcpretty/parser.rb:383:in `update_test_state'
from /Users/tanhui/.rvm/gems/ruby-2.2.3/gems/xcpretty-0.2.2/lib/xcpretty/parser.rb:270:in `parse'
from /Users/tanhui/.rvm/gems/ruby-2.2.3/gems/xcpretty-0.2.2/lib/xcpretty/formatters/formatter.rb:83:in `pretty_format'
from /Users/tanhui/.rvm/gems/ruby-2.2.3/gems/xcpretty-0.2.2/lib/xcpretty/printer.rb:15:in `pretty_print'
from /Users/tanhui/.rvm/gems/ruby-2.2.3/gems/xcpretty-0.2.2/bin/xcpretty:80:in `block in <top (required)>'
from /Users/tanhui/.rvm/gems/ruby-2.2.3/gems/xcpretty-0.2.2/bin/xcpretty:79:in `each_line'
from /Users/tanhui/.rvm/gems/ruby-2.2.3/gems/xcpretty-0.2.2/bin/xcpretty:79:in `<top (required)>'
from /usr/local/bin/xcpretty:22:in `load'
from /usr/local/bin/xcpretty:22:in `<main>'
from /Users/tanhui/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
from /Users/tanhui/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
[09:24:37]: Exit status: 1
[09:24:37]: Your shell environment is not correctly configured
[09:24:37]: Instead of UTF-8 your shell uses US-ASCII
[09:24:37]: Please add the following to your '~/.bashrc':
[09:24:37]: 
[09:24:37]:        export LANG=en_US.UTF-8
[09:24:37]:        export LANGUAGE=en_US.UTF-8
[09:24:37]:        export LC_ALL=en_US.UTF-8
[09:24:37]: 
[09:24:37]: You'll have to restart your shell session after updating the file.
[09:24:37]: If you are using zshell or another shell, make sure to edit the correct bash file.
[09:24:37]: For more information visit this stackoverflow answer:
[09:24:37]: https://stackoverflow.com/a/17031697/445598

**Comment by KrauseFx** [comment]
@tanhuiya it tells you how to fix the error right in the error message. If that doesn't help, please submit a separate issue 👍

**Comment by tanhuiya** [comment]
@KrauseFx  oh,sorry ,I just add to wrong place ,thank you .
and inivite you to this https://github.com/fastlane/fastlane/issues/5884

**Comment by tanhuiya** [comment]
@KrauseFx  Why the error occurs , I just work fine in local. runner did not work with a same bash eniroment ?

**Comment by connorshea** [comment]
@KrauseFx @hjanuschka it'd be awesome to have a GitLab CI section in the Fastlane CI docs :)

**Comment by hjanuschka** [comment]
@connorshea https://github.com/fastlane/docs/pull/144 here we go :)
