### ISSUE TITLE
Error installing fastlane

### ISSUE THREAD

**Issue by lukaskollmer** [fastlane/fastlane#5313]
Running `sudo gem install fastlane` fails with the following output:

```bash
lukas-air:~ lukaskollmer$ sudo gem install fastlane
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/spaceship
```

I had fastlane installed before but I removed it (`sudo gem uninstall fastlane` because updating fastlane threw exactly the same error)

**Comment by KrauseFx** [comment]
Can you try manually deleting `/usr/bin/spaceship`?

**Comment by lukaskollmer** [comment]
@KrauseFx Doesn't work, `rm -f /usr/bin/spaceship` fails with `Operation not permitted`

**Comment by samuel-mellert** [comment]
Installing fastlane via bundler (http://bundler.io/) is a much nicer experience than directly installing the gem. Also I recommend using rbenv (https://github.com/rbenv/rbenv) for managing ruby installations. Makes it much easier to recover once you messed up your ruby environment. ;) 

Also, if you are not already using it oh-my-zsh (https://github.com/robbyrussell/oh-my-zsh) is the best shell environment I've used so far. I can highly recommend it!

**Comment by neonichu** [comment]
@lukaskollmer This likely happens because you updated the rubygems gem of your system ruby installation. The default one that ships with macOS customises the default binary directory, but if you update it to any other version (e.g. by doing `gem update —system`), you will lose that. `sudo gem install fastlane -n /usr/local/bin` should work as an alternative.

**Comment by lukaskollmer** [comment]
@neonichu Worked, thank you!
