### ISSUE TITLE
New 'tag' key for 'import_from_git' action

### ISSUE THREAD

**Issue by Gladkov-Art** [fastlane/fastlane#5420]
Hello!
### Suggestion
I'd like to suggest adding `tag` as new key to the `import_from_git` action.
### Motivation
Recently I have implemented reusable fastfile for our projects. Everything was cool until I decided to try match as code signing tool for one of our project. And I encountered a predictable problem, I couldn't simply modify my reusable fastfile, because it breaks code signing flow for the rest of our projects. So I think that 'tag' key would allow me to create versioning system for my reusable fastfile. 

I would like to try to make PR for this issue, if you find it reasonable. Thanks!

**Comment by asfalcone** [comment]
@Gladkov-Art Could you explain how you would use the `tag` option? I'm not sure I understand.

**Comment by Gladkov-Art** [comment]
@asfalcone sure, I can see it in following way:

I will make import of my reusable fastlane file: 
``` Ruby
import_from_git (
  url: 'git@github.com:fastlane/fastlane.git',
  tag: 'any_tag'
)
```
Fastlane checkouts my repository to commit with tag - `any_tag` and then import fastfile. 
This improvement will allow me to change my fastfile, add new tag and adopt my applications one by one.

**Comment by Liquidsoul** [comment]
Hi @Gladkov-Art,

Did you try to pass a tag to the `branch` option of `import_from_git`?

We use the `--branch` option of `git clone` in this action and you should be able to specify a tag as it is said in the [git documentation](https://www.git-scm.com/docs/git-clone):

> **--branch <name>**
**-b <name>**
Instead of pointing the newly created HEAD to the branch pointed to by the cloned repository’s HEAD, point to `<name>` branch instead. In a non-bare repository, this is the branch that will be checked out. `--branch` can also take tags and detaches the HEAD at that commit in the resulting repository.

Tell me if it works and if so we will update the documentation accordingly.
Thanks!

**Comment by Gladkov-Art** [comment]
Hi @Liquidsoul
Can confirm, it works! 👍

**Comment by Liquidsoul** [comment]
Awesome @Gladkov-Art ! Thank you !
@asfalcone : I've created PR #5533 which updates the documentation accordingly. Hope this helps 😃

**Comment by Gladkov-Art** [comment]
It solves my issue completely, thanks!

**Comment by KrauseFx** [comment]
Great, thanks everyone, fixed with https://github.com/fastlane/fastlane/pull/5533 👍
