### ISSUE TITLE
Can't recreate provisioning profile

### ISSUE THREAD

**Issue by chshapiro** [fastlane/fastlane#5540]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I created a provisioning profile for my app using `match development` but then I accidentally deleted it in Apple Developer Console. Now when I try to run `match development` again, it tells me that it can't find the provisioning profile and the only thing that will fix it is to run `match nuke`. I'm not ready to run that command yet. Is there anything else I can do to fix this problem? Also if I eventually want to change the user id for the repo, is that possible?

##### Complete output when running fastlane, including the stack trace and command used

```
+-----------------------+----------------------------------------------+
|                       Summary for match 0.6.1                        |
+-----------------------+----------------------------------------------+
| git_url               | git@github.com:xxxx/xxxx.git |
| type                  | development                                  |
| app_identifier        | com.xxx.testapp                            |
| username              | xxxx@xxxx.com                     |
| git_branch            | master                                       |
| keychain_name         | login.keychain                               |
| readonly              | false                                        |
| team_id               | xxxxx                                   |
| verbose               | false                                        |
| force                 | false                                        |
| shallow_clone         | false                                        |
| force_for_new_devices | false                                        |
| skip_docs             | false                                        |
+-----------------------+----------------------------------------------+

[17:36:28]: Cloning remote git repo...
[17:36:28]: 🔓  Successfully decrypted certificates repo
[17:36:28]: Verifying that the certificate and profile are still valid on the Dev Portal...
[17:36:31]: Installing certificate...
[17:36:32]: Installing provisioning profile...
[17:36:33]: Provisioning profile 'xxxxxx' is not available on the Developer Portal
[17:36:33]: for the user xxxx@xxxx.com
[17:36:33]: Make sure to use the same user and team every time you run 'match' for this
[17:36:33]: Git repository. This might be caused by deleting the provisioning profile on the Dev Portal
[17:36:33]: 🔒  Successfully encrypted certificates repo

Looking for related GitHub issues on fastlane/fastlane...

➡️  Invalid provisioning profile, not sure where Team ID is coming from
   https://github.com/fastlane/fastlane/issues/4234 [closed] 6 💬
   21 Apr 2016


[!] To reset the provisioning profiles of your Apple account, you can use the `match nuke` feature, more information on https://github.com/fastlane/fastlane/tree/master/match
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile: N/A

### Environment

fastlane version (run `fastlane -v`): 1.99.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? `rvm`

**Comment by vpolouchkine** [comment]
Running `match nuke development` is the recommended approach here.

**Comment by allenhumphreys** [comment]
`match nuke development` doesn't help in a mixed match/non-match team environment. It causes excessive amounts of strife by rejecting everyone's personal development certificates. Personally, I have avoided moving my team to an entirely match-based development solution simply because I need to nuke to get things in sync but it's hard to coordinate a change over across 3 continents without disrupting development for 2 days.

As a result, I only use match to manage our distribution keys, certificates, and profiles.

**Comment by TKBurner** [comment]
@allenhumphreys Thanks for the feedback. Are you deleting the profile in the Apple Developer portal as well in this case? If so, this is expected behavior but I'll make sure to bring it up with the core team. Thanks!

**Comment by allenhumphreys** [comment]
@TKBurner 

It seems like what happened to me was that when Xcode added a device to the dev portal, it invalidated the match provisioning profile. Once the profile was invalidated (marked yellow on the website), it was either no longer visible to match or match chose to handle it in this way.

Unfortunately, this behavior may have been due to an older version of match. I did get the error mentioned in the initial report, and I worked around it by checking out the match repository and deleting the provisioning profiles manually. Once I did that, match simply created new provisioning profiles for me :-)

I hope this helps.

**Comment by TKBurner** [comment]
@allenhumphreys Thanks for following up. That seems to make sense as behavior. The profile was invalidated, match ignored it. I think your best bet would have been running `match nuke development`

Thanks!

**Comment by allenhumphreys** [comment]
@TKBurner 

I wish there was something a little more fine grained than `nuke`. Like just being able to reset the profiles and not the certificates would be nice.

**Comment by TKBurner** [comment]
@allenhumphreys Thanks for the feedback. I'll make sure to talk to the core team 👍
