### ISSUE TITLE
fastlane will automatic change app version in itunes, but I don't want this,do it has a solution? 

### ISSUE THREAD

**Issue by njafei** [fastlane/fastlane#5587]
fastlane will automatic change app version in itunes, but I don't want this,do it has a solution?

**Comment by njafei** [comment]
desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "***",
        use_legacy_build_api:true,
    ) # Build your app - more options available
    deliver(force: true)
    # frameit
  end

I don't use this config,


Here is my problem,when my app is in review in itunes,if I use fastlane, it will stop review, and increase version,and this is not what I want,I don't want to stop review,just want to release my new app

can U help me?

**Comment by brockboland** [comment]
Hi other Brock!

@njafei this happens when you run `fastlane appstore`?

I haven't used `deliver` before, but that might be the default behavior. If your app has been submitted and is in review, I'm not sure why you would run this command again, though, so maybe we should back up a bit: what are you trying to use fastlane to do when the app is in review?

**Comment by brockklein** [comment]
Haha! Hello to you too other Brock! (Not a phrase I suspect either of us are accustomed to saying.)

@njafei I think @brockboland is 100% correct. since you have not run `deliver init` and customized the generated `Deliverfile` I suspect the default behavior of `deliver` when called in a `Fastfile` is to include `increment_version_number`.

I'm not sure if there's a way to disable that without running `deliver init` and setting up your `Deliverfile`.

That being said, it sounds like you're running Fastlane commands on an app that has already been submitted for review. While I suspect this is possible I'm not sure if it is advisable and I don't have any experience configuring Fastlane to ensure it doesn't remove the app from review.

Also, if you do not use that config there's still not much we can do to help you troubleshoot unless you post the config you do use.

**Comment by njafei** [comment]
@brockboland  @brockklein 
my team is in a big sell company,so delay of release app will be a big problem, especially  the Market team has a schedule, to avoid be refused by apple review team by various reason(U konw, so many reason),my team submit a release version everyday, but we will not let it be in review, only make sure binary ipa is ok, so I want to do this.
