### ISSUE TITLE
Could not create tester using pilot

### ISSUE THREAD

**Issue by marufice** [fastlane/fastlane#5674]
When i trying to create an external tester for an app using pilot tool through Terminal in my local environment, then showing the following error in console:
Could not create tester marufice@gmail.com
[marufice@gmail.com]: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Forbidden"]}, "statusCode"=>"ERROR"}

How can i resolve this issue?

**Comment by TKBurner** [comment]
Hi @marufice Can you share your full input and output? I'd love to take a look. Thanks!

**Comment by jaleksynas** [comment]
This is long standing issue:
#3239
#3258
#1895 

This issue is usually due to the access level of your account.  Without admin access "create" operations fail since pilot is hitting a secure account level URL.  Since external testers are application specific this needs a bit of rework... I have done a PR for this in the past, but have not had the time to add the tests required to get it approved.  The functional part of the change is in the spaceship code. 

https://github.com/fastlane/fastlane/pull/5145

I could use some help taking up the effort on this (the code works for my technical role account) and get it approved!

**Comment by TKBurner** [comment]
@jaleksynas Would love to see a PR on this! @marufice Would you be willing to test if @jaleksynas has something that should make this possible?

Otherwise you should make sure you have an iTC admin account and as was mentioned you won't see this issue anymore. Thanks!

**Comment by bencollier** [comment]
Pretty sure this one is still an issue.

**Comment by TKBurner** [comment]
@bencollier Thanks for bumping this. We'll leave this ticket open then 👍 👍

**Comment by ahmedgharib** [comment]
such a bummer that even the branch got deleted for this
