### ISSUE TITLE
frameit the frame name wrong

### ISSUE THREAD

**Issue by ZacksTsang** [fastlane/fastlane#5805]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
when i download the frame from apple, the name is wrong.
##### Complete output when running fastlane, including the stack trace and command used

```
[10:04:28]: You can download new templates from 'https://developer.apple.com/app-store/marketing/guidelines/#images'
[10:04:28]: and store them in '/xxxxxx/.frameit/devices_frames'
[10:04:28]: Missing file: 'iPhone-6s-Plus-Space-Gray-vertical.png'
```
and download name is `iPhone_6_Plus_Vert_SpaceGray_sRGB_0914.psd`, how can i know the names? 

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by cratrifork** [comment]
I had a similar issue with the iPad Pro silver having a wrong name. 

You can fix it by renaming the file you downloaded off Apples website to the one required - In your example that would be:

Rename: **iPhone_6_Plus_Vert_SpaceGray_sRGB_0914.psd**   to   **iPhone-6s-Plus-Space-Gray-vertical.psd** (and put it in ~/.frameit/devices_frames )

When you run frameit, it converts the psd to png.

It might be that the offset and width is wrong because of the new file, but you can adjust this in:
/Library/Ruby/Gems/2.0.0/gems/frameit-2.7.0/lib/frameit/offsets.rb - Might need sudo to change the values.

I hope this helps.

**Comment by ZacksTsang** [comment]
@cratrifork Thanks for help

**Comment by TKBurner** [comment]
@cratrifork Thanks so much for stepping in on this and helping out. Hope that you have a great day! 👍

**Comment by KrauseFx** [comment]
I'm actively working on a re-write of _frameit_ that supports all the latest devices with https://github.com/fastlane/fastlane/pull/6597, please subscribe to the pull request to stay up to date. We hope to have a new version ready this week  🚀
