### ISSUE TITLE
Supporting activesupport  5

### ISSUE THREAD

**Issue by chrhsmt** [fastlane/fastlane#5809]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I develop application incorpolated with fastlane, and that app needs activesupport ver 5.
But now that gem in fastlane is locked version < 5 (ref #5294 , #5298 ).
I need conditioning by RUBY_VERSION.

**Comment by vpolouchkine** [comment]
Perhaps @neonichu can provide a workaround, per https://github.com/fastlane/fastlane/pull/5298

**Comment by neonichu** [comment]
Unfortunately, I don't think this can really be worked around effectively. Using `RUBY_VERSION` does not work, see [this comment](https://github.com/fastlane/fastlane/pull/5810#issuecomment-241542344) for more information.

IIRC, @segiddins was working on handling this better in rubygems, but even that would not help as long as the goal is to support macOS system ruby, because that also ships with an old version of rubygems.

**Comment by segiddins** [comment]
I've only been working on fixing it in Bundler.

**Comment by neonichu** [comment]
@segiddins that's actually better, because Bundler doesn't ship with system Ruby, does it?

**Comment by segiddins** [comment]
Not yet

**Comment by TKBurner** [comment]
Thanks! @segiddins Keep us updated 👍

**Comment by cpunion** [comment]
Is there any progress on this? Or which thread in Bundler can track this?

**Comment by segiddins** [comment]
This is implemented on bundler master, will go out in bundler 1.14

**Comment by cpunion** [comment]
@segiddins 👍

**Comment by TKBurner** [comment]
@segiddins Awesome! 👍

**Comment by cpunion** [comment]
`bundler v1.14.0.pre.1` was released, can we test it?

**Comment by cpunion** [comment]
I can test it, but don't know how to test.
