### ISSUE TITLE
unauthorized for supply uploading metadata to google play

### ISSUE THREAD

**Issue by CPPTET** [fastlane/fastlane#5927]
Tried with two different account with same permission.
one is ok, but another one failed with unauthorized.
command used: 
supply --skip_upload_apk --skip_upload_images --skip_upload_screenshots --verbose

Error:
```
/Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/google-api-client-0.9.12/lib/google/apis/core/http_command.rb:208:in `check_status': [!] Unauthorized (Google::Apis::AuthorizationError)
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/google-api-client-0.9.12/lib/google/apis/core/api_command.rb:104:in `check_status'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/google-api-client-0.9.12/lib/google/apis/core/http_command.rb:179:in `process_response'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/google-api-client-0.9.12/lib/google/apis/core/http_command.rb:286:in `execute_once'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/google-api-client-0.9.12/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/google-api-client-0.9.12/lib/google/apis/core/http_command.rb:104:in `block in execute'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/google-api-client-0.9.12/lib/google/apis/core/http_command.rb:96:in `execute'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/google-api-client-0.9.12/lib/google/apis/core/base_service.rb:346:in `execute_or_queue_command'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/google-api-client-0.9.12/generated/google/apis/androidpublisher_v2/service.rb:91:in `commit_edit'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/supply-0.7.0/lib/supply/client.rb:100:in `commit_current_edit!'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/supply-0.7.0/lib/supply/uploader.rb:31:in `perform_upload'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/supply-0.7.0/lib/supply/commands_generator.rb:39:in `block (2 levels) in run'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/fastlane_core-0.50.2/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/supply-0.7.0/lib/supply/commands_generator.rb:57:in `run'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/supply-0.7.0/lib/supply/commands_generator.rb:15:in `start'
	from /Users/Terry/.rvm/gems/ruby-2.2.3@global/gems/supply-0.7.0/bin/supply:6:in `<top (required)>'
	from /Users/Terry/.rvm/rubies/ruby-2.2.3/bin/supply:23:in `load'
	from /Users/Terry/.rvm/rubies/ruby-2.2.3/bin/supply:23:in `<main>'
```

**Comment by nafu** [comment]
@CPPTET 

Did you follow the setup step in the same way for two accounts?
https://github.com/fastlane/fastlane/tree/master/supply#setup

**Comment by CPPTET** [comment]
@nafu 
I did not choose the Release Manager role for that. But I've checked these permission for both account. And the failed one can perform the Supply init. but if I run "supply --skip_upload_apk --skip_upload_images --skip_upload_screenshots --verbose", it shows unauthorized error. Do you think if I need extra permission for resolving this issue?

<img width="364" alt="screen shot 2016-08-29 at 1 23 39 pm" src="https://cloud.githubusercontent.com/assets/21301233/18041481/1219e11a-6dec-11e6-86fa-1742f1a6713e.png">

**Comment by nafu** [comment]
@CPPTET 

I think so.
It's worth to try giving them release manager permission because it throws [Google::Apis::AuthorizationError](https://github.com/google/google-api-ruby-client/blob/557057c754d446b18f08cf719a84b68d7e55bd15/lib/google/apis/core/http_command.rb#L208).

The flow from supply commands is

1. [Supply::Setup.new.perform_upload](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/commands_generator.rb#L39)
  - [perform_upload](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/uploader.rb#L3-L33)
1. [client.commit_current_edit!](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/uploader.rb#L31)
  - [commit_current_edit!](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/client.rb#L96-L104)
1. [call_google_api android_publisher.commit_edit](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/client.rb#L100)
  - [commit_edit](https://github.com/google/google-api-ruby-client/blob/557057c754d446b18f08cf719a84b68d7e55bd15/generated/google/apis/androidpublisher_v2/service.rb#L82-L92)

**Comment by asfalcone** [comment]
@CPPTET I believe you do need the "Manage Production APKs" checkbox checked. Can you try with that and let us know? Thanks 👍

**Comment by CPPTET** [comment]
@nafu It is fine with release manager. Thanks.
@asfalcone May I know why the "Manage Produciton APKs" permission is needed? Because updating metadata will also update the change logs? Is there an option to disable updating the change log? Thanks.

**Comment by asfalcone** [comment]
@CPPTET I'm not 100% sure why certain permissions are required since the authorization and errors are governed by Google. We use this [google api client](https://github.com/google/google-api-ruby-client/) if you want to do more digging. 

I'm going to close this issue for now since this is working as expected. The last item in our [setup guide](https://github.com/fastlane/fastlane/tree/master/supply#setup) says that Release Manager role is required. 👍
