### ISSUE TITLE
[Feature] Add support for hidden -increment-minor-version option in increment_build_version action

### ISSUE THREAD

**Issue by thorstenhuhn** [fastlane/fastlane#596]
Apple's `agvtool` has a hidden option `-increment-minor-version` I use to bump my build version.
```shell
agvtool next-version -increment-minor-version -all
```
will bump 35.3 to 35.4, while the default behaviour would bump to 36.

I would love to see a `minor: true|false` option in the `increment_build_version` action. It might be useful for others too.

**Comment by truth3** [comment]
One thing I am doing in the, is setup two different lanes for bumping the build number and minor version as I am not quite sure I want to bump the version / build number for each target I build (since there is close to 40 of them) :)

**Comment by thorstenhuhn** [comment]
Well, I need those two parts of the build version for organizational reasons but I can workaround this "issue" by doing the calculation on my own and using the `increment_build_number(build_number: <calculated value>)` syntax. I could also call `agvtool` directly.

The remaining question is, if it makes sense to support a hidden (and maybe deprecated?) feature.
If yes, `bump_type: "minor"` would reflect the syntax of the `increment_version_number` action and would prevent the action from cutting the functionality of the underlying tool.

**Comment by Liquidsoul** [comment]
Hi @thorstenhuhn 

Does adding the possibility to trim the version number to the part you want in `increment_version_number` would solve the problem ?
Because right now, if you respect the `major.minor.patch` version format you can bump any part using the corresponding `bump_type`.
I was thinking about adding a `trim` option to this to be able to remove zeroed trailing parts in a version number (e.g. bumping 34.2 using `major` would result in 35)

**Comment by ohwutup** [comment]
hey everyone! i am going to close this issue for now as its been a while since there has been some activity. please feel free to reopen it if necessary! :8ball:
