### ISSUE TITLE
Fastlane command fails immediately becuase of mismatching json versions

### ISSUE THREAD

**Issue by 92tonywills** [fastlane/fastlane#6269]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Fastlane immediately quits when any version of json newer than the ruby bundle version is installed.
##### Complete output when running fastlane, including the stack trace and command used

```
/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2274:in `check_version_conflict': can't activate json-2.0.2, already activated json-1.8.3 (Gem::LoadError)
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1403:in `activate'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:89:in `block in require'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `each'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `require'
    from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.0/lib/fastlane_core.rb:1:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane.rb:1:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/lib/fastlane/cli_tools_distributor.rb:14:in `take_off'
    from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.104.0/bin/fastlane:5:in `<top (required)>'
    from /usr/local/bin/fastlane:23:in `load'
    from /usr/local/bin/fastlane:23:in `<main>'
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
update_fastlane

fastlane_version "1.95.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["CRASHLYTICS_API_TOKEN"] = "key_here"
    ENV["CRASHLYTICS_BUILD_SECRET"] = "secret_here"
    ENV["MATCH_READONLY"] = "true"
    ENV["MATCH_FORCE_FOR_NEW_DEVICES"] = "true"
    ENV["GYM_CLEAN"] = "true"
    ENV["GYM_SILENT"] = "true"
    cocoapods
  end

  desc "Just build the project"
  lane :build do
    match(type: "development")
    gym(scheme: "ManchesterCareers", configuration: "Debug")
  end

  desc "Runs all the tests"
  lane :test do
    match(type: "development")
    scan(scheme: "ManchesterCareers")
  end

  desc "Make an internal Fabric Beta release"
  lane :internalbeta do
    increment_build_number
    match(type: "adhoc")
    gym(scheme: "ManchesterCareers")
    crashlytics(groups: "dreamrs-ios")
  end

  desc "Make an full Fabric Beta release"
  lane :beta do
    increment_build_number
    match(type: "adhoc")
    gym(scheme: "ManchesterCareers")

    puts "Enter release notes here, end input with ctrl-D"
    releaseNotes = $stdin.read
    crashlytics(groups: "dreamrs-ios, manchester-careers", notes: releaseNotes)
  end
```
### Environment

fastlane version (run `fastlane -v`):
fastlane 1.104.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by PetrosIchor** [comment]
I get this all the time.  Removing the newer version is the easiest route to go: 

`gem uninstall json -v2.0.2`

It'll stop conflicting with 1.8.3 (which on my systems, I can't remove).

**Comment by KrauseFx** [comment]
Also to prevent this problem in the future, we recommend using a Gemfile: https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

**Comment by 92tonywills** [comment]
Removing json 2.0.2 is not a fix, any of my other gems could depend on that version of json.
Also, other gems in fact do work under this configuration (cocoapods for instance).

Using a Gemfile would fix this problem I know, but it seems like over kill IMO just to run one script - is there no way to do this at the application level?

**Comment by TKBurner** [comment]
@92tonywills Thanks for following up. For now the Gemfile is the best path forward. I don't know of a way to fix this at an application level, I suppose you could force it in RVM by switching rubies each time you run.

**Comment by marija17** [comment]
@KrauseFx Could you elaborate on using the Gemfile to fix this?  Do you put a particular json version in the Gemfile?

I've tried

```
source "https://rubygems.org"

gem "fastlane"
gem "json", "1.8.3"
```

and I'm still getting the same error as above.

**Comment by TKBurner** [comment]
@marija17 I think you might need to use a Gemfile.lock https://richonrails.com/articles/how-does-the-gemfile-lock-file-work

**Comment by KrauseFx** [comment]
@marija17 Yes, create the `Gemfile` in your project's directory, and run `bundle install`. From then on use `bundle exec fastlane [something]` to run _fastlane_ 👍

**Comment by iblacksun** [comment]
@KrauseFx  Same issue here, if i run ```fastlane init``` in a new project, should i create gemfile first?

**Comment by KrauseFx** [comment]
Hey everyone, we've been working on a new way to install and use fastlane, all you have to do is to download `fastlane.zip` and double click the `install` file. This will install fastlane with all its Ruby and OpenSSL dependencies, and should all work out of the box.
We just finished building this, and would love your early feedback on this beta. Please let us know how it works for you and if you run into any problems :+1: 
Download the latest version [here](https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/latest.zip).

**Comment by Damnum** [comment]
Awesome, I had the same problem, installed the package, and it works like a charm. Thanks, very handy!

**Comment by gigi-mohemian** [comment]
Worked like a charm for me as well 👍

**Comment by kexoth** [comment]
I had the same issue with mismatches on json & I solved it with `gem cleanup` & now I use only the newest gems & don't have any issues. 😉

**Comment by mikecole20** [comment]
`gem cleanup` solved the problem for me, too. Thanks, @kexoth!

**Comment by lferro9000** [comment]
The recommended "bundle install" is generating an huge amount of warnings and errors:

The git source `git://github.com/GateGuru/xcoder.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/GateGuru/xcoder.git
fatal: Not a git repository (or any of the parent directories): .git

Retrying `git fetch --force --quiet --tags 'git://github.com/GateGuru/xcoder.git' "refs/heads/*:refs/heads/*"` due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git fetch --force --quiet --tags 'git://github.com/GateGuru/xcoder.git' "refs/heads/*:refs/heads/*"` in directory /usr/local/lib/ruby/gems/2.3.0/cache/bundler/git/xcoder-5c3e7b9ff0cecbb074b8d33dd89f1f17dfbc6a3a has failed.
If this error persists you could try removing the cache directory '/usr/local/lib/ruby/gems/2.3.0/cache/bundler/git/xcoder-5c3e7b9ff0cecbb074b8d33dd89f1f17dfbc6a3a'fatal: Not a git repository (or any of the parent directories): .git

Retrying `git fetch --force --quiet --tags 'git://github.com/GateGuru/xcoder.git' "refs/heads/*:refs/heads/*"` due to error (3/4): Bundler::Source::Git::GitCommandError Git error: command `git fetch --force --quiet --tags 'git://github.com/GateGuru/xcoder.git' "refs/heads/*:refs/heads/*"` in directory /usr/local/lib/ruby/gems/2.3.0/cache/bundler/git/xcoder-5c3e7b9ff0cecbb074b8d33dd89f1f17dfbc6a3a has failed.
If this error persists you could try removing the cache directory '/usr/local/lib/ruby/gems/2.3.0/cache/bundler/git/xcoder-5c3e7b9ff0cecbb074b8d33dd89f1f17dfbc6a3a'fatal: Not a git repository (or any of the parent directories): .git

Retrying `git fetch --force --quiet --tags 'git://github.com/GateGuru/xcoder.git' "refs/heads/*:refs/heads/*"` due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git fetch --force --quiet --tags 'git://github.com/GateGuru/xcoder.git' "refs/heads/*:refs/heads/*"` in directory /usr/local/lib/ruby/gems/2.3.0/cache/bundler/git/xcoder-5c3e7b9ff0cecbb074b8d33dd89f1f17dfbc6a3a has failed.
If this error persists you could try removing the cache directory '/usr/local/lib/ruby/gems/2.3.0/cache/bundler/git/xcoder-5c3e7b9ff0cecbb074b8d33dd89f1f17dfbc6a3a'fatal: Not a git repository (or any of the parent directories): .git
Git error: command `git fetch --force --quiet --tags 'git://github.com/GateGuru/xcoder.git' "refs/heads/*:refs/heads/*"` in directory
/usr/local/lib/ruby/gems/2.3.0/cache/bundler/git/xcoder-5c3e7b9ff0cecbb074b8d33dd89f1f17dfbc6a3a has failed.
If this error persists you could try removing the cache directory
'/usr/local/lib/ruby/gems/2.3.0/cache/bundler/git/xcoder-5c3e7b9ff0cecbb074b8d33dd89f1f17dfbc6a3a'

**Comment by PetrosIchor** [comment]
I believe you posted in the wrong issue.  Your issue is git related.

**Comment by KrauseFx** [comment]
Alright, let's close this issue then 👍
