### ISSUE TITLE
I already install and update to the latest version but execute `fastlane -v` show me the version is 1.101.0

### ISSUE THREAD

**Issue by FlyingNoob** [fastlane/fastlane#6284]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I installed the fastalne latest version . But when I execute `fasten -v` it show me the version is 1.101.0.
I'm sure when I install fastlane version is 1.104.0.
The fabric show me the version 1.104.0 is installed.

### Environment

fastlane version (run `fastlane -v`):

1.101.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
 No
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rvm
![7130cb15-8713-421a-a36c-ef0590dcd130](https://cloud.githubusercontent.com/assets/9291649/18813955/922e5f72-833e-11e6-9e5b-0eaa553b6142.png)

**Comment by ohwutup** [comment]
Hey @FlyingNoob! Thanks for raising the issue! 

It looks like you might have two versions of _fastlane_ installed. From the info you are sharing it looks like `rvm` has version 1.101.0 installed, while the Fabric Mac app has installed 1.104.0 for you. 

Because you have `rvm` using `sudo` in your `gem update` says there is nothing to update because the `sudo` part implies that the gem you are trying to update is in your system ruby rather than `rvm`. The reason why the Fabric app and your command line differ as far as what they are showing installed is likely because `rvm` comes before `usr/local/bin/` in your `PATH` variable. 

What I would recommend doing here is do a `gem uninstall fastlane` in your terminal _without `sudo`_ and then when you do `which fastlane` you should see `/usr/local/bin/fastlane` as the path and if you do `fastlane -v` on the command line, you should get 1.104.0. 

Apologies for the confusion here, please let us know if you have any questions about this moving forward! 🐙 😄

**Comment by FlyingNoob** [comment]
@ohwutup Thanks for your help ! I already found this problem.

**Comment by TKBurner** [comment]
@FlyingNoob Awesome! Really glad to hear you got up and running! 👍
