### ISSUE TITLE
Providing a detailed error message to slack

### ISSUE THREAD

**Issue by jamyc** [fastlane/fastlane#6292]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I'm forcing a failing build and get a generic exception in Slack:
`Error building the application - see the log above`

A couple lines above that (in the Jenkins console output) it shows the error perfectly fine:

`[31m[x] [0m/Users/[USER]/.jenkins/workspace/Fastlanedev/Fastlane-integration/ViewController.swift:16:9: [31muse of unresolved identifier 'prnt'[0m`

Is there any possible way to either:
- Provide a link to the failing Jenkins build
- Provide a more detailed message
### Configuration Files

Fastfile:

``` ruby
  desc "Experimental dev lane"
  lane :dev do
    gym(scheme: "Fastlane-integration", use_legacy_build_api: true)
slack(
  message: "Build succeeded",
  channel: "#fastlane",
  success: true,
  payload: {
    'Build Date' => Time.new.to_s,
    'Built by' => 'Jenkins',
  },
  default_payloads: [:git_branch, :git_author]
)
  end

  error do |lane, exception|
     slack(
       message: exception.to_s,
       success: false
     )
  end
```
##### fastlane 1.104.0

Running the dev lane with a build step in Jenkins:

**Comment by TKBurner** [comment]
@jamyc Great to hear from you! I think this could be better too. Are you interested in submitting a PR? This seems like a great place to contribute. Thanks!

**Comment by thiagofelix** [comment]
@jamyc you might be able to get the link to the Jenkins build using the environment variable `BUILD_URL` . 

More information on the [Jenkins documentation](https://wiki.jenkins-ci.org/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-JenkinsSetEnvironmentVariables)

**Comment by jamyc** [comment]
@TKBurner Unfortunately, I won't be able to get to a PR request to implement any of this.

@thiagofelix Thank you for your suggestion, that worked out perfectly fine!

**Comment by netbe** [comment]
@jamyc and @TKBurner  was there a PR done/merged?

**Comment by jamyc** [comment]
@netbe Not that I know of. I used the suggestion of @thiagofelix to include the BUILD_URL in the slack message.

**Comment by thiagofelix** [comment]
From the original request
- [x] Provide a link to the failing Jenkins build
As @jamyc mentioned this one can be gathered from environment variables, most of the CI applications expose few env vars which can be used to get more information about the build. Accomplished without changing fastlane

- [ ] Provide a more detailed message
This one is more interesting because Gym is capturing the xcodebuild output and bubbling only a small message to the error block. 

I am working on a PR to extend the FastlaneError class that carry the exception to have a extra field containing the error output (generated by xcode). eg:

**Badly behaving lane:**
```
lane :build  do
    gym(..)
end

error do |lane, exception|
    slack(
       message: exception.to_s,
       success: false, 
       payload: { "Output" => exception.error_info.to_s }
    )
end
```

**Slack Message:**
![image](https://cloud.githubusercontent.com/assets/117622/22717931/f1dc4d34-ed84-11e6-8c17-145d3fee1975.png)

Of course the `Output` will be bigger than the preview image, but it helps to visualize how it would look like.

@jamyc That should give you access to the xcodebuild entire output (usually from xcpretty), although it is not perfect (you need to scan the output to find out why it failed) but at least doesn't hide the information. It will be nice to hear your feedbacks/thoughts on this kind of approach.

@TKBurner I'll be happy to hear from you as well if you think it is a good idea.

Thanks
