### ISSUE TITLE
bundle exec: wrong recommendation on how to run fastlane

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/fastlane#6308]
Via https://twitter.com/a2/status/780707046509449216

The recommended command seems wrong
![image](https://cloud.githubusercontent.com/assets/869950/18884873/2c4b9a10-849e-11e6-98d5-86c51a8e68e4.png)

**Comment by mfurtak** [comment]
`fastlane bundle exec snapshot reset_simulators` is not a good command to run :smile:

If they were running `bundle exec fastlane snapshot reset_simulators`, then the `return if ENV['BUNDLE_BIN_PATH']` check would prevent the warning message from being shown.

This message is a bit strange, but that's because it got strange input to start with. I'm not sure there's anything to fix here.

**Comment by KrauseFx** [comment]
Yeah, agreed, let's close this 👍
