### ISSUE TITLE
beta-reports-active entitlement

### ISSUE THREAD

**Issue by mgrilloteravisiongames** [fastlane/fastlane#675]
Hi all!! I've managed to succesfully create and upload an ios build of my project, thank you very much, this is a really helpful tool. I just have a question about the entitlements, the 'beta-reports-active' has been necesary so far to upload the build, however, as far as I remember, I haven't set this entitlement anywhere, so, is it possible that this is set by gym?, if that's so, how can I remove it from the compilation?

Best Regards

**Comment by ohwutup** [comment]
hey @mgrilloteravisiongames apologies for the long time since you opened this issue. is this still something you are experiencing? there have been a lot of releases and updates to fastlane since this issue was opened, would you mind updating and trying again? if you are still having the issue, please reopen it and paste in any output that fastlane prints out for you upon the error.

thanks!
