### ISSUE TITLE
Set 'log: true' while calling 'Fastlane::Actions.sh' if CLI option --verbose

### ISSUE THREAD

**Issue by GoodMirek** [fastlane/fastlane#6878]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I found it difficult to troubleshoot errors like:
<br>`ERROR [2016-11-06 03:34:20.16]: Shell command exited with exit status 48 instead of 0.`<br>
which are returned while running action e.g. `create_keychain`
Currently, shell command is called like this:
<br>`Fastlane::Actions.sh("security create-keychain -p #{escaped_password} #{escaped_name}", log: false)`<br>

Would you agree to set `log: true` if command line option `--verbose` is specified?
Or do you prefer another way for setting the `log: true`?
Please may you let me know so I can submit a pull request?

**Comment by KrauseFx** [comment]
Yeah, I like the idea of having log being true if not specified otherwise 👍 
Do you think there will be any side-effects?

**Comment by KrauseFx** [comment]
For actions like the keychain, we can't just print the output, as it also contains the password. This shouldn't show up in build logs, even for `verbose` mode

**Comment by hjanuschka** [comment]
how about adding `--troubleshoot` - wich enforces `true` on the `sh` action and also sets `verbose` - so you can manually choose it.

**Comment by GoodMirek** [comment]
I like the `--troubleshoot` option.

If even more safety was desired, we could impose interactive user confirmation asking the user whether they really desire to display sensitive info, like the confirmation required in case of `match nuke`.
Also, the `--troubleshoot` option might be ignored if is_ci is true.

**Comment by milch** [comment]
> If even more safety was desired, we could impose interactive user confirmation asking the user whether they really desire to display sensitive info, like the confirmation required in case of match nuke.

Yes, I very much agree. Some users might not realize, enable it on CI (or wherever) and leak information. There's also the issue of people wanting to be helpful and copying the output with `--troubleshoot` to their issue/PR. 

- When running on CI, I wouldn't ignore the option, but fail and let the user know that this option needs to be disabled on CI
- Otherwise there should be an interactive confirmation telling the user not to copy/paste the output anywhere w/o double checking and removing all passwords from the text and wether they are sure they really want to run with `--troubleshoot`

**Comment by GoodMirek** [comment]
Solved via #6889.
