### ISSUE TITLE
[New action] "force_sign": Setup Xcode project's code signing settings by force 💪

### ISSUE THREAD

**Issue by p4checo** [fastlane/fastlane#7136]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

This issue is to propose a new custom action which enables iOS workflows to change the Xcode project's code signing settings "by force 💪" before building a target.

This is especially useful to avoid having to configure the Xcode project with a "static" set of code signing configurations for:

- Provisioning Style (Xcode8+): Manual / Automatic 
- Team ID
- Provisioning Profile UUID (Xcode 7 and earlier) and Name (Xcode8+)
- Code Signing Identity: iPhone Development / iPhone Distribution

By being able to configure this before each build (e.g. `gym` call), it allows having separate sets of code signing configurations on the same project without being "intrusive".

Some practical scenarios can be for example: 
- Xcode project in which two different Apple Developer accounts/teams are required (e.g. 1 for Development and 1 for Release)
- shared Xcode project where teams have different code signing configurations (e.g. Automatic vs Manual Provisioning Style)

The action can be found at https://github.com/Mindera/fastlane-actions/blob/master/force_sign.rb

Any feedback is welcome! 👍 

Credits to @portellaa for helping me do this ❤️

**Comment by PetrosIchor** [comment]
Big supporter of this.  I've actually taken your work and been using it in production for the last couple days.  

For my needs, I've also added the following: 
bundle_identifier = $(PRODUCT_BUNDLE_IDENTIFIER)
product_name = $(TARGET_NAME)

I also updated the development_team environment variable:
TEAM_ID => FASTLANE_TEAM_ID (shared with match)

I've been thinking about other ways to build out this action or remove redundancies in my environment variables. Some ideas:
**Sharing Gym** _(could also use the 'XCODE_* env variables)_
- SCHEME => GYM_SCHEME
- BUILD_CONFIGURATION => GYM_CONFIGURATION
- PROJECT_PATH =>  GYM_PROJECT

**Sharing Match**
- PROVISIONING_PROFILE_SPECIFIER => $(sigh_com.myapp.id_appstore_profile-name)
- PROVISIONING_PROFILE_UUID => $(sigh_com.myapp.id_appstore)

CODE_SIGN_IDENTITY could also be linked to GYM_CODE_SIGN_IDENTITY. However, I've had problems using that gym function in the past and feel it might create conflicts. 

Sharing Gym and Match variables might limit some flexibility.  Assuming you are using both Gym and Match though, there might be a more elegant solution.

**Comment by p4checo** [comment]
Thanks for your inputs @PetrosIchor! 

It's really cool that you are already using it in production! 😉 

Actually, in one of our projects we also change the `PRODUCT_BUNDLE_IDENTIFIER`, but we do it in a separate action and change the `CFBundleIdentifier` on the Info.plist directly. Since it's intimately related with code signing, perhaps it makes sense to add it to `force_sign`.

As for the `PRODUCT_NAME`, since it's not related with code signing I would perhaps leave it out (at least if this action remains being called `force_sign` 😛).

Regarding the default environment variables for the arguments, we initially thought about using dedicated variables just for `force_sign` but then ended up using these ones because they more or less mirror Xcode's (we were also not liking the other options 😅 ).

We think that this gives the user more flexibility (as you well said) to define these without being "dependent" on another tool by default. It can however make sense to define them so that they are designed to the most common workflow (e.g. before `gym` and after `match`).

Anyway, feel free to open a PR! 😉👍 

@portellaa, what are your thoughts?

**Comment by portellaa** [comment]
Hey @PetrosIchor 👋

Thanks for sharing 👍🙌 and sorry for the delay 

I agree with @p4checo, it makes sense to integrate the `PRODUCT_BUNDLE_IDENTIFIER` in this action, since they are related.
Thanks for noticing that, as @p4checo said, we have a different action so it never crossed our minds.

Regarding the `PRODUCT_NAME`, i think it doesn't makes too much sense to include it in this action, however we could rename the action to something else and include this. I would prefer to keep this separated, but let's find a cool name for it and make it just one action 😃 

About the environment variables, i don't have a formed opinion about this, but if we use the same variable, since we run this before gym, are those variables ready to use when we run this action?
I agree to use shared values between the other actions, and if we want to change it, we have always the option to send them as parameter.

About the match variables, i didn't understand very well what is the idea. I don't understand this:
- PROVISIONING_PROFILE_SPECIFIER => $(sigh_com.myapp.id_appstore_profile-name)
- PROVISIONING_PROFILE_UUID => $(sigh_com.myapp.id_appstore)

For example, these values, `sigh_bundle-identifier_<type>_profile-name`, they depend on the match type, we can assume those values, right?
Don't know, but it's possible 👅 that i making confusion here.

Again, thanks a lot for the contribution and as @p4checo said, feel free to open a PR, more than free 👅 

🙌

**Comment by KrauseFx** [comment]
Hey this looks great, thanks for sharing this. Have you thought about providing this as a fastlane plugin? I'm sure a lot of people would find this very useful 👍

**Comment by portellaa** [comment]
Hey @KrauseFx 

Thanks a lot for the support 😃 👍 
We will work on that to make that change.
We think it needs a few tweaks in the action. We'll make them and submit the plugin.

@p4checo what do you think?

**Comment by p4checo** [comment]
Hi guys!
Yes, we can definitely provide this as a plugin. Will update this issue as soon as it's available 😉

**Comment by portellaa** [comment]
Hello,

Sorry for all the delay and inactivity regarding this issue and the plugin creation.

We manage to finish that and we have the repo with the plugin ready. [Repo link](https://github.com/Mindera/fastlane-plugin-cosigner).
We also deploy it to rubygems [link](https://rubygems.org/gems/fastlane-plugin-cosigner)

@KrauseFx ☝️ 

Many thanks to @p4checo @PetrosIchor and @KrauseFx for all the time spent reviewing this.

🍻
