### ISSUE TITLE
Fastlane incorrectly reports update available when installed via Homebrew

### ISSUE THREAD

**Issue by andybee** [fastlane/fastlane#7342]
When installing fastlane via Homebrew:

`brew cask install fastlane`

Running fastlane always returns the following message, despite no update being available:

```
$ fastlane
Fastlane update available
Please run `brew cask reinstall fastlane`
```

This is because, despite the latest cask installing bundle v1.1, the contents of `~/.fastlane/bin/VERSION` reads `1.0` instead of `1.1`.

I'm struggling to track down where the `VERSION` file exists and/or is generated within the fastlane codebase to attempt a pull request. I'm happy to attempt to resolve the issue, but some initial guidance would be greatly appreciated.

**Comment by andybee** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.1 (16B2657)                  |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| deliver             | 1.16.1  | ✅ Up-To-Date  |
| fastlane            | 1.111.0 | ✅ Up-To-Date  |
| fastlane_core       | 0.58.0  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| gym                 | 1.12.1  | ✅ Up-To-Date  |
| match               | 0.11.1  | ✅ Up-To-Date  |
| pem                 | 1.4.1   | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| produce             | 1.3.2   | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| sigh                | 1.12.1  | ✅ Up-To-Date  |
| snapshot            | 1.16.4  | ✅ Up-To-Date  |
| spaceship           | 0.38.5  | ✅ Up-To-Date  |
| supply              | 0.8.0   | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.3        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.13.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.0        |
| credentials_manager       | 0.16.2       |
| domain_name               | 0.5.20161021 |
| dotenv                    | 2.1.1        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 1.6.8        |
| fastlane_core             | 0.58.0       |
| gh_inspector              | 1.0.2        |
| google-api-client         | 0.9.20       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| krausefx-shenzhen         | 0.14.11      |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.2        |
| net-sftp                  | 2.1.2        |
| net-ssh                   | 3.2.0        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.4        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.12       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
| xcodeproj                 | 1.4.1        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2016-12-06**
</details>

**Comment by soleares** [comment]
+1

**Comment by KrauseFx** [comment]
Hey, thanks for submitting this issue, we're looking into it 👍  Sorry for the inconvenience

**Comment by mundipf** [comment]
+1

**Comment by tabrindle** [comment]
I dug into this issue a bit, and it seems that when installing from brew (`brew update && brew cask install fastlane`, bundle-1.1 is downloaded and installed, which upon running `fastlane --version`, results in `fastlane 2.1.1`, the most recent version, and still erroneously reports:

```
Fastlane update available 
Please run brew cask reinstall fastlane
```

This is because the bundle contains `bundle_update_checker.rb` which points to [https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/version.json]( https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/version.json) which even more confusingly contains 

```
{
"version": "1.111.0",
"bundle_version": 1.2,
"updated_at": "2016-12-13 19:37:32 UTC"
}
```

I think the main issue here is that the brew cask bundle is different than fastlane's version. This is confusing, and I think will cause maintenance problems. When you call `brew cask list --versions` it reports `fastlane 1.1`, not `fastlane 2.1.1` as one might expect. I think when a new version of the fastlane gem is released, the new cask bundle needs it's version incremented to the same version.

The other problem is that I believe fastlane has the ability to self update the gem through `fastlane update_fastlane, which as it is I believe updates the gems directly, and not through the cask bundle. We might need to change this command depending upon the install method.

**Comment by kensykora** [comment]
+1

**Comment by skrew** [comment]
`brew cask list --versions` report 1.0 for me, but `fast lane --version` give me 2.8.0

It's time for a bug fixes, this issue are reported for more than 1 month now ! ;)

**Comment by ohwutup** [comment]
Hey everyone! Thank you for raising the issue! Regarding what @tabrindle is saying: I agree, this is confusing that the versions are different. This is done because we do not build a new version of the package every time we release a new version of _fastlane_. The package itself is versioned (currently at 1.5) on its own so that we know when a new update needs to be installed via cask. I believe that the issues with the false reporting of an update available have been fixed in recent versions.

> The other problem is that I believe fastlane has the ability to self update the gem through `fastlane update_fastlane, which as it is I believe updates the gems directly, and not through the cask bundle. We might need to change this command depending upon the install method.

Regarding the quote above, this is intended, by running `fastlane update_fastlane`, the package will update it's self-contained instance of _fastlane_ to allow people to be on the latest version of _fastlane_ while still using an existing version of the package.

@skrew, it looks like you might be on an old version of the package itself, this can be updated by running `brew update && brew cask reinstall fastlane`. You should then see 1.5 from `brew cask list --versions` and 2.8.0 from `fastlane -v`

I am going to close this issue for now as the initial problem has been fixed, please do not hesitate to let us know if there is still an issue or confusion around the versioning! :rocket:

**Comment by zixia** [comment]
@ohwutup This fixes my issue today. Thanks!

**Comment by andybee** [comment]
This issue appears to have reappeared again. On running fastlane this morning:

```
fastlane update available
Please run `brew update && brew cask reinstall fastlane`
```

I run `brew update && brew cask reinstall fastlane` and then restart fastlane, but receive the same message.

**Comment by afehners** [comment]
I have the issue also.

```
brew cask list --versions
fastlane 1.6
```
```
fastlane -v
fastlane update available
Please run `brew update && brew cask reinstall fastlane`
fastlane installation at path:
/Users/alex/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.9.0/bin/fastlane
-----------------------------
fastlane 2.9.0
```

```
brew update && brew cask reinstall fastlane
Already up-to-date.
==> Downloading https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalon
Already downloaded: /Users/alex/Library/Caches/Homebrew/Cask/fastlane--1.6.zip
==> Verifying checksum for Cask fastlane
==> Running uninstall process for fastlane; your password may be necessary
==> Running uninstall script /usr/local/Caskroom/fastlane/1.6/uninstall
==> 
==> You can now remove fastlane from your search path by editing your ~/.bash_pr
==> fastlane was uninstalled successfully!
==> 
==> Running installer script /usr/local/Caskroom/fastlane/1.6/install
==> 
==> Installing fastlane to /Users/alex/.fastlane/bin... this might take a few se
==> 
==> 
==> Successfully copied fastlane to /Users/alex/.fastlane/bin
==> 
==> 
==> fastlane update available
==> Please run `brew update && brew cask reinstall fastlane`
==> Updating installed gems
==> Updating fastlane
==> ERROR:  While executing gem ... (TypeError)
==>     no implicit conversion of nil into String
==> fastlane update available
==> Please run `brew update && brew cask reinstall fastlane`
==> Cleaning up installed gems...
==> Clean Up Complete
==> 
==> Detected fastlane is already in your path 🚀
==> 
🍺  fastlane was successfully installed!
```

**Comment by dustinrwh** [comment]
I had this issue even after having homebrew reinstall fastlane a couple times, but it turns out the message I was given was slightly different than what worked. This is what I was seeing:

```
Fastlane update available
Please run `brew cask reinstall` fastlane
```

Running `brew update` along with the reinstall command fixed it for me:

`brew update && brew cask reinstall fastlane`

Thanks for the help everyone!
