### ISSUE TITLE
Fastlane bot blames everything on codesigning!

### ISSUE THREAD

**Issue by ConfusedVorlon** [fastlane/fastlane#7376]
### New Issue Checklist

- [y ] Updated fastlane to the latest version
- [y ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

just watch!

I understand that a lot of things are related to codesigning, and this issue does actually reference codesigning, but there is nothing in https://github.com/fastlane/fastlane/issues/7375 that seems like it should trigger the codesign response:

**Comment by TKBurner** [comment]
@ConfusedVorlon Thanks for your feedback. It's pretty simple and just uses key word search. However, I'll make sure we take a look. Hope you have a great day!

**Comment by KrauseFx** [comment]
Yes, you can check out the source code here: https://github.com/fastlane/issue-bot/blob/master/bot.rb#L125-L140

We did some measurements and noticed that about 40% of the submitted issues are related or caused by code signing, so we decided to make sure everybody saw the code signing troubleshooting guide, which solves lots of the most common problems.

We'll leave the bot like this, as you can always easily ignore the bot's message 👍

**Comment by ConfusedVorlon** [comment]
@KrauseFx perhaps better to not run the search within the <details><summary> block?
(that's what triggered the bot in https://github.com/fastlane/fastlane/issues/7375 )

If you just spank the codesign warning on everything - then people will quickly learn to ignore it when they shouldn't.

**Comment by KrauseFx** [comment]
Great idea, I'll update the bot. 

> If you just spank the codesign warning on everything - then people will quickly learn to ignore it when they shouldn't.

And that's okay for you, since you're already aware of the message, but most users submit their first issue and would see the message 👍
