### ISSUE TITLE
Sigh: Renewing profiles does not add all development certificates

### ISSUE THREAD

**Issue by CraigSiemens** [fastlane/fastlane#7378]
### Issue Description

When renewing a development provisioning profile with sigh, it only adds my development certificate and no one else from my team.

I am running the following command
```
sigh renew --force --development -a MY_APP_ID -u MY_USERNAME
```

The documentation states that 
> By default, `sigh` will include all certificates on development profiles,

However when I run it, it only includes my development certificate on the new provisioning profile.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.11.0                          |
| Installation Source | ~/.rvm/gems/ruby-2.2.4/bin/fastlane         |
| Host                | Mac OS X 10.12.1 (16B2657)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.2.4/lib                |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| snapshot            | 1.16.4  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| produce             | 1.3.2   | ✅ Up-To-Date  |
| gym                 | 1.12.1  | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |
| supply              | 0.8.0   | ✅ Up-To-Date  |
| fastlane            | 1.111.0 | ✅ Up-To-Date  |
| fastlane_core       | 0.59.0  | ✅ Up-To-Date  |
| spaceship           | 0.38.5  | ✅ Up-To-Date  |
| deliver             | 1.16.1  | ✅ Up-To-Date  |
| pem                 | 1.4.1   | ✅ Up-To-Date  |
| sigh                | 1.12.1  | ✅ Up-To-Date  |
| match               | 0.11.1  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| executable-hooks          | 1.3.2   |
| bundler-unload            | 1.0.2   |
| rubygems-bundler          | 1.4.4   |
| bundler                   | 1.12.5  |
| highline                  | 1.7.8   |
| terminal-table            | 1.4.5   |
| dotenv                    | 2.1.1   |
| net-ssh                   | 3.2.0   |
| net-sftp                  | 2.1.2   |
| rubyzip                   | 1.1.7   |
| security                  | 0.1.3   |
| krausefx-shenzhen         | 0.14.11 |
| slack-notifier            | 1.5.1   |
| xcpretty                  | 0.2.4   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| colored                   | 1.2     |
| credentials_manager       | 0.16.2  |
| fastimage                 | 1.6.8   |
| mini_magick               | 4.5.1   |
| xcpretty-travis-formatter | 0.0.4   |
| multi_json                | 1.12.1  |
| gh_inspector              | 1.0.2   |
| fastlane_core             | 0.59.0  |
| json                      | 1.8.3   |
| commander                 | 4.4.1   |
| excon                     | 0.54.0  |
| faraday-cookie_jar        | 0.0.6   |
| babosa                    | 1.0.2   |
| plist                     | 3.2.0   |
| xcode-install             | 2.0.9   |
| claide                    | 1.0.1   |
| xcodeproj                 | 1.4.1   |
</details>

*generated on:* **2016-12-08**
</details>

**Comment by smumryak** [comment]
Hi! I'm experiencing the same issue.

**Comment by atom-b** [comment]
Same issue here. Sigh only generates development profiles with the certificates I have installed locally instead of including all of them. This happens when running both the lane I have defined in the fastfile below and from the command line with `fastlane sigh --development`.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
#!/bin/ruby

###################### Documentation ######################
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions

# minimum fastlane version required
fastlane_version "2.24.0"

default_platform :ios

platform :ios do
  
  ## other lanes redacted ##

  desc "Update appstore and adhoc provisioning profiles"
  lane :'provision' do
    sigh
    sigh(
      development: true
    )
    sigh(
      adhoc:true,
      force: true
    )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
#!/bin/ruby

###################### Documentation ######################
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
app_identifier "com.some.AppId"
team_id "AAA123AA4A" 
apple_id login@email.com

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.25.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
| java-properties           | 0.2.0        |
</details>


*generated on:* **2017-04-04**
</details>
