### ISSUE TITLE
s3 HTML template has dysfunctional plist URL

### ISSUE THREAD

**Issue by jacobsybo** [fastlane/fastlane#743]
`fastlane/lib/assets/s3_html_template.erb`, line 57: Notice the double `itms-services://?action=download-manifest&url=`:

```html
        <a href="itms-services://?action=download-manifest&url=itms-services://?action=download-manifest&url=<%= url %>" id="text" class="btn btn-lg btn-default" onclick="document.getElementById('finished').id = '';">
```

**Comment by KrauseFx** [comment]
cc @joshdholtz

**Comment by joshdholtz** [comment]
Ah yesssss, I can take care of this one :grin:

**Comment by KrauseFx** [comment]
Thanks @joshdholtz :+1:

**Comment by katunch** [comment]
I've fixed this by using my own template. But i came across another issue. The `url` param (url to the plist file) should be url encoded. Otherwise it will not work (since iOS 9 I guess)

I've solved it in my template with a little bit of javascript. Maybe not perfect, but it works.
```javascript
    function downloadButton() {
        var manifest = "<%= url %>";
        document.write("<a class=\"btn btn-lg btn-primary\" href=\"itms-services://?action=download-manifest&url=" + encodeURIComponent(manifest) + "\">");
        document.write("Install</a>");
    }
```

Should I open a new issue for that?

**Comment by ohwutup** [comment]
Hey everyone I am going to close this due to inactivity, but @katunch if you are still having this issue, please comment here and we will reopen to discuss! :+1:
