### ISSUE TITLE
Archive failed when build

### ISSUE THREAD

**Issue by keroushe** [fastlane/fastlane#7761]
### Issue Description
Signing /Users/hexs/Library/Developer/Xcode/DerivedData/Wi-Fi_Disk-aohjxusastpudjdgayvtwnqqwjbv/Build/Intermediates/ArchiveIntermediates/Aigo\ iStorage/InstallationBuildProductsLocation/Applications/aigo\ Disk.app
** ARCHIVE FAILED **

And this is detailed error log
Validate /Users/hexs/Library/Developer/Xcode/DerivedData/Wi-Fi_Disk-aohjxusastpudjdgayvtwnqqwjbv/Build/Intermediates/ArchiveIntermediates/Aigo\ iStorage/InstallationBuildProductsLocation/Applications/aigo\ Disk.app
    cd /Users/hexs/Desktop/workspace/Shell_Test_Project/Wi-Fi_Disk_Optim
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/hexs/.rvm/gems/ruby-2.3.0/bin:/Users/hexs/.rvm/gems/ruby-2.3.0@global/bin:/Users/hexs/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/hexs/.rvm/bin"
    export PRODUCT_TYPE=com.apple.product-type.application
    builtin-validationUtility /Users/hexs/Library/Developer/Xcode/DerivedData/Wi-Fi_Disk-aohjxusastpudjdgayvtwnqqwjbv/Build/Intermediates/ArchiveIntermediates/Aigo\ iStorage/InstallationBuildProductsLocation/Applications/aigo\ Disk.app -validate-for-store

### Environment

+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.5.0                   |
| sdk         | iPhoneOS9.3.sdk         |
+-------------+-------------------------+

Thank you.

**Comment by keroushe** [comment]
But I can use Product-> Achieve to compile * .xcarchive, is the need for other settings?

**Comment by keroushe** [comment]
And I can not use this command to compile.
----------------------------------------
xcodebuild archive -scheme "Aigo iStorage" -configuration Release -archivePath build/Aigo_iStorage
----------------------------------------
the error log is the same, Thank you very much！

**Comment by PetrosIchor** [comment]
Did you recently perform any osx or xcode updates?

**Comment by keroushe** [comment]
No, xcode version is 7.3.1 and mac os version is 10.12.1, Is the need to update it?

**Comment by PetrosIchor** [comment]
Well, being on an old version has its own limits, but I was asking because I ran into archive failures after updating recently. You're way behind my environment though, so it's probably not related.

Could you previously archive without issues?  

I am guessing there's a path or permissions issue.  What happens if you run xcodebuild without an output path? (Or making it relative)

**Comment by keroushe** [comment]
If I do not use the archivePath, the same problem, but if I create a new project, it's ok, I do not know where my project is configured incorrectly.

Can you help me?

Thank you very much!

**Comment by ohayon** [comment]
Thanks for raising the issue @keroushe! It looks to me like there is an issue with the project that is causing `xcodebuild` to fail. Would you mind sharing the output from `xcode-select -p`? That might help to shed some light on the issue. 

If the output from that command shows you a path to a newer version of Xcode, its possible that while your project builds inside of Xcode 7.3.1, the `xcodebuild` command is set up to use a newer version. If this is the case, you can run `sudo xcode-select -s /Applications/<path to your Xcode 7.3.1>.app`

I am going to close this issue for now as it appears that it is related to your project rather than _fastlane_ itself, but please feel free to continue conversation here and we will try to help out as much as we can! 😄 🐙
