### ISSUE TITLE
[Match] git clone: could not read Password for 'https://': terminal prompts disabled

### ISSUE THREAD

**Issue by olbrichj** [fastlane/fastlane#7805]
### Issue Description
INFO [2017-01-10 16:47:53.52]: Cloning remote git repo...
INFO [2017-01-10 16:47:53.52]: $ GIT_TERMINAL_PROMPT=0 git clone 'https://' '/var/folders/rv/mc9j2bm521d1qr8wp4k8vlth0000gr/T/d20170110-62498-yv52cn'
INFO [2017-01-10 16:47:53.53]: ▸ Cloning into '/var/folders/rv/mc9j2bm521d1qr8wp4k8vlth0000gr/T/d20170110-62498-yv52cn'...
INFO [2017-01-10 16:47:53.69]: ▸ fatal: could not read Password for 'https://': terminal prompts disabled
Cloning into '/var/folders/rv/mc9j2bm521d1qr8wp4k8vlth0000gr/T/d20170110-62498-yv52cn'...
fatal: could not read Password for 'https:/': terminal prompts disabled
ERROR [2017-01-10 16:47:53.69]: Exit status: 128
"ERROR [2017-01-10 16:47:53.98]: Error cloning certificates git repo, please make sure you have access to the repository - see instructions above"

When running match via Jenkins it fails with the above error message.
Running it via ssh it fails the same way.
Running it locally (with a logged in user) it works.

My guess it can not access the keychain to retrieve local network passwords.
The user itself can do this.

### Environment
Jenkins 2 with Pipeline
Slave with OS X 10.11.6
Xcode 8.2

**Comment by mfurtak** [comment]
Hi @olbrichj - have you taken a look through our [Jenkins Integration documentation](https://docs.fastlane.tools/best-practices/continuous-integration/#jenkins-integration)? 

As you probably know, since you can't type in a password during your CI builds, _match_ & Git will have trouble using the `https` authentication method unless your build machine has its keychain set up with the right credentials for your repository.

The error message you provided is letting you know that _match_ could not determine the right password to use. It needed to prompt you, but on CI, it is not allowed to prompt because that would cause the build to hang.

Our suggestion would be to investigate the Keychains and Provisioning Profiles Plugin mentioned [here](https://docs.fastlane.tools/best-practices/continuous-integration/#plugins).

Please let us know how that works out for you 👍

**Comment by KrauseFx** [comment]
I'll close this issue for now
