### ISSUE TITLE
produce enable_services invalidates profiles, leading to trouble/confusion

### ISSUE THREAD

**Issue by mfurtak** [fastlane/fastlane#7819]
As noted in https://github.com/fastlane/fastlane/issues/7731, `produce enable_services` has the side-effect of invalidating provisioning profiles, which leads to trouble and/or confusion for users.

Is there something we can do to prevent trouble with this in the future? 

cc/ @joshdholtz

**Comment by joshdholtz** [comment]
Idea 1: If `produce enable_services` doesn't actually _change_ any of the existing configurations, don't run the command. In my experiences, running this on the same setting that already exists will invalidate profiles. This _may_ be a lot of work though.

Idea 2: Display some sort of warning saying that this will invalidate profiles. Easiest option but not very helpful.

Idea 3: Right now, `produce enable_services` has to get run to a bash command. We could make this its own action with an option in it to remake all the profiles? This would solve the issue be description the behavior in the documentation/action options.

Idea 4: I did this in my setup when I ran into this issue but I created a custom action that cleared all invalid provisioning profiles for a certain bundle id. This could _maybe_ get included in `sigh` as an option so that things stay cleaned up.

That is all I got right now 😇

**Comment by KrauseFx** [comment]
> Idea 2: Display some sort of warning saying that this will invalidate profiles. Easiest option but not very helpful.

I like that one, as it doesn't change existing behaviour. We can do something like we do in _sigh_ when an app ID is missing: https://github.com/fastlane/fastlane/blob/e5781677991e985e62530e701616ef5541356456/sigh/lib/sigh/runner.rb#L223-L234

This way the user can copy and paste the command, or we could even ask the user to run it for them.

_produce_ is clearly about creating App IDs, enabling features is already a gray area, but touching and modifying provisioning profile goes too far in my opinion.
