### ISSUE TITLE
Incorrect error message when trying to upload build while the app is in Waiting-for-review status [mac]

### ISSUE THREAD

**Issue by masteranza** [fastlane/fastlane#7905]
`You must add at least one screenshot. [en-US]: You must add at least one screenshot. There are one or more errors on the page.`

I just found this bug by uploading a new build while the old one was not rejected.
Screenshots are ok, since it works after I manually reject the build from submission.
Perhaps a nice solution would be a prompt with a message "There's another build awaiting review, reject it and upload a new one? (Y)/(N)"

Running: latest fastlane.

**Comment by timwredwards** [comment]
I've also experienced this issue. Seems deliver isn't auto-rejecting a binary that's "Waiting for review". It fails with:

`[!] The request could not be completed because:
	You must add at least one screenshot. You must add at least one 4.7-Inch Display screenshot or use screenshots from a larger display. You must add at least one 4-Inch Display screenshot or use screenshots from a larger display. [en-US]: You must add at least one screenshot. [en-US]: You must add at least one 4.7-Inch Display screenshot or use screenshots from a larger display. [en-US]: You must add at least one 4-Inch Display screenshot or use screenshots from a larger display. There are one or more errors on the page.`

Environment below:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.11.0"

default_platform :ios

platform :ios do

    buildNumber = ENV['BITRISE_BUILD_NUMBER'].to_i
    versionString = '1.0.'+buildNumber.to_s
    buildURL = ENV['BITRISE_BUILD_URL']
    lastCommitString = sh("git log -1 --pretty=%B")

    before_all do
        cocoapods
    end

    desc "Runs the unit tests"
    lane :test do
        scan
    end

    desc "Takes screenshots for specified screen sizes and locales"
    lane :screenshots do
        snapshot
    end

    desc "Creates a new ad-hoc build for the test team from staging/production"
    lane :build do
        match(
            type: 'appstore'
        )

        gym(
            scheme: "Cocoon",
            export_method: 'app-store'
        )

        deliver
    end
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "life.cocoon.cocoon" # The bundle identifier of your app
apple_id "john@cocoon.life" # Your Apple email address

team_id "H9TDZM8KUK"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.11.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.1        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| addressable               | 2.4.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.19       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.0       |
| io-console                | 0.4.5        |
</details>


*generated on:* **2017-01-26**
</details>

**Comment by timwredwards** [comment]
Any update on this? A workaround is to manually reject the current version, but it would be great if spaceship / deliver could auto-reject the currently build.

**Comment by KrauseFx** [comment]
Definitely something we'd be interested in fixing, however it always takes time to reproduce the situation to actually fix it. What's the best way to reproduce this exact scenario?

**Comment by timwredwards** [comment]
We're using Bitrise as our CI environment. When we use deliver to deploy an update to iTunes connect, if there's an existing build "waiting for review", or "in review", then it throws this error and fails. If there's no existing build blocking deliver, it works great. Note that it also works perfectly if there's an app ready for sale, and an app that's "developer rejected". I've been getting around this issue by manually cancelling in-review builds whenever pushing a new build.

**Comment by timwredwards** [comment]
Can reproduce every time. Let me know if you need anything from me.
