### ISSUE TITLE
Clean parameter ignored during build settings check

### ISSUE THREAD

**Issue by jacobjennings** [fastlane/fastlane#8099]
`xcodebuild -showBuildSettings -workspace (workspace) -scheme (scheme)`

was recently replaced with:

`xcodebuild clean -showBuildSettings -workspace (workspace) -scheme (scheme)`

in https://github.com/fastlane/fastlane/pull/5626

This seems to clean the target even if the argument -clean false is passed in as a parameter. I'm not sure what a solution would look like. Perhaps the retry in https://github.com/fastlane/fastlane/pull/5188 is sufficient?

Thanks to all contributors!

**Comment by mgrebenets** [comment]
@jacobjennings 
What is the `-clean false` parameter? Do you mean the `gym` action `clean: false` option?

As far as I understand, getting build settings is not related to building the app target.
The `clean` will be _always_ added to `-showBuildSetitngs` command, because otherwise it may hang.

According to the builds that we do, using `clean` for getting build settings doesn't actually clean the build files. I have just re-ran one of our projects 3 times in a row. Each time I run it a `clean -showBuildSettings` is called, but it doesn't impact build speeds. Only the first build takes longer, because it builds everything from scratch, 2nd and 3rd builds are much faster.

**Comment by jacobjennings** [comment]
My goal was to get incremental builds going, and this was something in particular that I noticed. However, it turns out that xcodebuild calls with the 'archive' option **always** clean before building. In order to do actual incremental builds with archives, the archive must be done in a successive xcrun PackageApplication call. In other words, with archived builds, this additional clean makes no difference.

I know it's atypical to archive incremental builds, but my intention is to fall back to clean builds upon failure in the interest of performance. I've managed this using xcodebuild and xcrun directly with some good results.

**Comment by mgrebenets** [comment]
By incremental builds, do you mean that build/derived data is not cleaned up between builds and your consequent builds run faster?

Because I got confused by the meaning of "incremental" - the actual feature of clang compiler which they may support in Swift 4 or sooner, but are not supporting yet.

If you simply want to keep derived/build data between builds, then I guess `gym` totally respects the `clean` option and using `xcodebuild clean -showBuildSettings` will not touch any derived data.

So it shouldn't be an issue.

Are you using Ci though? Cause if you use same build agents for different projects, then some other project CI can wipe derived data.

**Comment by IngmarStein** [comment]
According to the Xcode 8.3 beta 2 release notes, the underlying bug in `xcodebuild` has been fixed (radar 26749142). From that version on, we could again remove the `clean` parameter for `-showBuildSettings`.

**Comment by yakimant** [comment]
Have the same, xcodebuild archive always recompile everything even if nothing is changed.
So incremental builds are working with build, but not archive.
