### ISSUE TITLE
Gym scheme verification script not correct

### ISSUE THREAD

**Issue by angshukN** [fastlane/fastlane#8158]
The command line script for verifying whether the scheme for gym exists in the Xcode project is not correct because of which it displays " Couldn't find specified scheme '<scheme>' "
the command line script for checking whether the gym scheme exists is currently like this 

xcodebuild -list -project ./Project_name

This script should be updated to this 

xcodebuild -target target_name -configuration configuration_name -showBuildSettings  | grep -i 'PRODUCT_NAME'

If this update is not done then apps with product names differing from target name will throw this error.

**Comment by mgrebenets** [comment]
@angshukN 

I believe `xcodebuild -list -project Project.xcodeproj` is the right way to list schemes.
It is pretty much very similar to looking inside `Project.xcodeproj/xcshareddata/xcschemes/`.

It is true that scheme and product name do not have to match.
But I still don't see the issue here.

The script is supposed to look for a scheme and it is looking for a scheme.
It should not look for product name.

If scheme name is not the same as product name (which is totally fine), it's still irrelevant, because it doesn't matter what the product name is in this context.

Could you provide more details on what you are trying to do, please?
Why do you have `./` in `xcodebuild -list -project ./` command? Looks like it's missing path to `xcodeproj` file.

I can see where this command is generated in `fastlane` source code, and it looks like this:

```ruby
proj << "-project #{options[:project].shellescape}" if options[:project]
```

So the `options[:project].shellescape` should contain name of Xcode project, which in your case is `./`.

**Comment by angshukN** [comment]
@mgrebenets 
Thanks Bro
