### ISSUE TITLE
Is it possible to get a list of uploaded builds to crashlytics and get information ( release notes ) from it?

### ISSUE THREAD

**Issue by lolgear** [fastlane/fastlane#8202]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
So...
My scenario is simple.

1. Archive by Xcode
2. Run script that update version in build phase.
3. Load application to crashlytics server by Fabric desktop app.
4. Write notes for build.
5. Upload application to crashlytics.
6. Commit and push to git.
7. Say about build in Slack.

All these tasks could be done by fastlane, of course.
( And maybe my question could be solved more effectively by automate deployment? )

But I would like to ask about abilities of Fabric API.
Is it possible to get a list of uploaded builds and get information ( release notes ) from it?

Maybe my question is not an option and should be solved by delegating everything boring to fastlane, as I said before.

Thanks for help!

**Comment by PetrosIchor** [comment]
Your question about crashlytics API should be directed to their documentation and resources.  However, you should read through the fastlane docs because all those vectors are covered by the crashlytics action.  Fastlane can deliver both your artifact and notes to crashlytics. 

https://docs.fastlane.tools/actions/#crashlytics

Building, delivery, git tasks, and slack notifications can all be handled by fastlane if that's the approach that works for your needs.

**Comment by asfalcone** [comment]
@lolgear Thanks for your question. There is not currently an api for fabric that returns build information.
