### ISSUE TITLE
Fastlane install error

### ISSUE THREAD

**Issue by crewshin** [fastlane/fastlane#851]
I'm getting this error on install. Tested on a few machines + VM's. Old installs, fresh installs. Same result.

Repro steps:

* Install OSX.
* Install XCode
* Install homebrew
* Install cocoapods
* Install fastla..... 

![screen shot 2015-11-16 at 12 45 18 am](https://cloud.githubusercontent.com/assets/273809/11190320/ad3c1666-8c49-11e5-9266-220d96da4a67.png)

**Comment by crewshin** [comment]
Ah... brew install ruby

    jenkins:~ jenkins$ ruby --version
    ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]

This fixes it.

**Comment by crewshin** [comment]
I guess the real issue here is that even though fastlane's min ruby requirement is 2.0.0, it doesn't work.

**Comment by ohwutup** [comment]
hey @crewshin! Apologies for the issues you were having with ruby! I am going to close this issue for now because it's been a while since it started, but please reopen it if you are still having issues. If its ruby issues you are having, I would check out `rbenv` as a managed ruby environment! :name_badge:
