### ISSUE TITLE
Gym: export_method prevents include_bitcode.

### ISSUE THREAD

**Issue by dzan** [fastlane/fastlane#8675]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

( This is more of a question. )

Bitcode is not included in the ipa when `export_method` is set to `development`. This is however perfectly possible from Xcode but might I realize might not be a common use-case.

I was wondering if this is a bug, easy to fix, possible to workaround,...? I use fastlane to build and test +-70 apps in order to test our software on later (the input to which is an IPA with bitcode).

**Comment by dehlen** [comment]
I am also experiencing this issue. Any update on this one ?

**Comment by JDevlieghere** [comment]
+1

**Comment by mgrebenets** [comment]
Hi @dzan 

Xcode is using `xcodebuild` for building and packaging the app. And `gym` actually uses `xcodebuild` too.

According to `xcodebuild -h` output, bitcode option only applies for App Store exports, same applies for packaging debug symbols too:

```
	uploadBitcode : Bool

		For App Store exports, should the package include bitcode? Defaults to YES.

	uploadSymbols : Bool

		For App Store exports, should the package include symbols? Defaults to YES.
```

Otherwise app packages do not contain bitcode as far as I know.

If I understand bitcode feature correctly, it is only useful for Apple. 
Bitcode is an intermediate language representation of the original source code, if I get it right.
So Apple can use bitcode to recompile existing app and produce new binary.

When distributing the using distribution method other than App Store, there is no practical value in including bitcode in the app package, and that's why `xcodebuild` doesn't do that (according to documentation).

In my experience, if you try to use "Enterprise" option with bitcode, the archiving will fail. 
I didn't try it with "development" though.

Are you sure the `.ipa` actually includes bitcode?
Which command did you run to check it?
