### ISSUE TITLE
[feature] Add some verbosity to Gym when exporting dSYM

### ISSUE THREAD

**Issue by Sega-Zero** [fastlane/fastlane#8684]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Is it possible to add some verbosity for dSYM export action? Travis CI has just broke my build because no output was given within 10 minutes right after export operation started:

```bash
[16:39:10]: ▸ Archive Succeeded
[16:39:14]: Generated plist file with the following values:
[16:39:14]: ▸ -----------------------------------------
[16:39:14]: ▸ {
[16:39:14]: ▸   "method": "app-store",
[16:39:14]: ▸   "uploadSymbols": true,
[16:39:14]: ▸   "uploadBitcode": false
[16:39:14]: ▸ }
[16:39:14]: ▸ -----------------------------------------
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

Previous build took about 7 minutes with no output:
```bash
[19:23:23]: ▸ Archive Succeeded
[19:23:25]: Generated plist file with the following values:
[19:23:25]: ▸ -----------------------------------------
[19:23:25]: ▸ {
[19:23:25]: ▸   "method": "app-store",
[19:23:25]: ▸   "uploadSymbols": true,
[19:23:25]: ▸   "uploadBitcode": false
[19:23:25]: ▸ }
[19:23:25]: ▸ -----------------------------------------
[19:29:48]: Successfully exported and compressed dSYM file
[19:29:48]: Successfully exported and signed the ipa file:
```

As I mentioned in #8556, that kind of long operations needs some ping echo's, so the CI won't cancel the build, just the way it is done in pilot.

**Comment by Sega-Zero** [comment]
Well, some verbosity could point to it better, than 7+ minutes of silence?

**Comment by Hais** [comment]
I'm getting the same with Travis CI, Xcode 8.3, Fastlane 2.23.0

**Comment by hjanuschka** [comment]
@Sega-Zero @Hais  - can you try adding `--verbose`  to your _fastlane_ call?
its intended to print the sub-command outputs - like in your case the output of the packaging of the app (which seems to take a long time)


> sometimes its because there are way too much archives already exported. in that case you could clear out your archives folder.: `~/Library/Developer/Xcode/Archives/`

**Comment by Sega-Zero** [comment]
We don't have too much archives in Travis CI, since it's virtual machines cleanup at every launch.
I can add `--verbose`, but it will be verbose on the whole process, which is not what I would like to have in my build log: it may generate more than 10k lines, so all the text after is stripped with Travis CI in that case, so I have to download the raw file to see if everything is ok, that's not comfortable at all.
A separate option for export part verbosity in `gym` command would be great

**Comment by Sega-Zero** [comment]
Still having this issue :(

**Comment by mpirri** [comment]
I certainly understand your concerns about adding `--verbose` to the _fastlane_ call, but if you add it just once, does it offer any insight into what is going on during the long delay? Don't leave it set permanently, of course, just once to see what we can learn. 🚀

**Comment by Sega-Zero** [comment]
I'm afraid this happens very random. It may occur several times per day or may not occur for weeks. Is there a way to turn on a verbosity just for a last step of gym?

**Comment by Hais** [comment]
I'd agree, it's mostly at random. It tends to be how long the export takes which varies due to how much load the machine is under at the time. 

Travis cuts out after waiting 10 mins. Exporting my project on a good day it'll take 8mins, on a bad day it'll take longer and timeout. 

I'm happy to provide logs, but not sure which parts are most relevant. Basically, its this call that takes so long

`xcodebuild -exportArchive -exportOptionsPlist /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/gym_config20170720-3530-1213uo5.plist -archivePath '/Users/travis/Library/Developer/Xcode/Archives/2017-07-20/REDACTED 2017-07-20 07.36.54.xcarchive' -exportPath /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/gym_output20170720-3530-13u8hx9`

I should clarify that I wouldn't consider this a bug of Fastlane. Exporting the archive with Xcode GUI also takes as long. So it'd be nice to not have long periods of time where nothing is printed to console. 

@Sega-Zero for what it's worth, my current hack is to have this in my .travis.yml, which just periodically prints the PID of the xcodebuild process. 

`before_script:
- "while sleep 60; do pgrep xcodebuild; done &"`

**Comment by Sega-Zero** [comment]
Thanks for a snippet. I agree that this is not necessarily a bug in Fastlane and printing something every minute during export operation would be enough. Just like pilot does while waiting for build processing on itunes connect.

**Comment by mpirri** [comment]
Fortunately, it is easier for us to do that with `pilot` - since we have to poll to see if the build is processed, we can just print out a message every time we ping Apple's servers. Maybe possible for `gym` to run a background thread that just prints out dots or something, but I suspect it is not trivial to do that in a way that wouldn't be disruptive to other output when it appears. Something to think about...  🤔

**Comment by nirmalspeed** [comment]
I have this issue as well when using commandline WinSCP to hit our build server. I've seen other scripts where they output a period "." every few seconds while a long running command is still going.
