### ISSUE TITLE
build.submit_for_beta_review!(parameters) raise err

### ISSUE THREAD

**Issue by self-creative** [fastlane/fastlane#869]
Hi :
    I want to change my build after ITC processing,but when i use "build.submit_for_beta_review!(parameters)"mehod i found that throw following issue:

/Library/Ruby/Gems/2.0.0/gems/spaceship-0.14.1/lib/spaceship/tunes/tunes_client.rb:163:in `handle_itc_response': ITC.apps.builds.errorMessage.notApprovedBuild (Spaceship::TunesClient::ITunesConnectError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.14.1/lib/spaceship/tunes/tunes_client.rb:474:in `update_build_trains!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.14.1/lib/spaceship/tunes/build_train.rb:100:in `update_testing_status!'
	from notification.rb:78:in `beginTest'
	from notification.rb:13:in `run'
	from notification.rb:84:in `<main>'

**Comment by ohwutup** [comment]
Hey @self-creative, is this still an issue for you? I am going to close it for now as it has been a while since this was opened. But please reopen it if you are having the issue on new versions of the tools! Also, if you do reopen, please paste in the full output from your terminal. Thanks! :computer:
