### ISSUE TITLE
git_branch returns empty string while running in Travis-CI

### ISSUE THREAD

**Issue by Sega-Zero** [fastlane/fastlane#870]
When running fastlane on Travis-CI machine, `git_branch` returns an empty string. I tried this in my Fastfile:
```ruby
branch = sh('git rev-parse --abbrev-ref HEAD')
puts branch 
branch = sh("git branch | sed -n '/\* /s///p'")
puts branch
branch = ENV["TRAVIS_BRANCH"]
puts branch
```
the output is:
> [SHELL COMMAND]: git rev-parse --abbrev-ref HEAD
> [SHELL]: HEAD
> HEAD

> ---------------------------------------------
> --- Step: git branch | sed -n '/* /s///p' ---

> ---------------------------------------------
> [SHELL COMMAND]: git branch | sed -n '/* /s///p'
> [SHELL]: (HEAD detached at 567cf40)
> (HEAD detached at 567cf40)
> test-branch

Which is quite suprising, all of those commands returns `test-branch` on my local mac. I think `git_branch.rb` should try one of those commands as well as reading travis environment variable `TRAVIS_BRANCH` too.

**Comment by Rking788** [comment]
It seems like Travis is cloning a specific commit and that is why it is displaying a detached HEAD state from shell `git branch` command (the first shell seems to be parsed incorrectly and fail). On your local machine it works because your project is currently on a git branch. You could probably reproduce the Travis output by cloning the repository to a different directory and running `git checkout <COMMIT_HASH>` using that specific git commit hash. I'm not sure how the TRAVIS_BRANCH environment variable is defined but I assume it is the branch Travis is tracking new commits on for your project and doesn't represent a git branch in the actual Travis workspace.

I think it would be difficult to support all CI environments in the git_branch action but maybe someone could suggest a way to conditionally use either git_branch or ENV["TRAVIS_BRANCH"] in your Fastfile.

**Comment by KrauseFx** [comment]
Thanks for jumping in @Rking788, Minions are the best :+1: 
@Sega-Zero did that solve your issue?

**Comment by Sega-Zero** [comment]
Not really. I use `ENV["TRAVIS_BRANCH"]` in my Fastfile already. I thought it would be great to use the standard action instead. Fastlane already supports Jenkins env, so I think Travis-CI is famous enough to be officially supported too =) But if that is impossible - that issue may be closed.

**Comment by KrauseFx** [comment]
@Sega-Zero that's a great idea, I'll add `ENV["TRAVIS_BRANCH"]` :+1:
