### ISSUE TITLE
Fail to commit_version_bump after pod install

### ISSUE THREAD

**Issue by tirrorex** [fastlane/fastlane#9318]
### New Issue Checklist

I use the latest version

### Issue Description

I would like to know what is fastlane doing, i did a pod install before i ran fastlane precisely to avoid this.
And even so, if fastlane does a pod install and modify files why is it not expecting changes?
This doesn't make sense to me.

[!] Found unexpected uncommitted changes in the working directory. Expected these files to have
changed:
Sample.xcodeproj/project.pbxproj
Sample/Info.plist
Sample/Info-DEV.plist.
But found these actual changes:
Sample.xcodeproj/project.pbxproj
Sample/Info-DEV.plist
Sample/Info.plist
Podfile.lock
Pods/Manifest.lock
Pods/Pods.xcodeproj/project.pbxproj
Pods/Target Support Files/Pods-Sample-Dev/Pods-Sample-Dev-resources.sh
Pods/Target Support Files/Pods-Sample-Dev/Pods-Sample-Dev.debug.xcconfig
Pods/Target Support Files/Pods-Sample-Dev/Pods-Sample-Dev.release.xcconfig
Pods/Target Support Files/Pods-Sample/Pods-Sample-resources.sh
Pods/Target Support Files/Pods-Sample/Pods-Sample.debug.xcconfig
Pods/Target Support Files/Pods-Sample/Pods-Sample.release.xcconfig.

**Comment by joshdholtz** [comment]
@tirrorex Can you please include the output from `fastlane env` so I can see your environment and what your `Fastfile` looks like? It is easier to address your issue knowing all of this information.
Thanks!

**Comment by taquitos** [comment]
@tirrorex when you do a pod install it often updates a number of files in your workspace, especially `xcconfig`  files. This happens most often when you update your version of `cocoapods`

For background:
_fastlane_ explicitly called out it was only expecting
```
Sample.xcodeproj/project.pbxproj
Sample/Info.plist
Sample/Info-DEV.plist.
```
because when you call `commit_version_bump` it has to change the version number in all those files for the version to be fully "bumped"

Those extra files I see are:
```
Podfile.lock
Pods/Manifest.lock
Pods/Pods.xcodeproj/project.pbxproj
Pods/Target Support Files/Pods-Sample-Dev/Pods-Sample-Dev-resources.sh
Pods/Target Support Files/Pods-Sample-Dev/Pods-Sample-Dev.debug.xcconfig
Pods/Target Support Files/Pods-Sample-Dev/Pods-Sample-Dev.release.xcconfig
Pods/Target Support Files/Pods-Sample/Pods-Sample-resources.sh
Pods/Target Support Files/Pods-Sample/Pods-Sample.debug.xcconfig
Pods/Target Support Files/Pods-Sample/Pods-Sample.release.xcconfig.
```

Which is totally consistent with my experience with `cocoapods` too (although inconvenient) when you run `pod install`. I always just get in the habit of getting my iOS code perfect, committing, then running `pod update` committing all the changes like those `xcconfig` changes, and then calling it a day.

**Comment by tirrorex** [comment]
@taquitos you totally missed the point mate sorry, i already know everything you said.
By the way, i would not run a pod update just before building a release, especially in my case when we are still not in swift 3 and are de facto using old versions of the pods ;)

What i want to know is why after running pod install myself (said it in my issue that i ran pod install just before launching fastlane), fastlane running pod install would change those files when my command didn't, and also why fastlane running pod install is not expecting changes to those files when obviously there can be a change.
Either fastlane should not do pod install OR commit those changes by itself, the current behaviour makes absolutely no sense.

@joshdholtz nope sorry, i had to edit almost half the output last time to remove the company and app name from it and it was a pain in the ass...
Besides i just want to know what is going on with fastlane, i already fixed my issue by commiting the changes but like i said, what happened doesn't make any sense so i want to understand it to not facing this again.

**Comment by joshdholtz** [comment]
@tirrorex The _only_ thing I can think of without seeing any of your information is that you are _possibly_ using a different version of CocoaPods when running your fastlane setup and `pod install`. I would make sure to prefix both of those commands with `bundle exec` so the same CocoaPods version is being used. 

What does the diff in your `Podfile.lock` look like? Does it show its using a different version?

Again, sorry if this isn't much help. Kinda shooting in the dark without seeing anything.

**Comment by tirrorex** [comment]
Nope, i downloaded the zip for fastlane because from it failed to install with homebrew.
So the zip comes with his own version of cocoapods that is updated independently of the system?
Running pod install prefixed with `bundle exec` will fix this?
If so i can close the issue and thank you for your time :)
I finally get it

**Comment by joshdholtz** [comment]
@tirrorex I'm fairly certain that the packaged version of `fastlane` (homebrew or zip) comes with its own version of `cocoapods`. And knowing this know, using `bundle exec` _might_ not fix your issue. One thing you can try to do though is run `fastlane run cocoapods` instead of running `pod install`. This will run `pod install` from **within** the bundled version of `fastlane`.

**Note:** This theoretically should work for you. I have always installed `fastlane` and `cocoapods` via ruby gems so I have never experienced this issue specifically

**Comment by tirrorex** [comment]
thanks, i'm gonna make a script for it.
would love to install fastlane through rubygems but it can fails in so many ways :/
Anyway, closing the issue

**Comment by joshdholtz** [comment]
@tirrorex Also so many ways it can succeed 😉  But have fun continuing to fastlane 💪 🚀

**Comment by tirrorex** [comment]
I wouldn't calling fun ahah, almost throw my laptop away yesterday :D

**Comment by tirrorex** [comment]
For sure eheh, thanks !
