### ISSUE TITLE
xcodebuild_log_path would be conflict when the same project built simultaneously on CI

### ISSUE THREAD

**Issue by truebit** [fastlane/fastlane#9342]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When one project built in different branches on ci, the `xcodebuild_log_path` would use the [same log path](https://github.com/fastlane/fastlane/blob/master/gym/lib/gym/generators/build_command_generator.rb#L96-L102), which would got conflict on path.

IMHO adding a timestamp on `file_name` would fix it.

### Environment
Fastlane 2.36.0

**Comment by joshdholtz** [comment]
@truebit The reason for no timestamp being on the log file right now is so that all of the gym logs for that project and scheme are all in one file (and a lot of the other tools also use a very similar file naming scheme which I would assume would also cause you issues).

What is happening when you run the projects simultaneously? Do one of the fastlane jobs crash/hang? This probably a good thing to address but curious what you are actually experiencing.

**Comment by truebit** [comment]
The build would fail with exit code 65
And I cannot find any reason on ci log output from xcpretty because the log would be mixed due to same log file

**Comment by joshdholtz** [comment]
@truebit Are you cool with testing this from a branch of mine for me when I make a fix for this? Want to make sure it works for you before it would get merged into master.

**Comment by truebit** [comment]
my workaround is to set `--buildlog_path` for each build job on ci

**Comment by joshdholtz** [comment]
@truebit That's a pretty solid workaround 👌 I'm working on a fix for this issue for you though so you don't have to do which you could put my branch of fastlane in your `Gemfile` if you'd like to give it a try for me when its ready 😊

**Comment by joshdholtz** [comment]
@truebit Actually, I _think_ your solution of setting the `buildlog_path` (probably to a temp directory or a directory with the current timestamp) might be the best solution (just saw that that was an option). My solution was going to add a flag to gym to append a timestamp onto the filename but setting a different `buildlog_path` is already built in is probably a more elegant/flexible solution.

The intended purpose of the `"#{Gym.project.app_name}-#{Gym.config[:scheme]}.log"` filename is to keep all the logs in one place for a similar gym runs and to not create tens/hundreds/thousands of different output log files. Based on that I am going to close this issue for now since `buildlog_path` solves your issue but feel free to create a pull request if you'd like to see a different solution 😊 Thanks and happy fastlaning 💪 🚀
