### ISSUE TITLE
Spaceship vs Deliver tool

### ISSUE THREAD

**Issue by robin23686** [fastlane/fastlane#9486]
Not sure if this is the correct place for this question or not.

I am using deliver tool right now for my app to submit for review and its working fine.

1. But i want to know whether we should use spaceship or deliver for the app to submit for review and why is there any performance difference?
2. If in case I want to use spaceship to submit my app for review how can I use this tool to upload the ipa file on apple store.
3. Also is this will be good if i upload the app using deliver and submit it for review using spaceship

Please suggest

Thanks,
Robin Gupta

**Comment by robin23686** [comment]
its not the issue i am facing exactly. its confusion between what tool to use from spaceship and deliver to submit the app for review in apple store

**Comment by ohayon** [comment]
Hey @robin23686! This is definitely the correct place for this question! 😄 

To give a little context: _deliver_ is definitely the tool that you should be using to upload and submit your app for review. _spaceship_ is a library that we have to talk to Apple's services including iTunesConnect and the Apple Developer Center. _deliver_ uses _spaceship_ under the hood to communicate with iTunesConnect.

If you are successful with _deliver_ currently, you should keep that going for sure. 🚀 

Let us know if you have any more questions! 🐙

**Comment by robin23686** [comment]
Hi @ohayon Thanks for the reply.

This clears my confusion. However i have one more question

1. Can we use spaceship to upload the package if yes than how can you please provide a sample? the reason i am asking is i believe we can use spaceship outside mac environment as well (Please correct me if i am wrong)

2. Also right now we are dependent on Mac machine to publish the app on apple store and we want to remove this dependency and want to use linux or DCOS so can you please help me if this is possible also if yes can you please point me to correct documentation on how to do this?

**Comment by mpirri** [comment]
@robin23686 A really useful resource for learning to use spaceship is to look at the code for _deliver_ to see how it calls _spaceship_ under the hood. The _deliver_ source code is stored here:
https://github.com/fastlane/fastlane/tree/master/deliver/lib/deliver

In terms of using Linux to upload, you might run into some problems, since we rely on Apple's `itmstransporter` binary, which is only installed on macOS machines. It might be possible to bodge something together to work on Linux, but we don't have this documented.

I hope this is helpful!  🚀
