### ISSUE TITLE
Is it possible to export to both TestFlight and Crashlytics in a single lane?

### ISSUE THREAD

**Issue by thomasjoulin** [fastlane/fastlane#9612]
It seems I need to do `gym(export_method: 'ad-hoc')` for Crashlytics to work but not TestFlight. Is there a way to make it work or should I make 2 lanes (and build twice)? Here is what I'd like to do:

```
  lane :beta do |options|
    gym(
      scheme: "MyScheme"
    )

    pilot(
      skip_submission: true,
    )
     crashlytics(
      api_token: "secret",
      build_secret: "secret"
    )
  end
```

Thanks!

**Comment by getaaron** [comment]
The builds need to be signed with different provisioning profiles so you need to make separate builds. I recommend keeping them in separate lanes:

One of my fastfiles looks like this:

```ruby
  lane :beta do 
    scan
    build_and_deploy_crashlytics
    build_and_deploy_testflight
  end

  private_lane :build_and_deploy_crashlytics do
    gym
    crashlytics
  end

  private_lane :build_and_deploy_testflight do
    gym
    pilot
  end
```

One thing to be careful about with this approach is that it's possible for the Crashlytics deploy to succeed but the TestFlight deploy to fail.

**Comment by iDaniel89** [comment]
@thomasjoulin

You can upload to both platforms in the same lane and using the same build, the IPA must be prepared for Testflight, but you won't be able to install/test from Crashlytics/Fabric, since the provisioning will be useful only for the app store.  The main use of this is to report statistics/crashes of your Testflight IPA.

And if you are using crashlytics, don't forget to add the "upload symbols" task:

- upload_symbols_to_crashlytics(api_token:"token")
