### ISSUE TITLE
Simulator Restart Issue

### ISSUE THREAD

**Issue by tringManoj** [fastlane/fastlane#9625]
Why Should Simulator Restart each time to Run my Each Targets? Say If I have 5 Targets. Fastlane relaunches Simulator 5 times. Which takes 6 Mins for Each market. Is there a way to stop this ?

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by taquitos** [comment]
We could keep it running, but we do a lot more than just running the test. We optionally uninstall the app, we make sure to launch the right one, and we also set scaling. So overall, it's a lot safer to do that. In the future, we will hopefully be able to run multiple simulators at once (Xcode 9) so that might help speed things up.
