### ISSUE TITLE
There is no web session to update still appear on new version "fastlane"

### ISSUE THREAD

**Issue by huynguyen-n** [fastlane/fastlane#9653]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

Looking for iTunes Connect Team with ID 118523344

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	there is no web session to update

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09there%20is%20no%20web%20session%20to%20update+repo:fastlane/fastlane
➡️  pilot - there is no web session to update (on upload)
   https://github.com/fastlane/fastlane/issues/9237 [closed] 24 💬
   5 weeks ago

➡️  deliver: there is no web session to update
   https://github.com/fastlane/fastlane/issues/7309 [closed] 22 💬
   05 Dec 2016

➡️  deliver: there is no web session to update
   https://github.com/fastlane/fastlane/issues/6826 [closed] 55 💬
   05 Dec 2016

and 12 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because:%0A%09there%20is%20no%20web%20session%20to%20update&type=Issues&utf8=✓
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.5.0/spaceship/lib/spaceship/tunes/tunes_client.rb:222:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
	there is no web session to update
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.5.0/spaceship/lib/spaceship/tunes/tunes_client.rb:97:in `team_id='
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.5.0/spaceship/lib/spaceship/tunes/tunes_client.rb:124:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.5.0/spaceship/lib/spaceship/tunes/spaceship.rb:30:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.5.0/pilot/lib/pilot/manager.rb:16:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.5.0/pilot/lib/pilot/manager.rb:8:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.5.0/pilot/lib/pilot/build_manager.rb:4:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.5.0/pilot/lib/pilot/commands_generator.rb:57:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.5.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.5.0/pilot/lib/pilot/commands_generator.rb:133:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.5.0/pilot/lib/pilot/commands_generator.rb:14:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.5.0/fastlane/lib/fastlane/cli_tools_distributor.rb:45:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.5.0/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary> ✅ fastlane environment ✅ </summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12.5                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.11.0 (Apple Git-81)                              |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12.5 (16F73)                                       |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.3.3                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.5.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
  end

  lane :beta do
    gym(
      scheme: "MyScheme",
      output_directory: "fastlane/build/"
      )
    pilot(
	    skip_waiting_for_build_processing: true,
    )
  end

  # desc "Deploy a new version to the App Store"
  # lane :release do
    # match(type: "appstore")
    # snapshot
    # gym # Build your app - more options available
    # deliver(force: true)
    # frameit
  # end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.company.app"
apple_id "username@mail.com"

team_id "TeamID"
itc_team_id "ITC_TeamID"```
</details>

### fastlane gems

| Gem      | Version | Update-Status       |
| -------- | ------- | ------------------- |
| fastlane | 2.5.0   | 🚫 Update availaible |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version     |
| ------------------------- | ----------- |
| slack-notifier            | 1.5.1       |
| rouge                     | 1.11.1      |
| xcpretty                  | 0.2.4       |
| terminal-notifier         | 1.7.1       |
| plist                     | 3.2.0       |
| multipart-post            | 2.0.0       |
| word_wrap                 | 1.0.0       |
| babosa                    | 1.0.2       |
| colored                   | 1.2         |
| excon                     | 0.54.0      |
| http-cookie               | 1.0.3       |
| faraday-cookie_jar        | 0.0.6       |
| gh_inspector              | 1.0.2       |
| uber                      | 0.0.15      |
| representable             | 2.3.0       |
| retriable                 | 2.1.0       |
| mime-types-data           | 3.2016.0521 |
| mime-types                | 3.1         |
| hurley                    | 0.2         |
| little-plugger            | 1.1.4       |
| multi_json                | 1.12.1      |
| logging                   | 2.1.0       |
| jwt                       | 1.5.6       |
| memoist                   | 0.15.0      |
| os                        | 0.9.6       |
| signet                    | 0.7.3       |
| googleauth                | 0.5.1       |
| google-api-client         | 0.9.20      |
| highline                  | 1.7.8       |
| json                      | 1.7.7       |
| mini_magick               | 4.5.1       |
| security                  | 0.1.3       |
| xcpretty-travis-formatter | 0.0.4       |
| dotenv                    | 2.1.1       |
| faraday_middleware        | 0.10.1      |
| i18n                      | 0.7.0       |
| thread_safe               | 0.3.5       |
| tzinfo                    | 1.2.2       |
| activesupport             | 4.2.7.1     |
| commander                 | 4.4.3       |
| rubyzip                   | 1.2.0       |
| nanaimo                   | 0.2.3       |
| xcodeproj                 | 1.4.2       |
| claide                    | 1.0.2       |
| bundler                   | 1.13.7      |
| terminal-table            | 1.7.3       |
| unicode-display_width     | 1.1.2       |
</details>


*generated on:* **2017-07-02**
</details>

**Comment by KrauseFx** [comment]
Hey @huynguyen-n, seems like there have been some server issues over the last few hours, could you give it another try? Has your setup like this already worked before?

**Comment by castus** [comment]
Unfortunately we have the same error on the newest version of fastlane. It is very weird, because it occurs when we use our Bamboo CI service but doesn't occur when I do it manually using terminal. Moreover CI service and manual run from terminal use the same user, the same env variables and the same machine. We had this issue for about 3 weeks. It comes from nowhere, just one day everything stopped working. Till today we are trying to solve it using the newest version of fastlane but it doesn't fix the issue :(


<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.11.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.9.3 (Apple Git-75)                               |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.11.6 (15G31)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.1                                                            |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.44.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.10.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 1.8.3        |
| claide                    | 1.0.2        |
</details>


*generated on:* **2017-07-03**
</details>

**Comment by huynguyen-n** [comment]
Hi guys, I have checked that with "fastlane init" and figure out error "Connection reset by peer - SSL_Connect" after input email for iTunes Connect then I fixed that with this link from raywenderlich https://www.raywenderlich.com/136168/fastlane-tutorial-getting-started-2 and I have fixed this problem, @castus can you follow that and check again, if fixed please tell me to close this issues. Thanks @KrauseFx.

**Comment by yakimant** [comment]
Have the same issue, appears randomly:
![sadas](https://www.evernote.com/l/ADm_DBCrDVhCba7tltt9uJ2BQ2yNXcnoFbsB/image.png)

**Comment by castus** [comment]
Me, together with @Aylard, have finally fixed this issue. In our case the problem was that we have two versions of Ruby in the system. When we update fastlane, we do it only for 2.0.0 but not for 2.3.1 which we are using to run fastlane. When we update fastlane on 2.3.1 everything works as expected.

Thanks @KrauseFx for you amazing work!

**Comment by yakimant** [comment]
@castus, so you run fastlane on ruby 2.3.1?
@KrauseFx, is ruby 2.0.0 still supported?

**Comment by castus** [comment]
@yakimant Actually we use only pilot from the whole toolbelt, but yes, we run it on 2.3.1

**Comment by KrauseFx** [comment]
Make sure to update Ruby to have the latest OpenSSL version, which is needed to communicate with back-end services 👍

**Comment by jjrebollo** [comment]
I just updated Ruby to the latest version:
`ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]`

But still getting this error:
`[!] The request could not be completed because:
	there is no web session to update`

Thoughts? :(

**Comment by KrauseFx** [comment]
Sorry, this is gonna be hard for us to debug, unless we have some steps to reproduce to fix the issue. Are you running into this problem on all Macs?

**Comment by jjrebollo** [comment]
I just got it working. I needed to go in Xcode to Preferences --> Account and there, re-log in the account I've been kicked out from.

This seems to be a recurrent issue on Xcode8.

**Comment by KrauseFx** [comment]
That's great to hear 👍
