### ISSUE TITLE
Deploy metadata to Google play

### ISSUE THREAD

**Issue by DevProgGo** [fastlane/fastlane#9779]
Hi Fastlane team!

How to deploy metadata like (list below) for Android?

1) Icon "Recommended"
2) Type and Category
3) Rating (Age)
4) Price and Distribution

**Comment by mpirri** [comment]
@DevProgGo Have you had a look at the _fastlane_ `supply` documentation? You can view it here: 
https://docs.fastlane.tools/getting-started/android/setup/
and also here:
https://docs.fastlane.tools/getting-started/android/release-deployment/

You should be able to invoke `fastlane supply init` for your project, and it will download the metadata for your project. You can then edit that metadata to set the values you want to set above.

I hope this helps, please let us know if you have other questions about _fastlane_! 🚀

**Comment by DevProgGo** [comment]
fastlane supply init - extracted only: name, description, screenshots and icon.

In the end, I would like to automate the creation of new applications. From the console, with one command)

**Comment by mpirri** [comment]
@DevProgGo A question - did you set the metadata you are asking about in the Google Play interface? I'm curious to know if `fastlane supply init` isn't seeing this metadata, or maybe it isn't filling it in because it is missing.

I think if you want to automate this process, you will have to construct the metadata file yourself and then run `fastlane supply run` using that metadata file.

Thanks! 🚀

**Comment by DevProgGo** [comment]
Yes. All Required Fields. App ready to publish.

But this all metadata:
![g-app](https://user-images.githubusercontent.com/29978607/28337673-14375320-6c0f-11e7-86a8-279bcaeea769.png)

I am not owner in google play account, maybe api limited for me?

**Comment by DevProgGo** [comment]
In supply.rb file i saw this: AVAILABLE_METADATA_FIELDS = %w(title short_description full_description video).
