### ISSUE TITLE
Fastlane Pilot able to define "What to test?" metadata?

### ISSUE THREAD

**Issue by jvanlint** [fastlane/fastlane#9789]
Does Pilot support the inclusion of a "What to test?" section that you can fill in the Connect Portal to tell testers what to look for in the uploaded build?

**Comment by mpirri** [comment]
@jvanlint You can set "What to Test" by setting the `changelog` when calling `pilot`. The naming convention is a bit confusing because Apple has changed the name of this field recently (and we should probably add a new alias to the `changelog` parameter to indicate it sets "What to Test"!)

So, you can do this (from the command line):
```
fastlane pilot distribute --changelog "What to test goes here"
```

Or from your Fastfile:
```
pilot(changelog: "What to test goes here")
```

I hope this is helpful, please let us know if you have any other questions about _fastlane_!  🚀

**Comment by jvanlint** [comment]
Cheers. Very helpful.
