### ISSUE TITLE
cert is left in directory and causes clean_build_artifacts to fail

### ISSUE THREAD

**Issue by karlzarsemd** [fastlane/fastlane#993]
When a build is complete and I want to commit the build version updates, I expect calling `clean_build_artifacts` to delete the certificate that was downloaded or that I'd be able to retrieve the file path of the cert so I could do that manually.  What I found works is to force an output_directory that is outside the src directory but then there's a requirements to write outside of the src dir and it still leaves artifacts behind.  
```
Found unexpected uncommited changes in the working directory. Expected these files to have 
changed: 
ProjectName.xcodeproj/project.pbxproj
ProjectName/Resources/Info.plist
ProjectNameTests/Info.plist
ProjectNameUITests/Info.plist.
But found these actual changes: 
ProjectName.xcodeproj/project.pbxproj
ProjectName/Resources/Info.plist
ProjectNameTests/Info.plist
ProjectNameUITests/Info.plist
AA2FYJ8C23.cer.
Make sure you have cleaned up the build artifacts and 
are only left with the changed version files at this stage in your lane, and don't touch the 
working directory while your lane is running. You can also use the :force option to bypass this 
check, and always commit a version bump regardless of the state of the working directory.

```

**Comment by Rking788** [comment]
i don't think the certificate is considered a 'build artifact' as it is not created or modified during the build process, so i don't think it will be removed by the `clean_build_artifacts` action. 

One option would be to use a subdirectory of your project's src directory and add that to your .gitignore file so it will not be seen as an uncommitted change and you won't have files written outside of your src directory. If you would like to commit your certificates to your repository this would not be helpful.

**Comment by ohwutup** [comment]
Hey @karlzarsemd! Thanks for submitting the issue! At first glance I believe that @Rking788 is correct, it would be good practice to save the certs to a local directory and add them to your `.gitignore`.

Let us know if you have any more questions at all, I am going to close the issue for now, but please feel free to re-open it if you find that you still have issues!

**Comment by KrauseFx** [comment]
Also, check out [match](https://github.com/fastlane/match) which manages certificates and provisioning profiles for you :+1:

**Comment by dusek** [comment]
Hello, I am not the OP, but have the exact same issue and would like the issue to be reopened.

To me the `*.cer` file the `cert` tool produces is the same kind of artifact as the `*.mobileprovision` file the `sigh` tool produces - i.e. created on the Developer Portal if needed, then downloaded. Yet `clean_build_artifacts` does clean the latter, but not the former. I do not understand the inconsistency.

Since the certificate file is not needed for anything I know (the private key and the certificate are in the keychain, so unlike `*.mobileprovision` file, this file is even a duplicate) and I will redownload it again during next build with `cert` tool, I do not need the `*cer` file really, just like I do not need the `*.mobileprovision` file after the build finishes (next build downloads it again).

So I currently have this hack in my `Fastfile`:

```ruby
    certname = cert
    FileUtils.rm("../#{certname}.cer")
```

It works, but I fear the relative path might change in future version of fastlane (and it is extra work for me to do).

So I personally would be in favor of `clean_build_artifacts` removing the `*.cer` file created by `cert` tool, the same way it removes the `*.mobileprovision` file created by `sigh`, to avoid unclean git state in `after_all` where commiting version bump and pushing it to git repo. I cannot use `reset_git_repo` for this, as that would clean also the version bump changes I need to commit.
